; ============================================================================
; UnoDOS / Sega Master System — milestone 1: boot to a rendered desktop.
; ============================================================================
; The FIRST UnoDOS port built fresh on the contract-driven + greenfield-window
; architecture (CONTRACT-ARCH §13). Bare-metal Z80 @ 3.58 MHz on the Sega VDP
; 315-5124 (Mode 4, 256x192 = 32x24 cells, 4bpp tiles, CRAM palette), 8 KB work
; RAM, the Sega mapper, the standard control pad. Built with sjasmplus into a
; plain 32 KB .sms cartridge image.
;
; Display model (mirrors the Genesis/SNES tile-VDP cousins): everything is
; composed on the name table as (tile) cells snapped to the 8px grid; the four
; UnoDOS theme colours live in CRAM. M1 draws the desktop only — the title bar
; and the labelled icon grid — consuming the Contract for the screen geometry
; and (when the WM lands) the window-entry layout.
;
; Contract-owned (CONTRACT-ARCH Phase 4): screen geometry + window-entry /
; event-queue layout are generated by unogen from unodef/unodef.toml
; ([world.sms]) so they can never drift from the Contract.
; ============================================================================

    include "../unodef/gen/sms/sys_gen.inc"   ; SCRW/SCRH/SCRCOLS/SCRROWS, W*, EV_*
    include "../unodef/gen/z80/unodef.inc"     ; the full Contract surface (SYS_*, enums)

; ---------------------------------------------------------------- hardware
VDP_DATA    EQU $BE
VDP_CTRL    EQU $BF
PORT_DC     EQU $DC                 ; controller port A
PORT_DD     EQU $DD                 ; controller port B
NAME_BASE   EQU $3800               ; tilemap base in VRAM
RAM_TOP     EQU $DFF0               ; stack top (8 KB RAM $C000-$DFFF)

; cell name-table entry helper: addr = NAME_BASE + (row*SCRCOLS + col)*2
NAME_OF     MACRO col, row
            ; -> hl = VRAM address of cell (col,row)
            ld hl, NAME_BASE + (row*SCRCOLS + col)*2
            ENDM

; ---------------------------------------------------------------- reset
; Canonical SMS startup: a jp over the RST / interrupt vector region, with the
; gaps filled by DEFS (sjasmplus --raw does not pad ORG jumps, so we never ORG
; forward — we emit a contiguous image).
    ORG $0000
reset:
    di
    im 1
    jp boot

    DEFS $0038-$, $00               ; pad to the maskable-INT vector
int_handler:                        ; $0038
    ei
    reti

    DEFS $0066-$, $00               ; pad to the NMI (pause button) vector
nmi_handler:                        ; $0066
    retn

boot:
    ld sp, RAM_TOP
    ; Sega mapper: slots 0/1/2 -> banks 0/1/2 (code lives in banks 0-1)
    xor a
    ld ($FFFC), a
    ld ($FFFD), a
    inc a
    ld ($FFFE), a
    inc a
    ld ($FFFF), a
    ; clear 8 KB work RAM
    ld hl, $C000
    ld de, $C001
    ld bc, $1FFF
    ld (hl), 0
    ldir

    call vdp_init
    call load_palette
    call load_tiles
    call clear_names
    call draw_desktop
    call display_on

main_loop:
    halt
    jr main_loop

; ---------------------------------------------------------------- VDP init
vdp_init:
    ld hl, vdp_regs
    ld b, vdp_regs_end - vdp_regs
    ld c, VDP_CTRL
    otir                            ; stream (value, reg|$80) pairs to control port
    ret

vdp_regs:
    db $04,$80      ; R0: Mode 4
    db $80,$81      ; R1: display OFF (bit7 set), 8x8 sprites
    db $FF,$82      ; R2: name table base = $3800
    db $FF,$83      ; R3: (unused in Mode 4)
    db $FF,$84      ; R4: (unused in Mode 4)
    db $FF,$85      ; R5: sprite attribute table = $3F00
    db $FF,$86      ; R6: sprite pattern table = $2000
    db $00,$87      ; R7: border/backdrop = sprite-palette index 0
    db $00,$88      ; R8: horizontal scroll = 0
    db $00,$89      ; R9: vertical scroll = 0
    db $FF,$8A      ; R10: line interrupt off
vdp_regs_end:

; turn the display on (R1 = $C0: bit7 + display-enable bit6)
display_on:
    ld a, $C0
    out (VDP_CTRL), a
    ld a, $81
    out (VDP_CTRL), a
    ret

; ---------------------------------------------------------------- palette
; Upload the 16-entry CRAM background palette, then the same 16 to the sprite
; palette (so the border/backdrop colour = desktop blue).
load_palette:
    xor a                           ; CRAM address 0
    out (VDP_CTRL), a
    ld a, $C0
    out (VDP_CTRL), a
    ld hl, palette
    ld b, 16
    ld c, VDP_DATA
    otir                            ; bg palette 0..15
    ld hl, palette
    ld b, 16
    otir                            ; sprite palette 16..31 (auto-incremented)
    ret

; ---------------------------------------------------------------- tiles
; Upload the whole tile blob (NTILES*32 bytes) to VRAM tile 0 ($0000).
load_tiles:
    ld hl, $0000                    ; VRAM tile area, write mode
    call vram_set_addr
    ld hl, tiles_all
    ld de, NTILES*32                ; byte count (de as 16-bit counter)
ltloop:
    ld a, (hl)
    out (VDP_DATA), a
    inc hl
    dec de
    ld a, d
    or e
    jr nz, ltloop
    ret

; ---------------------------------------------------------------- name table
; Clear the full 32x28 name table to tile 0 (solid desktop blue).
clear_names:
    ld hl, NAME_BASE
    call vram_set_addr
    ld de, SCRCOLS*28               ; 32*28 entries
cnloop:
    xor a
    out (VDP_DATA), a               ; tile low = 0
    out (VDP_DATA), a               ; flags/high = 0
    dec de
    ld a, d
    or e
    jr nz, cnloop
    ret

; ---------------------------------------------------------------- desktop
draw_desktop:
    ; --- title bar: fill row 0 with inverted blanks (white), then the title ---
    ld hl, NAME_BASE                ; row 0, col 0
    call vram_set_addr
    ld b, SCRCOLS
tbloop:
    ld a, T_FONTINV                 ; inverted space = solid white cell
    out (VDP_DATA), a
    xor a
    out (VDP_DATA), a
    djnz tbloop
    ; title text "UnoDOS 3" inverted at (1,0)
    ld d, 1
    ld e, 0
    ld hl, s_title
    ld c, T_FONTINV
    call puts_at

    ; --- icon grid: 4 columns (pitch 8, +1 margin), row = 3 + 7*(idx/4) -----
    ld ix, icon_tbl
    ld c, 0                         ; c = icon index (preserved across calls)
ig_next:
    ; col = (idx & 3)*8 + 1
    ld a, c
    and 3
    add a, a
    add a, a
    add a, a
    inc a
    ld d, a                         ; d = col
    ; row = 3 + 7*(idx/4)
    ld a, c
    srl a
    srl a                           ; a = group (0..2)
    ld e, a
    add a, a                        ; 2g
    add a, a                        ; 4g
    add a, e                        ; 5g
    add a, e                        ; 6g
    add a, e                        ; 7g
    add a, 3
    ld e, a                         ; e = row
    ; tile base = T_ICONS + idx*4
    ld a, c
    add a, a
    add a, a
    add a, T_ICONS
    push bc                         ; save icon index
    push de                         ; save col/row
    ld c, a                         ; c = TL tile
    call draw_icon
    pop de                          ; col/row back
    ; label centred-ish under the icon at (col, row+2)
    inc e
    inc e
    ld l, (ix+0)
    ld h, (ix+1)                    ; hl = label string ptr
    ld c, T_FONT
    call puts_at
    pop bc                          ; icon index back
    inc ix
    inc ix
    inc c
    ld a, c
    cp NICONS
    jr nz, ig_next
    ret

; ---- puts_at: D=col E=row, HL=string (NUL-term), C=tile base for ASCII 32 -
puts_at:
    push hl
    ; addr = NAME_BASE + (row*SCRCOLS + col)*2
    ld h, 0
    ld l, e
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl                      ; row*32
    ld b, 0
    ld a, d
    add a, l
    ld l, a
    ld a, b
    adc a, h
    ld h, a                         ; +col
    add hl, hl                      ; *2 (2 bytes/entry)
    ld de, NAME_BASE
    add hl, de
    call vram_set_addr
    pop hl
psloop:
    ld a, (hl)
    or a
    ret z
    sub 32
    add a, c
    out (VDP_DATA), a               ; tile low
    xor a
    out (VDP_DATA), a               ; flags
    inc hl
    jr psloop

; ---- draw_icon: D=col E=row, C=TL tile (TL,TR,BL,BR consecutive) ----------
draw_icon:
    push de
    push bc
    ; top row at (col,row): TL, TR
    ld h, 0
    ld l, e
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl                      ; row*32
    ld a, d
    add a, l
    ld l, a
    jr nc, $+3
    inc h
    add hl, hl                      ; (row*32+col)*2
    ld de, NAME_BASE
    add hl, de
    call vram_set_addr
    ld a, c                         ; TL
    out (VDP_DATA), a
    xor a
    out (VDP_DATA), a
    ld a, c
    inc a                           ; TR
    out (VDP_DATA), a
    xor a
    out (VDP_DATA), a
    ; bottom row at (col,row+1): BL, BR  -> previous addr + (SCRCOLS*2)
    pop bc
    pop de
    push de
    push bc
    inc e                           ; row+1
    ld h, 0
    ld l, e
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl
    ld a, d
    add a, l
    ld l, a
    jr nc, $+3
    inc h
    add hl, hl
    ld de, NAME_BASE
    add hl, de
    call vram_set_addr
    ld a, c
    add a, 2                        ; BL
    out (VDP_DATA), a
    xor a
    out (VDP_DATA), a
    ld a, c
    add a, 3                        ; BR
    out (VDP_DATA), a
    xor a
    out (VDP_DATA), a
    pop bc
    pop de
    ret

; ---- vram_set_addr: HL = VRAM address, sets write pointer -----------------
vram_set_addr:
    ld a, l
    out (VDP_CTRL), a
    ld a, h
    or $40                          ; write-to-VRAM command bits
    out (VDP_CTRL), a
    ret

; ---------------------------------------------------------------- strings
s_title:  db "UnoDOS 3",0

; icon label table (parallel to mkdata.py ICON order + paint)
icon_tbl:
    dw l_sysinfo, l_clock, l_notepad, l_music, l_files, l_theme
    dw l_tracker, l_dostris, l_outlast, l_pacman, l_paint
l_sysinfo:  db "SysInfo",0
l_clock:    db "Clock",0
l_notepad:  db "Notepad",0
l_music:    db "Music",0
l_files:    db "Files",0
l_theme:    db "Theme",0
l_tracker:  db "Tracker",0
l_dostris:  db "Dostris",0
l_outlast:  db "OutLast",0
l_pacman:   db "Pac-Man",0
l_paint:    db "Paint",0

; ---------------------------------------------------------------- data blob
    include "gen_data.inc"          ; tiles_all, palette, NTILES, T_*, NICONS

; ---------------------------------------------------------------- ROM header
    DEFS $7FF0-$, $00
    db "TMR SEGA"                   ; $7FF0 magic
    db $00,$00                      ; $7FF8 reserved
    db $00,$00                      ; $7FFA checksum (ignored by emulators)
    db $00,$00,$00                  ; $7FFC product code + version
    db $4C                          ; $7FFF region=export(4), size=32KB(C)
    DEFS $8000-$, $00
