#!/usr/bin/env python3
# Convert a curated set of CA root PEMs into a BearSSL trust-anchor C array
# (tls_ca.c). Run once when the root set changes; the output is checked in so
# the normal build needs no Python crypto. Roots are read from the system
# ca-certificates store (/etc/ssl/certs).
import os, sys
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import rsa, ec

CERTS = "/etc/ssl/certs"
ROOTS = [
    "ISRG_Root_X1", "ISRG_Root_X2",
    "DigiCert_Global_Root_CA", "DigiCert_Global_Root_G2", "DigiCert_Global_Root_G3",
    "Baltimore_CyberTrust_Root",
    "GlobalSign_Root_CA", "GlobalSign_Root_CA_-_R3", "GlobalSign_Root_CA_-_R6",
    "USERTrust_RSA_Certification_Authority", "USERTrust_ECC_Certification_Authority",
    "Amazon_Root_CA_1", "GTS_Root_R1",
    "Go_Daddy_Root_Certificate_Authority_-_G2",
]
# BearSSL curve ids (bearssl_ec.h) + field byte sizes
CURVE = {"secp256r1": (23, 32), "secp384r1": (24, 48), "secp521r1": (25, 66)}

def carr(name, data):
    out = ["static const unsigned char %s[] = {" % name]
    line = "\t"
    for i, b in enumerate(data):
        line += "0x%02X," % b
        if (i % 12) == 11: out.append(line); line = "\t"
    if line.strip(): out.append(line)
    out.append("};")
    return "\n".join(out)

def be(n):                              # int -> minimal big-endian bytes
    if n == 0: return b"\x00"
    return n.to_bytes((n.bit_length() + 7) // 8, "big")

def main():
    pieces, entries = [], []
    idx = 0
    # extra PEM paths on argv are appended (used to inject a test CA for local
    # handshake verification; the committed bundle is generated with no args).
    paths = [os.path.join(CERTS, r + ".pem") for r in ROOTS] + sys.argv[1:]
    for path in paths:
        if not os.path.exists(path):
            sys.stderr.write("skip (missing): %s\n" % path); continue
        cert = x509.load_pem_x509_certificate(open(path, "rb").read())
        dn = cert.subject.public_bytes()          # DER of the Subject Name
        pub = cert.public_key()
        p = "TA%d" % idx
        pieces.append(carr(p + "_DN", dn))
        if isinstance(pub, rsa.RSAPublicKey):
            nums = pub.public_numbers()
            pieces.append(carr(p + "_N", be(nums.n)))
            pieces.append(carr(p + "_E", be(nums.e)))
            key = ("{ BR_KEYTYPE_RSA, { .rsa = { (unsigned char*)%s_N, sizeof %s_N,"
                   " (unsigned char*)%s_E, sizeof %s_E } } }" % (p, p, p, p))
        elif isinstance(pub, ec.EllipticCurvePublicKey):
            cn = pub.curve.name
            if cn not in CURVE: sys.stderr.write("skip (curve %s): %s\n" % (cn, path)); pieces.pop(); continue
            cid, flen = CURVE[cn]
            nums = pub.public_numbers()
            q = b"\x04" + nums.x.to_bytes(flen, "big") + nums.y.to_bytes(flen, "big")
            pieces.append(carr(p + "_Q", q))
            key = "{ BR_KEYTYPE_EC, { .ec = { %d, (unsigned char*)%s_Q, sizeof %s_Q } } }" % (cid, p, p)
        else:
            sys.stderr.write("skip (key type): %s\n" % path); pieces.pop(); continue
        entries.append("\t{ { (unsigned char*)%s_DN, sizeof %s_DN }, BR_X509_TA_CA,\n\t  %s }," % (p, p, key))
        sys.stderr.write("  + %s\n" % path)
        idx += 1

    with open("tls_ca.c", "w", newline="\n") as f:
        f.write("/* GENERATED by mktrust.py - BearSSL CA trust anchors for HTTPS.\n"
                " * A curated subset of the system root store (%d roots), enough to\n"
                " * validate the common public CAs. Regenerate when the set changes. */\n" % idx)
        f.write('#include "bearssl.h"\n#include "tls_ca.h"\n\n')
        f.write("\n\n".join(pieces))
        f.write("\n\nconst br_x509_trust_anchor uno_tls_tas[] = {\n")
        f.write("\n".join(entries))
        f.write("\n};\nconst size_t uno_tls_tas_num = %d;\n" % idx)
    sys.stderr.write("wrote tls_ca.c: %d trust anchors\n" % idx)

main()
