/* ===========================================================================
 * UnoDOS/pc64 - Clock: an analog face, a world map with the day/night
 * terminator, and a world-time list.
 *
 * Replaces the old two-label Clock (a digital string and "(firmware RTC)").
 *
 * Two canvases, both earning it: an analog dial is per-pixel geometry, and a
 * shaded world map is per-pixel by definition. Everything around them - the
 * UTC-offset spinner, the city list, the digital readout - is ordinary unoui
 * widgets, so the whole app follows the theme.
 *
 * ---- the terminator --------------------------------------------------------
 * Day/night is real spherical geometry, not a drawn curve. The subsolar point
 * is at longitude 180 - 15*UTC_hours and at a latitude equal to the solar
 * declination, which is approximated from the day of year by
 *   decl = 23.44 deg * sin(360/365 * (N + 284))
 * A point is in daylight when
 *   sin(lat)sin(decl) + cos(lat)cos(decl)cos(lon - sublon) > 0
 * which is evaluated per map pixel. That gets the seasons right for free: the
 * Arctic is lit around the June solstice and dark around December, and the
 * terminator tilts rather than running straight down the map.
 *
 * ---- what the RTC gives us --------------------------------------------------
 * The firmware RTC has no time zone attached, so nothing here can know the
 * machine's offset from UTC. Rather than guess, the app asks: the "UTC offset"
 * spinner states what local time IS, and every world time is derived from
 * it. Default 0 - i.e. "the RTC is UTC" - which is what a machine with no
 * other information should assume. There is no DST handling and the UI says
 * so; DST rules are a political database, not arithmetic, and shipping a
 * half-right one would be worse than being explicit.
 * ======================================================================== */
#include "unoui.h"
#include "unoui_theme.h"
#include "pc64_icons.h"     /* pc64_shell_theme */
#include "mac_compat.h"     /* uno_pc64_time */
#include "build/world_map.h"  /* generated by tools/mkworldmap.py */
#include <string.h>

float sinf(float x);
float cosf(float x);

void pc64_shell_dirty(void);
int  pc64_shell_workarea_w(void);
int  pc64_shell_workarea_h(void);

/* ---- widget ids (700..719 reserved for Clock) ------------------------------ */
enum { CID_UTC = 700, CID_CITIES };

#define DEG2RAD 0.01745329f
#define CLOCK_Y 24                  /* where the window opens, vertically */

/* ---- the city table --------------------------------------------------------
 * Offsets are in MINUTES, because several of these are not whole hours (India
 * is +5:30, and it is exactly the kind of thing a clock app gets wrong). */
typedef struct {
    const char *name;
    float lat, lon;
    short off_min;
} city;

static const city kCities[] = {
    { "London",      51.5f,   -0.1f,     0 },
    { "Berlin",      52.5f,   13.4f,    60 },
    { "Moscow",      55.8f,   37.6f,   180 },
    { "Dubai",       25.2f,   55.3f,   240 },
    { "Mumbai",      19.1f,   72.9f,   330 },
    { "Beijing",     39.9f,  116.4f,   480 },
    { "Tokyo",       35.7f,  139.7f,   540 },
    { "Sydney",     -33.9f,  151.2f,   600 },
    { "Auckland",   -36.8f,  174.8f,   720 },
    { "Honolulu",    21.3f, -157.9f,  -600 },
    { "Los Angeles", 34.1f, -118.2f,  -480 },
    { "Denver",      39.7f, -105.0f,  -420 },
    { "Chicago",     41.9f,  -87.6f,  -360 },
    { "Toronto",     43.7f,  -79.4f,  -300 },
    { "New York",    40.7f,  -74.0f,  -300 },
    { "Sao Paulo",  -23.5f,  -46.6f,  -180 },
    { "Reykjavik",   64.1f,  -21.9f,     0 },
    { "Cairo",       30.0f,   31.2f,   120 },
    { "Nairobi",     -1.3f,   36.8f,   180 },
    { "Cape Town",  -33.9f,   18.4f,   120 },
};
#define NCITY ((int)(sizeof kCities / sizeof kCities[0]))

/* ---- state ------------------------------------------------------------------ */
static int   cl_utc_off = 0;            /* local time = UTC + this, in MINUTES */
static char  cl_items[NCITY][40];
static const char *cl_ptr[NCITY];
static char  cl_digital[48];
static char  cl_date[48];
static int   cl_sel;
static unoui_widget *cl_list_w;

/* ---- small helpers ----------------------------------------------------------- */
static char *ccat(char *p, const char *s) { while (*s) *p++ = *s++; return p; }
static char *c2(char *p, int v)
{ *p++ = (char)('0' + (v / 10) % 10); *p++ = (char)('0' + v % 10); return p; }
static char *cint(char *p, long v)
{
    char t[12]; int n = 0;
    if (v < 0) { *p++ = '-'; v = -v; }
    if (!v) t[n++] = '0';
    while (v) { t[n++] = (char)('0' + v % 10); v /= 10; }
    while (n) *p++ = t[--n];
    return p;
}

/* days since Jan 1 (0-based), for the solar declination */
static int day_of_year(int y, int mo, int d)
{
    static const int cum[12] = { 0,31,59,90,120,151,181,212,243,273,304,334 };
    int n;
    if (mo < 1) mo = 1; if (mo > 12) mo = 12;
    n = cum[mo - 1] + d - 1;
    if (mo > 2 && ((y % 4 == 0 && y % 100 != 0) || y % 400 == 0)) n++;
    return n;
}

/* current UTC as minutes since midnight, plus the date, from the RTC */
static void now_utc(int *utc_min, int *sec, int *yy, int *mo, int *dd)
{
    int y = 2026, m = 1, d = 1, h = 0, mi = 0, s = 0;
    long t;
    uno_pc64_time(&y, &m, &d, &h, &mi, &s);
    t = (long)h * 60 + mi - cl_utc_off;          /* RTC shows LOCAL time */
    /* carry the date across a midnight the offset pushed us over */
    while (t < 0)      { t += 1440; d--; }
    while (t >= 1440)  { t -= 1440; d++; }
    if (d < 1)  { m--; if (m < 1) { m = 12; y--; } d = 31; }   /* coarse: only
                    used for the solar declination, where a day is noise */
    if (d > 31) { d = 1; m++; if (m > 12) { m = 1; y++; } }
    *utc_min = (int)t; *sec = s; *yy = y; *mo = m; *dd = d;
}

/* ---- the analog face ---------------------------------------------------------- */
/* Bresenham, clip-safe via fb_pixel. A dial needs arbitrary-angle lines and
 * fb.h only offers h/v spans, so this is the missing primitive. */
static void line(int x0, int y0, int x1, int y1, fb_px c)
{
    int dx = x1 - x0, dy = y1 - y0, sx = dx < 0 ? -1 : 1, sy = dy < 0 ? -1 : 1;
    int err, e2;
    if (dx < 0) dx = -dx;
    if (dy < 0) dy = -dy;
    err = dx - dy;
    for (;;) {
        fb_pixel(x0, y0, c);
        if (x0 == x1 && y0 == y1) break;
        e2 = err * 2;
        if (e2 > -dy) { err -= dy; x0 += sx; }
        if (e2 <  dx) { err += dx; y0 += sy; }
    }
}

/* a hand with some width: draw parallel offsets rather than a real polygon */
static void hand(int cx, int cy, float ang, int len, int wide, fb_px c)
{
    float s = sinf(ang), co = cosf(ang);
    int ex = cx + (int)(s * len), ey = cy - (int)(co * len);
    int i;
    line(cx, cy, ex, ey, c);
    for (i = 1; i <= wide; i++) {
        /* perpendicular = (cos, sin) in screen space */
        int ox = (int)(co * i), oy = (int)(s * i);
        line(cx + ox, cy + oy, ex + ox, ey + oy, c);
        line(cx - ox, cy - oy, ex - ox, ey - oy, c);
    }
}

static void circle(int cx, int cy, int r, fb_px c)
{
    int x = r, y = 0, err = 1 - r;
    while (x >= y) {
        fb_pixel(cx + x, cy + y, c); fb_pixel(cx + y, cy + x, c);
        fb_pixel(cx - y, cy + x, c); fb_pixel(cx - x, cy + y, c);
        fb_pixel(cx - x, cy - y, c); fb_pixel(cx - y, cy - x, c);
        fb_pixel(cx + y, cy - x, c); fb_pixel(cx + x, cy - y, c);
        y++;
        if (err < 0) err += 2 * y + 1;
        else { x--; err += 2 * (y - x) + 1; }
    }
}

static void face_draw(struct unoui_widget *w, unoui_rect r, void *ctx)
{
    const unoui_theme *t = pc64_shell_theme();
    int utc, sec, yy, mo, dd, i;
    int cx = r.x + r.w / 2, cy = r.y + r.h / 2;
    int rad = (r.w < r.h ? r.w : r.h) / 2 - 2;
    int lmin;
    (void)w; (void)ctx;
    if (rad < 8) return;
    now_utc(&utc, &sec, &yy, &mo, &dd);
    lmin = utc + cl_utc_off;
    while (lmin < 0) lmin += 1440;
    lmin %= 1440;

    fb_fill_rect(r.x, r.y, r.w, r.h, t->pal.field_bg);
    circle(cx, cy, rad, t->pal.text);
    /* hour ticks: long at 12/3/6/9 */
    for (i = 0; i < 12; i++) {
        float a = (float)i * 30.0f * DEG2RAD;
        int o = (i % 3 == 0) ? rad - 8 : rad - 4;
        int x0 = cx + (int)(sinf(a) * o),     y0 = cy - (int)(cosf(a) * o);
        int x1 = cx + (int)(sinf(a) * (rad - 1)), y1 = cy - (int)(cosf(a) * (rad - 1));
        line(x0, y0, x1, y1, (i % 3 == 0) ? t->pal.text : t->pal.text_dim);
    }
    {
        int hh = lmin / 60, mm = lmin % 60;
        float ah = ((float)(hh % 12) + (float)mm / 60.0f) * 30.0f * DEG2RAD;
        float am = ((float)mm + (float)sec / 60.0f) * 6.0f * DEG2RAD;
        float as = (float)sec * 6.0f * DEG2RAD;
        hand(cx, cy, ah, rad / 2,        2, t->pal.text);
        hand(cx, cy, am, rad * 4 / 5,    1, t->pal.text);
        hand(cx, cy, as, rad * 9 / 10,   0, t->pal.accent);
    }
    fb_fill_rect(cx - 2, cy - 2, 5, 5, t->pal.accent);
}
static int face_event(struct unoui_widget *w, const void *ev, void *ctx)
{ (void)w; (void)ev; (void)ctx; return 0; }
static unoui_canvas cl_face = { face_draw, face_event, 0 };

/* ---- the world map ------------------------------------------------------------- */
static int land_at(int mx, int my)
{
    int rb = (WORLD_W + 7) / 8;
    if (mx < 0 || mx >= WORLD_W || my < 0 || my >= WORLD_H) return 0;
    return (kWorldMap[my * rb + (mx >> 3)] >> (7 - (mx & 7))) & 1;
}

static void map_draw(struct unoui_widget *w, unoui_rect r, void *ctx)
{
    const unoui_theme *t = pc64_shell_theme();
    int utc, sec, yy, mo, dd, px, py, i;
    float decl, sublon, sd, cd;
    (void)w; (void)ctx;
    now_utc(&utc, &sec, &yy, &mo, &dd);

    /* solar declination from the day of year, and the subsolar longitude */
    decl = 23.44f * sinf((360.0f / 365.0f) * (float)(day_of_year(yy, mo, dd) + 284)
                         * DEG2RAD) * DEG2RAD;
    sublon = 180.0f - (float)utc * 0.25f;         /* 15 deg per hour = 0.25/min */
    sd = sinf(decl); cd = cosf(decl);

    for (py = 0; py < r.h; py++) {
        int my = py * WORLD_H / r.h;
        float lat = (90.0f - ((float)my + 0.5f) * 180.0f / WORLD_H) * DEG2RAD;
        float sl = sinf(lat), cl = cosf(lat);
        for (px = 0; px < r.w; px++) {
            int mx = px * WORLD_W / r.w;
            float lon = (((float)mx + 0.5f) * 360.0f / WORLD_W) - 180.0f;
            float ha = (lon - sublon) * DEG2RAD;
            int day = (sl * sd + cl * cd * cosf(ha)) > 0.0f;
            int isl = land_at(mx, my);
            fb_px c;
            if (isl) c = day ? t->pal.accent : t->pal.text_dim;
            else     c = day ? t->pal.field_bg : t->pal.win_bg;
            fb_pixel(r.x + px, r.y + py, c);
        }
    }
    fb_frame_rect(r.x, r.y, r.w, r.h, t->pal.text_dim);

    /* city markers, with the selected one picked out */
    for (i = 0; i < NCITY; i++) {
        int x = r.x + (int)((kCities[i].lon + 180.0f) * (float)r.w / 360.0f);
        int y = r.y + (int)((90.0f - kCities[i].lat) * (float)r.h / 180.0f);
        if (i == cl_sel) {
            fb_fill_rect(x - 2, y - 2, 5, 5, t->pal.text);
            fb_fill_rect(x - 1, y - 1, 3, 3, t->pal.field_bg);
        } else {
            fb_fill_rect(x, y, 2, 2, t->pal.text);
        }
    }
}
static int map_event(struct unoui_widget *w, const void *evp, void *ctx)
{
    const unoui_event *e = (const unoui_event *)evp;
    (void)w; (void)ctx;
    if (e->kind != UI_EV_MOUSE_DOWN) return 0;
    return 0;                    /* the list is the selector; the map displays */
}
static unoui_canvas cl_map = { map_draw, map_event, 0 };

/* ---- the readouts --------------------------------------------------------------- */
static void refresh_text(void)
{
    static const char *kMon[12] = { "Jan","Feb","Mar","Apr","May","Jun",
                                    "Jul","Aug","Sep","Oct","Nov","Dec" };
    int utc, sec, yy, mo, dd, i;
    char *p;
    now_utc(&utc, &sec, &yy, &mo, &dd);

    {   /* local digital time */
        int lmin = utc + cl_utc_off;
        while (lmin < 0) lmin += 1440;
        lmin %= 1440;
        p = c2(cl_digital, lmin / 60); *p++ = ':';
        p = c2(p, lmin % 60);          *p++ = ':';
        p = c2(p, sec);
        p = ccat(p, "  local  (UTC");
        if (cl_utc_off >= 0) *p++ = '+';
        p = cint(p, cl_utc_off / 60);
        if (cl_utc_off % 60) { *p++ = ':'; p = c2(p, (cl_utc_off < 0 ? -cl_utc_off : cl_utc_off) % 60); }
        *p++ = ')';
        *p = 0;
    }
    {   /* the date, plus UTC for reference */
        p = cint(cl_date, dd); *p++ = ' ';
        p = ccat(p, kMon[(mo - 1) % 12]); *p++ = ' ';
        p = cint(p, yy);
        p = ccat(p, "   UTC ");
        p = c2(p, utc / 60); *p++ = ':'; p = c2(p, utc % 60);
        *p = 0;
    }
    for (i = 0; i < NCITY; i++) {   /* the world-time rows */
        int m = utc + kCities[i].off_min, dayshift = 0;
        while (m < 0)     { m += 1440; dayshift--; }
        while (m >= 1440) { m -= 1440; dayshift++; }
        p = ccat(cl_items[i], kCities[i].name);
        while (p < cl_items[i] + 12) *p++ = ' ';
        p = c2(p, m / 60); *p++ = ':'; p = c2(p, m % 60);
        if (dayshift > 0) p = ccat(p, " +1d");
        else if (dayshift < 0) p = ccat(p, " -1d");
        *p = 0;
        cl_ptr[i] = cl_items[i];
    }
}

/* Called every shell frame while the window is open, but a clock only has
 * something new to say once a second - so recompute and repaint on the second
 * boundary and do nothing the rest of the time. Without this the second hand
 * would pin the compositor at frame rate for no visible gain. */
void pc64_clock_tick(void)
{
    static int last = -1;
    int utc, sec, yy, mo, dd;
    now_utc(&utc, &sec, &yy, &mo, &dd);
    if (sec == last) return;
    last = sec;
    refresh_text();
    pc64_shell_dirty();
}

int pc64_clock_action(const unoui_action *a)
{
    if (a->id < 700 || a->id >= 720) return 0;
    switch (a->id) {
    case CID_UTC:
        cl_utc_off = a->value * 60;      /* the spinner is in whole hours */
        break;
    case CID_CITIES:
        if (a->value >= 0 && a->value < NCITY) cl_sel = a->value;
        break;
    default: return 0;
    }
    refresh_text();
    pc64_shell_dirty();
    return 1;
}

/* ---- window build ----------------------------------------------------------------- */
void pc64_clock_build(unoui_window *w)
{
    const unoui_theme *t = pc64_shell_theme();
    int fh = fb_text_h(), ch = ui_field_h();
    unoui_widget *x;
    int waw = pc64_shell_workarea_w(), wah = pc64_shell_workarea_h();
    int pad = 8, faceh, mapw, maph, cw;
    int chrome, listh, y;

    /* The shell can be running anywhere from 640x400 to 1920x1200, so nothing
     * here is a fixed pixel count: the map is sized as a fraction of the work
     * area (keeping the 2:1 ratio equirectangular demands), the dial matches
     * its height, and the city list takes whatever is left. */
    mapw = waw * 2 / 5;
    if (mapw < 160) mapw = 160;
    if (mapw > 288) mapw = 288;
    maph = mapw / 2;
    faceh = maph;
    if (faceh > 132) faceh = 132;
    cw = faceh + pad + mapw;

    chrome = 2 + (faceh > maph ? faceh : maph) + 6
           + 2 * (fh + 2) + 6                       /* digital + date        */
           + ch + 6                                 /* offset row            */
           + fh + 2                                 /* "World times" label   */
           + 8 + 4
           + t->m.title_h + t->m.frame_w + 2 * t->m.pad;
    /* whatever is left below the window's own top edge (CLOCK_Y), less a
       margin so the frame never touches the taskbar */
    listh = wah - CLOCK_Y - 12 - chrome;
    if (listh > 8 * (fh + 6) + 8) listh = 8 * (fh + 6) + 8;
    if (listh < 3 * (fh + 6) + 8) listh = 3 * (fh + 6) + 8;

    refresh_text();
    unoui_window_init(w, "Clock", 300, CLOCK_Y, 1, 1);

    y = 2;
    /* the analog dial and the world map sit side by side on the top row */
    unoui_add_canvas(w, 0, y, faceh, faceh, &cl_face);
    unoui_add_canvas(w, faceh + pad, y, mapw, maph, &cl_map);
    y += (faceh > maph ? faceh : maph) + 6;

    unoui_add_label(w, 0, y, cl_digital); y += fh + 2;
    unoui_add_label(w, 0, y, cl_date);    y += fh + 6;

    unoui_add_label(w, 0, y + (ch - fh) / 2, "UTC offset (hours):");
    x = unoui_add_spinner(w, fb_text_w("UTC offset (hours):") + 8, y, 70,
                          -12, 14, cl_utc_off / 60);
    x->id = CID_UTC;
    unoui_add_label(w, fb_text_w("UTC offset (hours):") + 86, y + (ch - fh) / 2,
                    "standard time - no DST");
    y += ch + 6;

    unoui_add_label(w, 0, y, "World times"); y += fh + 2;
    /* The list is the LAST widget, so marking it fill is correct here: on
     * resize it stretches to the content edge and nothing sits below it to be
     * swallowed. (The Music window's list is mid-layout and must not do this.) */
    x = unoui_add_list(w, 0, y, cw, listh, cl_ptr, NCITY, cl_sel);
    x->id = CID_CITIES; cl_list_w = x; (void)cl_list_w;
    unoui_widget_fill(x);
    y += listh + 4;

    w->r.w = cw + 2 * t->m.frame_w + 2 * t->m.pad;
    w->r.h = y + t->m.title_h + t->m.frame_w + 2 * t->m.pad;
    w->min_w = w->r.w;
    w->min_h = chrome + 3 * (fh + 6) + 8 + 4;
    w->flags |= UI_WIN_RESIZE;
    unoui_reflow_window(t, w);
}
