/* ===========================================================================
 * UnoDOS/pc64 - TLS client glue (see tls.h). BearSSL does all the crypto.
 * ======================================================================== */
#include "bearssl.h"
#include "tls.h"
#include "tls_ca.h"      /* bundled CA trust anchors for HTTPS */
#include "unoauto.h"     /* cooperative test deadline; compiles away in prod */
#include <string.h>
#include <stdint.h>

/* ---- the PINNED server public key (P-256 uncompressed point) -------------
 * PINNED_EC_Q is generated by pc64/tls_test/gen.sh (public key only, so it is
 * safe to commit; server.key/.crt stay local). Pinning it IS the trust anchor
 * - the handshake only succeeds if the server proves possession of this key. */
#include "tls_test/pinned_key.h"

/* millisecond delay from the pc64 kernel - used to pace + time-bound the
 * transport waits below so a black-holed peer cannot busy-spin the UI. */
void uno_pc64_delay_ms(int ms);

/* Debug-build transport trace: fires only on failure paths (EOF, deadlines,
 * flush errors), so a dead TLS exchange names its layer in the kernel log
 * instead of surfacing as a bare BR_ERR_IO. Compiles away in production. */
#ifdef UNO_DEBUG
void uno_dbg_log(const char *fmt, ...);
#define TLSTRACE(...) uno_dbg_log(__VA_ARGS__)
#else
#define TLSTRACE(...) ((void)0)
#endif

/* sysrng.c is excluded (it pulls CPU intrinsics); ssl_engine calls this to
   look for a system seeder. We return "none" and inject entropy directly. */
br_prng_seeder br_prng_seeder_system(const char **name)
{
    if (name) *name = "none";
    return 0;
}

/* ---- cooperative test deadline ------------------------------------------
 * unoauto's TEST runner arms a per-check wall-clock budget, but a synchronous
 * runner cannot preempt a wait loop that is blocked inside one call - so the
 * live network checks (S-AI-01/02, S-NET-30) could sit here past the budget and
 * the whole SPECTEST batch reported "guest did not power off (hang?)". The
 * runner exports unoauto_deadline_left_ms() precisely so the long waits opt in
 * and bail; this is that half. 0 = out of budget, -1 = no budget armed (the
 * production case, where the macro folds it to a constant -1 and the test
 * compiles out entirely). */
#define TLS_OUT_OF_BUDGET() (unoauto_deadline_left_ms() == 0)

/* ---- low-level record transport over the pc64 TCP stack ----------------- */
static int low_read(void *ctx, unsigned char *buf, size_t len)
{
    long tries = 6000000;       /* hard iteration ceiling (backstop) */
    int  ms = 0;                /* accumulated wall-clock wait */
    (void)ctx;
    for (;;) {
        /* poll FIRST, then drain: when one poll batch delivers the last data
         * segment AND the peer's FIN together (Connection: close servers do
         * exactly this), checking the state before re-reading the queue threw
         * away the just-arrived bytes and reported EOF - the S-AI-02 bug. A
         * DONE state is EOF only once the queue is empty. */
        int n;
        net_poll();
        n = net_tcp_recv(buf, (int)len);
        if (n > 0) return n;
        { int st = net_tcp_state(); if (st == TCP_DONE || st == TCP_CLOSED) {
              TLSTRACE("tls: low_read EOF (tcp state %d after %d ms)", st, ms); return -1; } }
        uno_pc64_delay_ms(1);                   /* pace the idle wait to ~1ms/poll */
        if (++ms > 4000) { TLSTRACE("tls: low_read -1 (4s idle deadline)"); return -1; }
        if (TLS_OUT_OF_BUDGET()) {
            TLSTRACE("tls: low_read -1 (test budget exhausted after %d ms)", ms); return -1; }
        if (--tries <= 0) return -1;
    }
}
static int low_write(void *ctx, const unsigned char *buf, size_t len)
{
    int off = 0;
    long tries = 12000000;      /* hard iteration ceiling (backstop) */
    int  ms = 0;                /* accumulated wall-clock wait */
    (void)ctx;
    while (off < (int)len) {
        int chunk = (int)len - off;
        int r;
        if (chunk > 512) chunk = 512;
        r = net_tcp_send(buf + off, chunk);   /* -1 while a segment is unacked */
        if (r > 0) off += r;
        net_poll();
        if (net_tcp_state() != TCP_ESTABLISHED) {
            TLSTRACE("tls: low_write %d/%d (tcp state %d)", off, (int)len, net_tcp_state());
            return (off > 0) ? off : -1;
        }
        if (r <= 0) {                          /* no progress: pace + bound the wait */
            uno_pc64_delay_ms(1);
            if (++ms > 8000) { TLSTRACE("tls: low_write %d/%d (8s deadline)", off, (int)len);
                               return (off > 0) ? off : -1; }   /* ~8s deadline */
            if (TLS_OUT_OF_BUDGET()) {
                TLSTRACE("tls: low_write %d/%d (test budget exhausted)", off, (int)len);
                return (off > 0) ? off : -1; }
        }
        if (--tries <= 0) return (off > 0) ? off : -1;
    }
    return off;
}

/* ---- context ------------------------------------------------------------ */
static br_ssl_client_context   g_sc;
static br_x509_minimal_context g_xm;      /* scratch for init_full (overridden) */
static br_x509_knownkey_context g_kk;
static br_sslio_context        g_io;
static unsigned char           g_iobuf[BR_SSL_BUFSIZE_MONO];
static int g_open;

int tls_connect(const u8 dst[4], u16 port, const char *sni)
{
    unsigned char seed[32];
    br_ec_public_key pk;
    long t;

    /* Checked BEFORE the socket exists: a box with no usable RNG must never
     * open a connection it cannot secure, and the caller gets a distinct
     * reason instead of a generic handshake failure. */
    if (tls_entropy_source() == TLS_ENT_NONE) {
        TLSTRACE("tls: refusing connect - no usable entropy source");
        return TLS_ENOENTROPY;
    }
    if (net_tcp_connect(dst, port) != 0) return -1;
    t = 4000000;                                /* hard iteration ceiling (backstop) */
    { int ms = 0;
      while (net_tcp_state() != TCP_ESTABLISHED) {
        net_poll();
        { int st = net_tcp_state(); if (st == TCP_DONE || st == TCP_CLOSED) return -2; }
        uno_pc64_delay_ms(1);
        if (++ms > 3000) return -2;             /* ~3s deadline: SYN went unanswered */
        if (TLS_OUT_OF_BUDGET()) return -2;     /* the test's budget ran out first */
        if (--t <= 0) return -2;
      } }

    /* suites + algorithms from the standard client profile... */
    br_ssl_client_init_full(&g_sc, &g_xm, 0, 0);
    /* ...but replace CA/chain validation with a PINNED key */
    pk.curve = BR_EC_secp256r1;
    pk.q = (unsigned char *)PINNED_EC_Q;
    pk.qlen = sizeof PINNED_EC_Q;
    br_x509_knownkey_init_ec(&g_kk, &pk, BR_KEYTYPE_KEYX | BR_KEYTYPE_SIGN);
    br_ssl_engine_set_x509(&g_sc.eng, &g_kk.vtable);

    br_ssl_engine_set_buffer(&g_sc.eng, g_iobuf, sizeof g_iobuf, 0);
    if (!tls_entropy_get(seed, sizeof seed)) return TLS_ENOENTROPY;  /* source died */
    br_ssl_engine_inject_entropy(&g_sc.eng, seed, sizeof seed);
    memset(seed, 0, sizeof seed);

    if (br_ssl_client_reset(&g_sc, sni, 0) != 1) return -3;
    br_sslio_init(&g_io, &g_sc.eng, low_read, 0, low_write, 0);
    g_open = 1;
    return 0;                       /* handshake completes on first I/O */
}

/* current UTC time as BearSSL's (days since 0 AD, seconds since midnight);
 * Unix epoch = days 719528. Sourced from the UEFI RTC (uno_pc64_time). */
void uno_pc64_time(int *y, int *mo, int *d, int *h, int *mi, int *s);
static void tls_now(uint32_t *days, uint32_t *secs)
{
    int y = 1970, mo = 1, d = 1, h = 0, mi = 0, s = 0;
    long yy, era, yoe, doy, doe, ud; int m;
    uno_pc64_time(&y, &mo, &d, &h, &mi, &s);
    yy = y; m = mo; yy -= (m <= 2);                 /* days_from_civil (Hinnant) */
    era = (yy >= 0 ? yy : yy - 399) / 400;
    yoe = yy - era * 400;
    doy = (153 * (m + (m > 2 ? -3 : 9)) + 2) / 5 + d - 1;
    doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    ud  = era * 146097 + doe - 719468;              /* days since 1970-01-01 */
    *days = (uint32_t)(ud + 719528);
    *secs = (uint32_t)(h * 3600 + mi * 60 + s);
}

/* Connect + TLS with CA-chain validation (HTTPS to arbitrary hosts). Unlike
 * tls_connect (pinned key), this trusts the bundled root store and checks the
 * server name + validity date. */
int tls_connect_ca(const u8 dst[4], u16 port, const char *sni)
{
    unsigned char seed[32];
    uint32_t days, secs;
    long t;

    if (tls_entropy_source() == TLS_ENT_NONE) {          /* fail closed - see tls_entropy.h */
        TLSTRACE("tls: refusing connect_ca - no usable entropy source");
        return TLS_ENOENTROPY;
    }
    if (net_tcp_connect(dst, port) != 0) return -1;
    t = 4000000;                                /* hard iteration ceiling (backstop) */
    { int ms = 0;
      while (net_tcp_state() != TCP_ESTABLISHED) {
        net_poll();
        { int st = net_tcp_state(); if (st == TCP_DONE || st == TCP_CLOSED) return -2; }
        uno_pc64_delay_ms(1);
        if (++ms > 3000) return -2;             /* ~3s deadline: SYN went unanswered */
        if (TLS_OUT_OF_BUDGET()) return -2;     /* the test's budget ran out first */
        if (--t <= 0) return -2;
      } }
    br_ssl_client_init_full(&g_sc, &g_xm, uno_tls_tas, uno_tls_tas_num);  /* trust the roots */
    tls_now(&days, &secs);
    br_x509_minimal_set_time(&g_xm, days, secs);            /* validity window */
    br_ssl_engine_set_buffer(&g_sc.eng, g_iobuf, sizeof g_iobuf, 0);
    if (!tls_entropy_get(seed, sizeof seed)) return TLS_ENOENTROPY;  /* source died */
    br_ssl_engine_inject_entropy(&g_sc.eng, seed, sizeof seed);
    memset(seed, 0, sizeof seed);
    if (br_ssl_client_reset(&g_sc, sni, 0) != 1) return -3;
    br_sslio_init(&g_io, &g_sc.eng, low_read, 0, low_write, 0);
    g_open = 1;
    return 0;
}

int tls_write(const void *data, int len)
{
    int r;
    if (!g_open) return -1;
    r = br_sslio_write_all(&g_io, data, (size_t)len);
    if (r < 0) { TLSTRACE("tls: write_all failed, engine err %d",
                          br_ssl_engine_last_error(&g_sc.eng)); return -1; }
    r = br_sslio_flush(&g_io);      /* drives the handshake + sends the record */
    if (r < 0) { TLSTRACE("tls: flush failed, engine err %d",
                          br_ssl_engine_last_error(&g_sc.eng)); return -1; }
    return len;
}

int tls_read(void *buf, int cap)
{
    int r;
    if (!g_open) return -1;
    r = br_sslio_read(&g_io, buf, (size_t)cap);
    return r;                        /* >0 = bytes, <0 = closed/error */
}

void tls_close(void)
{
    /* NOT br_sslio_close(): its loop runs until the engine reaches CLOSED,
     * but when the peer's close_notify was already received (shutdown_recv)
     * a failed low_write deliberately does NOT fail the engine (ssl_io.c
     * run_until, the RFC 5246 carve-out) - so against a torn-down TCP
     * connection it calls low_write forever. A Connection: close server
     * (data + close_notify + FIN in one flight) hit exactly that: 20 s of
     * spin until the watchdog reset the machine. This is the same polite
     * close, but it gives up the moment the transport does. */
    if (g_open) {
        int guard = 16;
        br_ssl_engine_close(&g_sc.eng);
        while (br_ssl_engine_current_state(&g_sc.eng) != BR_SSL_CLOSED && guard-- > 0) {
            unsigned st = br_ssl_engine_current_state(&g_sc.eng);
            if (st & BR_SSL_SENDREC) {          /* our close_notify */
                size_t len; unsigned char *buf = br_ssl_engine_sendrec_buf(&g_sc.eng, &len);
                int w = low_write(0, buf, len);
                if (w <= 0) break;              /* transport gone: peer won't wait (RFC 5246) */
                br_ssl_engine_sendrec_ack(&g_sc.eng, (size_t)w);
            } else if (st & BR_SSL_RECVAPP) {   /* discard late app data */
                size_t len;
                if (br_ssl_engine_recvapp_buf(&g_sc.eng, &len)) br_ssl_engine_recvapp_ack(&g_sc.eng, len);
            } else if (st & BR_SSL_RECVREC) {   /* wait for the peer's close_notify */
                size_t len; unsigned char *buf = br_ssl_engine_recvrec_buf(&g_sc.eng, &len);
                int r = low_read(0, buf, len);
                if (r <= 0) break;
                br_ssl_engine_recvrec_ack(&g_sc.eng, (size_t)r);
            } else break;
        }
        g_open = 0;
    }
    net_tcp_close();
}

int tls_last_error(void) { return br_ssl_engine_last_error(&g_sc.eng); }
unsigned tls_version(void) { return g_sc.eng.session.version; }
unsigned tls_cipher(void) { return g_sc.eng.session.cipher_suite; }
