#!/bin/sh
# Generate a fixed EC (P-256) server key + self-signed cert for the TLS test
# server, and emit the pinned public point as a C header the client compiles
# in. Only the PUBLIC point (pinned_key.h) is committed; server.key/.crt are
# local throwaways (gitignored). Re-run this after changing the key.
cd "$(dirname "$0")"
set -e
if [ ! -f server.key ]; then
    openssl ecparam -name prime256v1 -genkey -noout -out server.key
    openssl req -new -x509 -key server.key -out server.crt -days 3650 \
        -subj /CN=unodos-pc64
fi
python3 - <<'PY'
import subprocess
der = subprocess.check_output(["openssl","x509","-in","server.crt","-noout","-pubkey"])
d = subprocess.check_output(["openssl","pkey","-pubin","-outform","DER"], input=der)
pt = d[-65:]
assert pt[0] == 4 and len(pt) == 65, (pt[0], len(pt))
rows = []
for i in range(0, 65, 16):
    rows.append("    " + ",".join("0x%02x" % b for b in pt[i:i+16]) + ",")
body = "\n".join(rows).rstrip(",")
open("pinned_key.h", "w", newline="\n").write(
    "/* generated by tls_test/gen.sh - the pinned P-256 server public point.\n"
    "   Public key only (safe to commit); server.key/.crt stay local. */\n"
    "#ifndef PC64_PINNED_KEY_H\n#define PC64_PINNED_KEY_H\n"
    "static const unsigned char PINNED_EC_Q[65] = {\n" + body + "\n};\n#endif\n")
print("wrote tls_test/pinned_key.h")
PY
