/*  UnoSettings.cs - developer settings that outlive the flasher binary.
 *
 *  deploy-to-share.ps1 overwrites UnoDosFlasher.exe on the share after every
 *  pc64 build, and people run it straight from \\behemoth, so anything stored
 *  beside the exe - or embedded in it - is gone the next time you flash.
 *  These live in %APPDATA%\UnoDOS\flasher.ini instead, which no build touches.
 *
 *  Deliberately a hand-rolled key=value file: the flasher compiles with the
 *  in-box csc against .NET Framework, and a JSON serializer would drag in a
 *  reference the build does not otherwise need.  Unknown keys are preserved on
 *  save, so an older flasher cannot silently drop a newer one's settings.
 */
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

class UnoSettings
{
    public const int VERSION = 1;

    // DevMode now means "flash the DEBUG build + run the selected tests".
    // OFF (the default) flashes the clean PRODUCTION build.
    public bool   DevMode;
    // --- test selection (only meaningful in DevMode) ---
    public bool   TestSpec;           // conformance suite (SPECTEST) -> spec
    public bool   TestWifi   = true;  // WiFi network test
    public bool   TestEth    = true;  // Ethernet network test (auto-detects adapter)
    public bool   TestMtrr;           // MTRR write-combining experiment -> mtrr-wc
    public int    StressPasses = 3;   // stress driver passes (0 = no stress run)
    public bool   AutoShutoff = true; // power off when the run finishes
    // --- developer extras (kit / zip copy) ---
    public bool   KitEnabled = true;  // copy the testkit (carries wifi.txt creds)
    public string KitPath   = @"\\behemoth\unreplicated\unodos\pc64\testkit";
    public bool   ZipEnabled;
    public string ZipPath   = "";
    public string ZipDest   = "";     // subfolder on the disk, blank = root
    public string Label     = "UNODOS";
    public bool   AutoUpdate = true;  // check the share + self-update at startup
    public string UpdatePath = "";    // ini-only override of the update share dir

    // Which embedded ESP resource to flash.
    public string EspResource { get { return DevMode ? "unodos_esp_debug" : "unodos_esp_prod"; } }

    /* The STRESS.CFG the debug build reads, generated from the test toggles.
     * Written only in DevMode; overrides the debug ESP's shipped default.
     * Returns null when nothing should be armed (all tests off + no stress). */
    public string StressCfg()
    {
        if (!DevMode) return null;
        var sb = new StringBuilder();
        sb.Append("# UnoDOS test config - generated by the flasher's Developer options\r\n");
        int passes = StressPasses < 0 ? 0 : StressPasses;
        sb.Append("passes=" + passes + "\r\n");
        if (!AutoShutoff) sb.Append("noshutdown\r\n");
        if (TestSpec)     sb.Append("spec\r\n");
        if (TestMtrr)     sb.Append("mtrr-wc\r\n");
        // network: neither -> nonet; wifi-only -> force wifi even with an
        // adapter; eth-only -> no wifi fallback; both -> auto-detect.
        if (!TestWifi && !TestEth) sb.Append("nonet\r\n");
        else if (TestWifi && !TestEth) sb.Append("net-force-wifi\r\n");
        else if (TestEth && !TestWifi) sb.Append("net-eth-only\r\n");
        return sb.ToString();
    }

    readonly Dictionary<string, string> extra = new Dictionary<string, string>();

    public static string Dir
    {
        get {
            return Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "UnoDOS");
        }
    }
    public static string FilePath { get { return Path.Combine(Dir, "flasher.ini"); } }

    public static UnoSettings Load()
    {
        var s = new UnoSettings();
        try {
            if (!File.Exists(FilePath)) return s;
            foreach (var raw in File.ReadAllLines(FilePath)) {
                string line = raw.Trim();
                if (line.Length == 0 || line[0] == '#' || line[0] == ';') continue;
                int eq = line.IndexOf('=');
                if (eq <= 0) continue;
                string k = line.Substring(0, eq).Trim(), v = line.Substring(eq + 1).Trim();
                switch (k.ToLowerInvariant()) {
                    case "version":     break;                       // informational
                    case "devmode":     s.DevMode    = Truthy(v); break;
                    case "testspec":    s.TestSpec   = Truthy(v); break;
                    case "testwifi":    s.TestWifi   = Truthy(v); break;
                    case "testeth":     s.TestEth    = Truthy(v); break;
                    case "testmtrr":    s.TestMtrr   = Truthy(v); break;
                    case "stresspasses": { int p; if (int.TryParse(v, out p)) s.StressPasses = p; break; }
                    case "autoshutoff": s.AutoShutoff = Truthy(v); break;
                    case "kitenabled":  s.KitEnabled = Truthy(v); break;
                    case "kitpath":     s.KitPath    = v;         break;
                    case "zipenabled":  s.ZipEnabled = Truthy(v); break;
                    case "zippath":     s.ZipPath    = v;         break;
                    case "zipdest":     s.ZipDest    = v;         break;
                    case "label":       if (v.Length > 0) s.Label = v; break;
                    case "autoupdate":  s.AutoUpdate = Truthy(v); break;
                    case "updatepath":  s.UpdatePath = v;         break;
                    default:            s.extra[k] = v;           break;
                }
            }
        } catch { /* a corrupt settings file must never stop someone flashing */ }
        return s;
    }

    public void Save()
    {
        try {
            Directory.CreateDirectory(Dir);
            var sb = new StringBuilder();
            sb.AppendLine("# UnoDOS flasher settings - kept out of the exe so it survives an update.");
            sb.AppendLine("version="    + VERSION);
            sb.AppendLine("devmode="    + (DevMode ? "1" : "0"));
            sb.AppendLine("testspec="   + (TestSpec ? "1" : "0"));
            sb.AppendLine("testwifi="   + (TestWifi ? "1" : "0"));
            sb.AppendLine("testeth="    + (TestEth ? "1" : "0"));
            sb.AppendLine("testmtrr="   + (TestMtrr ? "1" : "0"));
            sb.AppendLine("stresspasses=" + StressPasses);
            sb.AppendLine("autoshutoff=" + (AutoShutoff ? "1" : "0"));
            sb.AppendLine("kitenabled=" + (KitEnabled ? "1" : "0"));
            sb.AppendLine("kitpath="    + KitPath);
            sb.AppendLine("zipenabled=" + (ZipEnabled ? "1" : "0"));
            sb.AppendLine("zippath="    + ZipPath);
            sb.AppendLine("zipdest="    + ZipDest);
            sb.AppendLine("label="      + Label);
            sb.AppendLine("autoupdate=" + (AutoUpdate ? "1" : "0"));
            sb.AppendLine("updatepath=" + UpdatePath);
            foreach (var kv in extra) sb.AppendLine(kv.Key + "=" + kv.Value);
            File.WriteAllText(FilePath, sb.ToString(), Encoding.UTF8);
        } catch { }
    }

    static bool Truthy(string v)
    {
        v = v.ToLowerInvariant();
        return v == "1" || v == "true" || v == "yes" || v == "on";
    }

    /* What the settings actually add to a flash, in order.  Returns the reason a
     * source was skipped rather than throwing: a missing kit folder should be a
     * visible warning, not a failed install. */
    public List<IPayloadSource> ExtraPayloads(out List<string> warnings)
    {
        var list = new List<IPayloadSource>();
        warnings = new List<string>();
        if (!DevMode) return list;

        // the generated STRESS.CFG (arms the debug build's tests) - first, so
        // it's applied and shown; it overrides the debug ESP's shipped default
        string cfg = StressCfg();
        if (cfg != null)
            list.Add(new InlineFilePayload("STRESS.CFG", cfg, "test config (STRESS.CFG)"));

        if (KitEnabled) {
            if (Directory.Exists(KitPath)) list.Add(new FolderPayload(KitPath, ""));
            else warnings.Add("Test kit folder not found: " + KitPath);
        }
        if (ZipEnabled) {
            if (File.Exists(ZipPath)) list.Add(new ZipPayload(ZipPath, ZipDest));
            else warnings.Add("Zip not found: " + ZipPath);
        }
        return list;
    }
}
