#!/usr/bin/env python3
"""Generate vic20/vic_data.inc from the shared UnoDOS assets (Commodore VIC-20).

The VIC (6560/6561) is a CHARACTER-cell display: a 22x23 screen matrix of 8-bit
char codes, each cell coloured by a colour-RAM nibble (8 fg colours) over the
global background colour. Characters are 8x8 **1bpp** = 8 bytes. We bake a custom
256-char set: a font, an INVERTED font (complement bitmaps -> a white bar with
the desktop colour showing the glyph, for title bars), 8x8 mini-icons (one per
app, the x86 donor downscaled + thresholded), and solid blocks for Dostris.
The kernel copies this set into RAM at $3000 (the VIC char base) at boot.

Usage: python vic20/mkdata.py    (from the repo root)
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(HERE, "vic_data.inc")

font = []
for line in open(os.path.join(ROOT, "kernel", "font8x8.asm"), encoding="latin-1"):
    m = re.match(r"\s*db\s+0b([01]{8})", line)
    if m:
        font.append(int(m.group(1), 2))
assert len(font) == 95 * 8

chars = []   # each = 8 bytes (1bpp, bit7 leftmost)
chars.append([0]*8)                                   # 0 blank
for g in range(95):
    chars.append(list(font[g*8:(g+1)*8]))             # 1..95 font
for g in range(95):
    chars.append([b ^ 0xFF for b in font[g*8:(g+1)*8]])  # 96..190 inverted
chars.append([0xFF]*8)                                # 191 solid block

# icons -> 8x8 1bpp mini (donor index != 0 -> pixel set)
def icon_mini(path):
    data = open(path, "rb").read()
    assert data[0] == 0xEB and data[2:4] == b"UI", f"{path}: no UI header"
    chunky = data[0x10:0x50]
    pix = [[((chunky[r*4 + px//4] >> ((3-(px%4))*2)) & 3) for px in range(16)] for r in range(16)]
    out = []
    for y in range(8):
        b = 0
        for x in range(8):
            if pix[2*y][2*x] != 0:
                b |= 0x80 >> x
        out.append(b)
    return out
ICONS = ["build/sysinfo.bin","build/clock.bin","build/notepad.bin","build/music.bin",
         "build/browser.bin","build/settings.bin","build/tracker.bin","build/tetris.bin",
         "build/outlast.bin","build/pacman.bin"]
PAINT = ["0000000000033000","0000000000333000","0000000003330000","0000000033300000",
         "0000000333000000","0000011330000000","0000111100000000","0000111000000000",
         "0001110000000000","0001100000000000","0022000022220000","0222200222222000",
         "2222222222222200","2222222222222220","0222222222222200","0002222222220000"]
MINI_BASE = len(chars)
for bf in ICONS:
    p = os.path.join(ROOT, bf)
    if not os.path.exists(p):
        sys.exit(f"missing {bf} - run 'make floppy144' first")
    chars.append(icon_mini(p))
# paint mini
pm = []
for y in range(8):
    b = 0
    for x in range(8):
        if int(PAINT[2*y][2*x]) != 0:
            b |= 0x80 >> x
    pm.append(b)
chars.append(pm)
NICONS = len(ICONS) + 1
assert len(chars) <= 256, f"{len(chars)} chars > 256"

# Dostris piece tables
PIECES = {"I":["....","####","....","...."],"O":[".##.",".##.","....","...."],
          "T":[".#..","###.","....","...."],"S":[".##.","##..","....","...."],
          "Z":["##..",".##.","....","...."],"J":["#...","###.","....","...."],
          "L":["..#.","###.","....","...."]}
def rot90(g): return ["".join(g[3-c][r] for c in range(4)) for r in range(4)]
def mask(g):
    m=0
    for r in range(4):
        for c in range(4):
            if g[r][c]=="#": m|=1<<(15-(r*4+c))
    return m
order=["I","O","T","S","Z","J","L"]
piece_masks=[]
for p in order:
    g=PIECES[p]
    for _ in range(4):
        piece_masks.append(mask(g)); g=rot90(g)
T_BLOCK = 191
# piece colours = VIC colour-RAM nibbles: cyan3 yellow7 purple4 green5 red2 white1 orange8
piece_cols=[3,7,4,5,2,1,8]

# Music (VIC tone osc): value = 255 - 65536/(16*freq*... ) approximated to an audible scale.
NOTE_HZ={"C4":262,"D4":294,"E4":330,"F4":349,"G4":392,"A4":440,"B4":494,"C5":523,"D5":587}
Q,H=26,52
TUNE=[("E4",Q),("E4",Q),("F4",Q),("G4",Q),("G4",Q),("F4",Q),("E4",Q),("D4",Q),("C4",Q),("C4",Q),
      ("D4",Q),("E4",Q),("E4",H),("D4",Q),("D4",H),("E4",Q),("E4",Q),("F4",Q),("G4",Q),("G4",Q),
      ("F4",Q),("E4",Q),("D4",Q),("C4",Q),("C4",Q),("D4",Q),("E4",Q),("D4",H),("C4",Q),("C4",H)]
# VIC osc: freq ~ Phi2 / (16*(256-value)); solve value = 256 - 4329/note  (alto osc $900B)
music_song=[(max(128,min(254, round(256 - 4329.0/NOTE_HZ[n]))), d) for n,d in TUNE]

# VIC 16-colour palette (RGB) for the harness
PALETTE=[(0,0,0),(255,255,255),(120,40,40),(80,160,170),(120,60,150),(80,150,75),
         (50,40,135),(180,190,110),(120,80,30),(180,130,80),(180,110,110),(135,200,195),
         (170,120,210),(150,210,140),(115,105,200),(220,225,170)]

with open(OUT,"w",newline="\n") as f:
    f.write("; AUTO-GENERATED by vic20/mkdata.py - do not edit\n")
    f.write(f"NCHARS    EQU {len(chars)}\n")
    f.write(f"T_FONT    EQU 1\nT_FONTINV EQU 96\nT_BLOCK   EQU 191\n")
    f.write(f"T_MINI    EQU {MINI_BASE}\nNICONS    EQU {NICONS}\n")
    f.write(f"NTHEMES   EQU 4\nMUSIC_COUNT EQU {len(music_song)}\n")
    f.write("charset_data:\n")
    for c in chars:
        f.write("    dc.b " + ",".join("$%02X"%b for b in c) + "\n")
    f.write("piece_masks:\n")
    for i,p in enumerate(order):
        f.write("    dc.w " + ",".join("$%04X"%piece_masks[i*4+r] for r in range(4)) + "\n")
    f.write("piece_cols:\n    dc.b " + ",".join(str(c) for c in piece_cols) + "\n")
    f.write("row_off:\n    dc.w " + ",".join(str(r*22) for r in range(24)) + "\n")
    f.write("music_song:\n")
    for v,fr in music_song:
        f.write(f"    dc.b ${v:02X},{fr}\n")
print(f"wrote {OUT}: {len(chars)} chars, {NICONS} icons, {len(music_song)} notes")
