#!/usr/bin/env python3
"""unodoc host gate (phase 1: the CFB container).

Runs without booting the OS, over the same sources the .UNO module compiles
freestanding.  Five stages:

  1. build      cfbtest with build.sh's sanitizer set PLUS AddressSanitizer.
                (docs/OFFICE97-PLAN.md §9, the UnoAmp EQ lesson: a harness
                without the OS's flags tests different code.  Every failure
                is fatal - -fno-sanitize-recover=all.)
  2. selftest   in-memory round-trip, directory ordering, the DIFAT overflow
                path, random access, and a battery of corrupt containers.
  3. corpus     open every file in corpus/ (generated by mkcorpus.py from
                LibreOffice headless) and assert the streams each format is
                required to carry are present.
  4. rebuild    read each corpus file, rebuild the container through OUR
                writer, and assert (a) the tree and every stream byte survive
                and (b) LibreOffice still opens the rebuilt file and converts
                it to the same content as the original.  That second half is
                the oracle: it is a third party agreeing our container is
                well formed.
  5. fuzz       thousands of mutations of each corpus file through the
                reader.  Requirement: never crash, never hang.

Usage: python3 run_tests.py [filter-substring] [--force-corpus]
Exit code 0 = green.
"""
import os, re, shutil, subprocess, sys, time

HERE   = os.path.dirname(os.path.abspath(__file__))
UD     = os.path.dirname(HERE)
GEN    = os.path.join(HERE, "gen")
CORPUS = os.path.join(HERE, "corpus")
BIN    = os.path.join(GEN, "cfbtest")
XBIN   = os.path.join(GEN, "xlstest")
DBIN   = os.path.join(GEN, "doctest")
PBIN   = os.path.join(GEN, "ppttest")
PROFILE = os.path.join(GEN, "loprofile")

# build.sh's first-party sanitizer set, verbatim, plus ASan for the host.
SAN = ["-fsanitize=address,undefined",
       "-fsanitize=signed-integer-overflow,bounds,shift,"
       "integer-divide-by-zero,null",
       "-fno-sanitize-recover=all"]

SRCS  = ["unodoc.c", "ud_cfb.c", "ud_zip.c", "ud_xml.c",
         "../unomedia/unomedia.c", "../unomedia/um_inflate.c"]
# The OOXML reader is built into the SAME test binary: one dump(), one
# fixture, two parsers. um_inflate comes from unomedia (its header calls
# itself "a general facility future formats will want" - this is that
# format), so the media library joins the link line here.
XSRCS = ["unodoc.c", "ud_cfb.c", "ud_xls.c", "ud_ptg.c", "ud_ptgc.c", "ud_xlsw.c",
         "ud_zip.c", "ud_xml.c", "ud_xlsx.c", "ud_ooxz.c", "ud_xlsxw.c",
         "../unomedia/unomedia.c", "../unomedia/um_inflate.c"]
DSRCS = ["unodoc.c", "ud_cfb.c", "ud_doc.c", "ud_docw.c",
         "ud_zip.c", "ud_xml.c", "ud_docx.c", "ud_ooxz.c", "ud_docxw.c",
         "../unomedia/unomedia.c", "../unomedia/um_inflate.c"]
PSRCS = ["unodoc.c", "ud_cfb.c", "ud_ppt.c", "ud_escher.c", "ud_pptw.c",
         "ud_zip.c", "ud_xml.c", "ud_pptx.c", "ud_ooxz.c", "ud_pptxw.c",
         "../unomedia/unomedia.c", "../unomedia/um_inflate.c"]

# what each format is required to carry, as unodoc paths
REQUIRED = {
    ".doc": [["WordDocument"], ["\x05SummaryInformation"], ["0Table", "1Table"]],
    ".xls": [["Workbook", "Book"], ["\x05SummaryInformation"]],
    ".ppt": [["PowerPoint Document"], ["Current User"]],
}

# The same assertion for the ZIP container: the parts each OOXML format is
# required to carry. [Content_Types].xml is in all three - it is what makes a
# zip an OPC package rather than a zip - so it is listed per format rather
# than assumed once.
REQUIRED_ZIP = {
    ".docx": [["[Content_Types].xml"], ["word/document.xml"],
              ["word/_rels/document.xml.rels"]],
    ".xlsx": [["[Content_Types].xml"], ["xl/workbook.xml"],
              ["xl/_rels/workbook.xml.rels"]],
    ".pptx": [["[Content_Types].xml"], ["ppt/presentation.xml"],
              ["ppt/_rels/presentation.xml.rels"]],
}

fails = []
def fail(msg):
    fails.append(msg)
    print("  FAIL %s" % msg)

def run(args, timeout=300):
    return subprocess.run(args, capture_output=True, text=True,
                          timeout=timeout, errors="replace")

# ---- 1. build ---------------------------------------------------------------
def build():
    os.makedirs(GEN, exist_ok=True)
    cmd = (["gcc", "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Werror",
            "-I", UD] + SAN + ["-o", BIN] +
           [os.path.join(UD, s) for s in SRCS] +
           [os.path.join(HERE, "cfbtest.c")])
    def gcc(out, srcs, main):
        c = (["gcc", "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Werror",
              "-I", UD] + SAN + ["-o", out] +
             [os.path.join(UD, x) for x in srcs] + [os.path.join(HERE, main)])
        rr = run(c)
        if rr.returncode:
            print(rr.stdout + rr.stderr)
            raise SystemExit("build failed: " + out)
    r = run(cmd)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("build failed")
    gcc(XBIN, XSRCS, "xlstest.c")
    gcc(DBIN, DSRCS, "doctest.c")
    gcc(PBIN, PSRCS, "ppttest.c")
    print("build: ok")

# ---- 2. selftest ------------------------------------------------------------
SELFTESTS = [
    (lambda: [BIN, "selftest"],  "cfbtest selftest"),
    (lambda: [XBIN, "selftest"], "xlstest selftest"),   # the SST encoding switch
    (lambda: [XBIN, "wtest"],    "xlstest wtest"),      # the writer round-trip
    # ...and the SAME model round-tripped through the OOXML serialiser, judged
    # by the SAME assertions.
    (lambda: [XBIN, "wxtest"],   "xlstest wxtest"),
    (lambda: [DBIN, "selftest"], "doctest selftest"),   # the multi-piece walk
    (lambda: [DBIN, "wtest", os.path.join(GEN, "written.doc")], "doctest wtest"),
    (lambda: [DBIN, "wxtest", os.path.join(GEN, "written.docx")], "doctest wxtest"),
    (lambda: [PBIN, "wtest"],    "ppttest wtest"),      # the .ppt writer round-trip
    (lambda: [PBIN, "wxtest"],   "ppttest wxtest"),
]

# What LibreOffice must find in the .doc WE wrote.  Our own reader agreeing
# with our own writer proves only that they share a misunderstanding.
WRITTEN_DOC_MUST_HAVE = [
    ("Plain first paragraph.",        "the first paragraph"),
    ("This one is bold.",             "a bold paragraph's text"),
    ("This one is italic and centred.", "an italic centred paragraph"),
    ("Back to plain, right aligned.", "a right-aligned paragraph"),
    ('fo:font-weight="bold"',         "the bold run"),
    ('fo:font-style="italic"',        "the italic run"),
    ('fo:text-align="center"',        "centred alignment"),
    ('fo:text-align="end"',           "right alignment"),
]

def written_doc(have_lo):
    # Both forms of the same document, judged the same way. The .docx half is
    # the one that matters most here: OUR reader reading OUR writer proves
    # nothing about a file Word will ever see.
    for name, tmp in (("written.doc", "lo_wdoc"), ("written.docx", "lo_wdocx")):
        out = os.path.join(GEN, name)
        if not os.path.exists(out):
            fail("no %s was written" % name)
            continue
        print("  %-13s %d bytes" % (name, os.path.getsize(out)))
        if not have_lo:
            print("  (no soffice: the independent half of this stage is SKIPPED)")
            return
        flat = soffice_flat(out, os.path.join(GEN, tmp))
        if flat is None:
            fail("LibreOffice REFUSED the %s we wrote" % name)
            continue
        missing = [why for s, why in WRITTEN_DOC_MUST_HAVE if s not in flat]
        if missing:
            fail("LibreOffice opened our %s but did not find: %s"
                 % (name, ", ".join(missing)))
        else:
            print("  %-13s LibreOffice reads back all %d checked features"
                  % (name, len(WRITTEN_DOC_MUST_HAVE)))

def selftest():
    for argv, what in SELFTESTS:
        r = run(argv(), timeout=900)
        out = r.stdout.strip()
        print("  " + (out.replace("\n", "\n  ") if out else "(no output)"))
        if r.returncode:
            fail("%s returned %d" % (what, r.returncode))
            if r.stderr.strip():
                print(r.stderr[:4000])

# ---- corpus helpers ---------------------------------------------------------
def corpus_files():
    if not os.path.isdir(CORPUS):
        return []
    return sorted(os.path.join(CORPUS, f) for f in os.listdir(CORPUS)
                  if os.path.splitext(f)[1] in REQUIRED
                  or os.path.splitext(f)[1] in REQUIRED_ZIP)

def ensure_corpus(force=False):
    args = [sys.executable, os.path.join(HERE, "mkcorpus.py")]
    if force:
        args.append("--force")
    r = run(args, timeout=1800)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("corpus generation failed")
    print(r.stdout.strip().splitlines()[-1])

# ---- 3. corpus read ---------------------------------------------------------
def read_corpus(files):
    for path in files:
        ext = os.path.splitext(path)[1]
        if ext in REQUIRED_ZIP:
            read_zip_corpus(path, ext)
            continue
        r = run([BIN, "ls", path])
        if r.returncode or "OPEN-FAILED" in r.stdout:
            fail("%s: %s" % (os.path.basename(path),
                             r.stdout.strip()[:200] or "ls returned %d" % r.returncode))
            continue
        names = set()
        for line in r.stdout.splitlines():
            m = re.match(r"\s*[SD] (.*?)(?: \d+ [0-9a-f]{16})?$", line)
            if m:
                names.add(m.group(1))
        missing = [alts for alts in REQUIRED[ext]
                   if not any(a in names for a in alts)]
        entries = len([l for l in r.stdout.splitlines() if l.strip()]) - 1
        if missing:
            fail("%s: missing %s (saw %s)"
                 % (os.path.basename(path),
                    " / ".join("|".join(a) for a in missing),
                    ", ".join(sorted(repr(n) for n in names))))
        else:
            print("  %-12s %7d bytes, %2d entries"
                  % (os.path.basename(path), os.path.getsize(path), entries))

def read_zip_corpus(path, ext):
    """The ZIP container gate: every part is listed AND inflated.

    Inflating all of them is the point - it is the only place the gate runs
    unomedia's deflate over real third-party data, and a part that comes out a
    different length than the central directory promised is caught here rather
    than as a reader that mysteriously sees half a document."""
    base = os.path.basename(path)
    r = run([BIN, "zls", path])
    if r.returncode or "OPEN-FAILED" in r.stdout:
        fail("%s: %s" % (base, (r.stdout + r.stderr).strip()[:200]))
        return
    names, bad = set(), []
    for line in r.stdout.splitlines():
        f = line.split(" ")
        if len(f) >= 4 and f[0] == "P":
            names.add(f[1])
            if f[3] != "ok":
                bad.append((f[1], " ".join(f[3:])))
    if bad:
        fail("%s: %d part(s) failed to inflate; first: %s" % (base, len(bad), bad[0]))
        return
    missing = [alts for alts in REQUIRED_ZIP[ext]
               if not any(a in names for a in alts)]
    if missing:
        fail("%s: missing %s (saw %s)"
             % (base, " / ".join("|".join(a) for a in missing),
                ", ".join(sorted(names))))
    else:
        print("  %-14s %7d bytes, %2d parts, all inflate"
              % (base, os.path.getsize(path), len(names)))

# ---- 4. rebuild + the LibreOffice oracle ------------------------------------
# CFB only. The rebuild stage reads a container through OUR writer and asks
# LibreOffice to agree; there is no OOXML WRITER in this phase, so an .xlsx has
# nothing to rebuild and is not silently passed through a stage that would
# report success without doing anything.
FLAT = {".doc": "fodt", ".xls": "fods", ".ppt": "fodp"}

# The flat-XML form for the LibreOffice oracle, which DOES apply to both
# containers: it converts whatever it is given. Kept separate from FLAT
# because FLAT also decides which files the rebuild stage handles, and that
# one is CFB-only.
FLAT_ANY = dict(FLAT)
FLAT_ANY.update({".docx": "fodt", ".xlsx": "fods", ".pptx": "fodp"})

# Volatile output, nothing to do with the container:
#   office:meta   carries the conversion timestamp
#   Rsid/RsidRoot are Word revision-save ids, which LibreOffice generates
#                 afresh on every load - two conversions of the SAME file
#                 disagree.  Verified 2026-08-01, hence the determinism
#                 self-check below: we never strip a field on faith.
VOLATILE = [
    re.compile(r"<office:meta>.*?</office:meta>", re.S),
    re.compile(r'<config:config-item config:name="Rsid[A-Za-z]*"'
               r'[^>]*>[^<]*</config:config-item>'),
]

def normalize(text):
    for rx in VOLATILE:
        text = rx.sub("", text)
    return text

def first_diff(a, b, ctx=70):
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    lo = max(0, i - ctx)
    return "at %d:\n    A: %r\n    B: %r" % (i, a[lo:i + ctx], b[lo:i + ctx])

def soffice_flat(path, outdir):
    """Convert `path` to flat XML and return its content, normalized."""
    env = dict(os.environ)
    env["HOME"] = PROFILE
    env["SAL_USE_VCLPLUGIN"] = "svp"
    os.makedirs(PROFILE, exist_ok=True)
    os.makedirs(outdir, exist_ok=True)
    fmt = FLAT_ANY[os.path.splitext(path)[1]]
    out = os.path.join(outdir, os.path.splitext(os.path.basename(path))[0]
                       + "." + fmt)
    # Remove the target FIRST.  Without this, a conversion that fails or times
    # out leaves the PREVIOUS run's file sitting there and we compare against
    # stale content - which can invent a failure (seen once on small.ppt) just
    # as easily as it can hide a real one.
    if os.path.exists(out):
        os.remove(out)
    subprocess.run(["soffice", "--headless", "--norestore", "--convert-to",
                    fmt, "--outdir", outdir, path],
                   capture_output=True, text=True, env=env, timeout=600)
    if not os.path.exists(out):
        return None
    with open(out, encoding="utf-8", errors="replace") as f:
        return normalize(f.read())

def rebuild_corpus(files, oracle=True):
    outdir = os.path.join(GEN, "rebuilt")
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)
    for path in files:
        base = os.path.basename(path)
        # CFB ONLY. This stage reads a container through OUR writer and asks
        # LibreOffice to agree it is still the same document; there is no OOXML
        # WRITER in this phase, so an .xlsx has nothing to rebuild. Skipping it
        # explicitly is the point - running it would fail on a signature check
        # and report a missing feature as a broken one.
        if os.path.splitext(path)[1] not in FLAT:
            continue
        # (a) our own gate: the tree and every stream byte survive a rebuild
        r = run([BIN, "rt", path])
        if r.returncode:
            fail("%s: %s" % (base, r.stdout.strip()[:400]))
            continue
        out = os.path.join(outdir, base)
        r = run([BIN, "rebuild", path, out])
        if r.returncode:
            fail("%s: rebuild: %s" % (base, r.stdout.strip()[:200]))
            continue
        print("  %-12s rebuild %s" % (base, r.stdout.strip()))
        if not oracle:
            continue
        # (b) the oracle: LibreOffice reads the rebuilt container and gets
        #     the same document back.  The original is converted TWICE first,
        #     so the comparison has to earn the right to be meaningful: if
        #     two conversions of the same bytes already disagree, the
        #     normalizer is missing a volatile field and we say so instead of
        #     reporting a pass we did not establish.
        a1 = soffice_flat(path, os.path.join(GEN, "lo_orig1"))
        a2 = soffice_flat(path, os.path.join(GEN, "lo_orig2"))
        b = soffice_flat(out, os.path.join(GEN, "lo_new"))
        if a1 is None or a2 is None:
            fail("%s: LibreOffice could not convert the ORIGINAL" % base)
        elif a1 != a2:
            fail("%s: oracle is not deterministic - normalize() misses a "
                 "volatile field, so this file proves nothing. Diff %s"
                 % (base, first_diff(a1, a2)))
        elif b is None:
            fail("%s: LibreOffice REFUSED the rebuilt container" % base)
        elif a1 != b:
            fail("%s: LibreOffice read the rebuilt file differently "
                 "(%d vs %d bytes of flat XML). Diff %s"
                 % (base, len(a1), len(b), first_diff(a1, b)))
        else:
            print("  %-12s oracle  LibreOffice agrees (%d bytes flat XML)"
                  % (base, len(a1)))

# ---- 4b. workbook: values against the fixture -------------------------------
def parse_cells(text):
    out = {}
    for line in text.splitlines():
        f = line.split("	")
        if len(f) >= 6 and f[0] == "cell":
            out[(int(f[1]), int(f[2]), int(f[3]))] = (f[4], f[5])
    return out

def parse_formulas(text):
    out = {}
    for line in text.splitlines():
        f = line.split("\t")
        if len(f) >= 5 and f[0] == "formula":
            out[(int(f[1]), int(f[2]), int(f[3]))] = f[4]
    return out

def same(kind, want, got):
    if want == got:
        return True
    if kind == "NUM":
        try:
            return float(want) == float(got)
        except ValueError:
            return False
    return False

def dump_cp1252(path):
    """xlstest emits CP-1252 bytes (unodoc's internal text encoding), so the
    runner decodes them as CP-1252 rather than letting the default UTF-8 turn
    every accented character into a replacement char and a false failure."""
    r = subprocess.run([XBIN, "dump", path], capture_output=True, timeout=600)
    return (r.returncode,
            r.stdout.decode("cp1252", errors="strict"),
            r.stderr.decode("utf-8", errors="replace"))

# The one place the two formats legitimately disagree, and it is a difference
# in the FILES rather than in the readers: LibreOffice stores the boolean
# constant as the BIFF token PtgFunc(TRUE) in .xls, which decompiles to "TRUE",
# and as the literal text "TRUE()" in .xlsx. Both readers report exactly what
# their file says. Checked by hand against the part before being allowed here.
XLSX_FORMULA_ALIAS = {"=TRUE": "=TRUE()", "=FALSE": "=FALSE()"}

def workbooks(files):
    for path in files:
        if not (path.endswith(".xls") or path.endswith(".xlsx")):
            continue
        base = os.path.basename(path)
        xlsx = path.endswith(".xlsx")
        fixpath = path + ".expect.tsv"
        try:
            rc, out, err = dump_cp1252(path)
        except UnicodeDecodeError as e:
            fail("%s: dump is not valid CP-1252 (%s)" % (base, e))
            continue
        if rc or out.startswith("ERR:"):
            fail("%s: %s" % (base, (out + err).strip()[:300]))
            continue
        if "!! lookup disagrees" in out:
            fail("%s: random access disagrees with iteration" % base)
        got = parse_cells(out)
        if not os.path.exists(fixpath):
            fail("%s: no fixture" % base)
            continue
        with open(fixpath, encoding="utf-8") as f:
            fixtext = f.read()
        want = parse_cells(fixtext)
        wantf = parse_formulas(fixtext)
        bad, missing = [], []
        for key, (kind, val) in want.items():
            if key not in got:
                missing.append(key)
            elif got[key][0] != kind or not same(kind, val, got[key][1]):
                bad.append((key, (kind, val), got[key]))
        # Extra cells are fine only when they carry no value (blank records
        # that exist just to hold a format, e.g. the covered half of a merge)
        # or when they are formula cells, whose value is whatever the engine
        # computed on save and so is asserted by the `formula` line instead.
        extra = [k for k, v in got.items()
                 if k not in want and k not in wantf and v[0] != "EMPTY"]
        if missing or bad or extra:
            fail("%s: %d missing, %d wrong, %d unexpected; first wrong: %s"
                 % (base, len(missing), len(bad), len(extra),
                    bad[0] if bad else (missing[0] if missing else extra[0])))
        else:
            print("  %-12s %5d cells match the fixture" % (base, len(want)))
        # formulas: the fixture states them in Excel A1 syntax while the
        # source document states them in ODF syntax, so a match means the
        # decompiler rebuilt the expression rather than echoing anything
        if wantf:
            gotf = parse_formulas(out)
            wrong = [(k, wantf[k], gotf.get(k, "<absent>"))
                     for k in wantf
                     if gotf.get(k) != wantf[k]
                     and not (xlsx and gotf.get(k) == XLSX_FORMULA_ALIAS.get(wantf[k]))]
            if wrong:
                fail("%s: %d of %d formulas differ; first: %s"
                     % (base, len(wrong), len(wantf), wrong[0]))
            else:
                print("  %-12s %5d formulas decompile exactly"
                      % (base, len(wantf)))
        if base in ("cells.xls", "cells.xlsx"):
            # the FORMAT/XF path: the two date cells must resolve to a real
            # number-format code, not General
            fmts = [l.split("	")[-1] for l in out.splitlines()
                    if l.startswith("cell	0	6	")]
            if not fmts or any(f == "fmt=General" for f in fmts):
                fail("cells.xls: date cells lost their number format (%s)" % fmts)
            else:
                print("  %-12s date format resolved: %s"
                      % (base, fmts[0].replace("fmt=", "")))

# ---- 4c. the workbook WE write, judged by LibreOffice -----------------------
# xlstest wtest already proves our writer and our reader agree, but a file we
# both write and read could be consistently wrong. This is the independent
# half: LibreOffice opens it and has to find the same content.
WRITTEN_MUST_HAVE = [
    ('table:name="Alpha"',                  "the first sheet"),
    ('table:name="Beta"',                   "the second sheet"),
    ('office:value="1.5"',                  "a plain number"),
    ('office:value="12345678901234"',       "a number past 32 bits"),
    ('office:value="42"',                   "a rewritten cell"),
    ("café naïve Über",      "CP-1252 accents"),
    ("euro € sign",                    "a string that had to go out WIDE"),
    ("#DIV/0!",                             "an error value"),
    ("#N/A",                                "another error value"),
    ('table:number-columns-spanned="3"',    "the merged range"),
    ("number:date-style",                   "a built-in number format"),
    ("kg",                                  "a custom number format"),
    # Formulas WE compiled, as LibreOffice re-renders them in ODF syntax.
    # This is what actually validates the operand classes: a reference in the
    # wrong class still writes, but comes back meaning something else.
    ("of:=1+2*3",                           "operator precedence"),
    ("of:=(1+2)*3",                         "the author's own parentheses"),
    ("of:=2^3^2",                           "left-associative ^"),
    ("of:=-[.B1]",                          "unary minus on a reference"),
    ("of:=50%",                             "postfix percent"),
    ("of:=[.$A$1]",                         "an absolute reference"),
    ("of:=SUM([.A1:.C3])",                  "an area as a function argument"),
    ("of:=IF([.A1]&gt;0;&quot;y&quot;;&quot;n&quot;)",
                                            "mixed argument types"),
    ("of:=SUM(MAX(1;2);MIN(3;4))",          "nested calls"),
    ("of:=[$Alpha.A1]",                     "a 3-D reference"),
    ("of:=SUM([$Alpha.A1:.B2])",            "a 3-D area"),
    ("of:=&quot;a&quot;&quot;b&quot;",       "a doubled quote in a literal"),
]

def written(have_lo):
    for name, argv, tmp in (
            ("written.xls",  lambda o: [XBIN, "wfile", o],           "lo_written"),
            ("written.xlsx", lambda o: [XBIN, "wfile", o, "xlsx"],   "lo_writtenx")):
        out = os.path.join(GEN, name)
        r = run(argv(out), timeout=600)
        if r.returncode or not os.path.exists(out):
            fail("could not write %s: %s"
                 % (name, (r.stdout + r.stderr).strip()[:300]))
            continue
        print("  %-13s %d bytes" % (name, os.path.getsize(out)))
        if not have_lo:
            print("  (no soffice: the independent half of this stage is SKIPPED)")
            return
        flat = soffice_flat(out, os.path.join(GEN, tmp))
        if flat is None:
            fail("LibreOffice REFUSED the %s we wrote" % name)
            continue
        missing = [why for s, why in WRITTEN_MUST_HAVE if s not in flat]
        if missing:
            fail("LibreOffice opened our %s but did not find: %s"
                 % (name, ", ".join(missing)))
        else:
            print("  %-13s LibreOffice reads back all %d checked features"
                  % (name, len(WRITTEN_MUST_HAVE)))

# ---- 4c'. the presentation WE write, judged by LibreOffice ------------------
# ppttest wtest already proves writer and reader agree; this is the
# independent half.  Impress has no text filter, so the check goes through
# flat ODF: every string the demo deck carries must appear, and the deck must
# come back as exactly two draw:page elements.
WRITTEN_PPT_MUST_HAVE = [
    ("Slide one title",   "the first slide's title"),
    ("alpha line",        "a body paragraph"),
    ("beta line",         "the second body paragraph"),
    ("Slide two title",   "the second slide's title"),
    ("café €",            "the UTF-16 text atom (CP-1252 specials)"),
]

def written_ppt(have_lo):
    for name, verb, tmp in (("written.ppt",  "wfile",  "lo_wppt"),
                            ("written.pptx", "wxfile", "lo_wpptx")):
        out = os.path.join(GEN, name)
        r = run([PBIN, verb, out], timeout=600)
        if r.returncode or not os.path.exists(out):
            fail("could not write %s: %s"
                 % (name, (r.stdout + r.stderr).strip()[:300]))
            continue
        print("  %-13s %d bytes" % (name, os.path.getsize(out)))
        if not have_lo:
            print("  (no soffice: the independent half of this stage is SKIPPED)")
            return
        flat = soffice_flat(out, os.path.join(GEN, tmp))
        if flat is None:
            fail("LibreOffice REFUSED the %s we wrote" % name)
            continue
        missing = [why for s, why in WRITTEN_PPT_MUST_HAVE if s not in flat]
        pages = flat.count("<draw:page ")
        if missing:
            fail("LibreOffice opened our %s but did not find: %s"
                 % (name, ", ".join(missing)))
        elif pages != 2:
            fail("LibreOffice sees %d draw:page elements in %s, wanted 2"
                 % (pages, name))
        else:
            print("  %-13s LibreOffice reads back all %d checked strings on "
                  "2 pages" % (name, len(WRITTEN_PPT_MUST_HAVE)))

# ---- 4d. documents: our text against LibreOffice's -------------------------
def lo_txt(path, outdir):
    env = dict(os.environ)
    env["HOME"] = PROFILE
    env["SAL_USE_VCLPLUGIN"] = "svp"
    os.makedirs(PROFILE, exist_ok=True)
    os.makedirs(outdir, exist_ok=True)
    subprocess.run(["soffice", "--headless", "--norestore", "--convert-to",
                    "txt:Text (encoded):UTF8", "--outdir", outdir, path],
                   capture_output=True, text=True, env=env, timeout=600)
    out = os.path.join(outdir, os.path.splitext(os.path.basename(path))[0] + ".txt")
    if not os.path.exists(out):
        return None
    with open(out, encoding="utf-8", errors="replace") as f:
        return f.read()

def norm_lines(text):
    """Compare on content, not layout: the two extractors disagree about
    trailing blank lines and about whether a space run is one space, and
    neither difference means the piece table was walked wrong."""
    out = []
    text = text.lstrip("﻿")        # LibreOffice's UTF-8 output is BOM'd
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = " ".join(line.split())
        if line:
            out.append(line)
    return out

# What fmt.doc PROVABLY contains, and nothing more.  The file was authored
# with seven distinctly formatted runs, but LibreOffice's flat-ODF import
# drops most automatic styles on the way to .doc: converting fmt.doc back to
# ODF shows no bold/italic/size span at all and a single text-align.  So the
# expectations here are what survived, cross-checked against LibreOffice's own
# read-back rather than against what the source asked for.
#
# It is still a real test of the style machinery: `size` is 24 for EVERY run
# and comes from the Normal style chain, not from any direct exception -
# LibreOffice independently reports that style as 12pt - while underline and
# strike are direct CHPX layered on top.
FMT_DOC_EXPECT = [
    ("PLAINWORD",  "size",      24),
    ("BOLDWORD",   "size",      24),
    ("ULINEWORD",  "underline", 1),
    ("ULINEWORD",  "size",      24),
    ("STRIKEWORD", "strike",    1),
    ("CAPSWORD",   "size",      24),
]

def check_fmt_doc(path):
    rr = subprocess.run([DBIN, "fmt", path], capture_output=True, timeout=600)
    got = {}
    for line in rr.stdout.decode("cp1252", errors="replace").splitlines():
        f = line.split("\t")
        if len(f) >= 4:
            got[(f[1], f[2])] = int(f[3])
    bad = [(m, k, v, got.get((m, k))) for m, k, v in FMT_DOC_EXPECT
           if got.get((m, k)) != v]
    if bad:
        fail("fmt.doc: %d formatting expectations differ; first: %s"
             % (len(bad), bad[0]))
    else:
        print("  %-12s %d style-resolved properties match (size comes from "
              "the Normal style chain)" % ("fmt.doc", len(FMT_DOC_EXPECT)))

def documents(files, have_lo):
    for path in files:
        if not (path.endswith(".doc") or path.endswith(".docx")):
            continue
        base = os.path.basename(path)
        r = run([DBIN, "info", path])
        if r.returncode or r.stdout.startswith("ERR:"):
            fail("%s: %s" % (base, (r.stdout + r.stderr).strip()[:300]))
            continue
        print("  %-12s %s" % (base, r.stdout.strip()))
        if base == "fmt.doc":
            check_fmt_doc(path)
        rr = subprocess.run([DBIN, "text", path], capture_output=True, timeout=600)
        if rr.returncode:
            fail("%s: text extraction failed" % base)
            continue
        ours = rr.stdout.decode("cp1252", errors="replace")
        if not have_lo:
            continue
        theirs = lo_txt(path, os.path.join(GEN, "lo_txt"))
        if theirs is None:
            fail("%s: LibreOffice could not convert it to text" % base)
            continue
        a, b = norm_lines(ours), norm_lines(theirs)
        if a != b:
            i = 0
            while i < len(a) and i < len(b) and a[i] == b[i]:
                i += 1
            fail("%s: text differs from LibreOffice's at line %d of %d/%d\n"
                 "      ours:  %r\n      theirs: %r"
                 % (base, i, len(a), len(b),
                    a[i] if i < len(a) else "<end>",
                    b[i] if i < len(b) else "<end>"))
        else:
            print("  %-12s %d lines identical to LibreOffice's extraction"
                  % (base, len(a)))

# ---- 4e. presentations: our slide text against LibreOffice's ----------------
TAGS = re.compile(r"<[^>]*>")

def presentations(files, have_lo):
    for path in files:
        if not (path.endswith(".ppt") or path.endswith(".pptx")):
            continue
        base = os.path.basename(path)
        r = run([PBIN, "info", path])
        if r.returncode or r.stdout.startswith("ERR:"):
            fail("%s: %s" % (base, (r.stdout + r.stderr).strip()[:300]))
            continue
        print("  %-12s %s" % (base, r.stdout.strip().splitlines()[-1]))
        nsh = sum(1 for l in r.stdout.splitlines() if l.startswith("shape"))
        # Escher is the BINARY format's drawing layer. A .pptx stores its
        # shapes as DrawingML inside each slide part and has no Escher at all,
        # so demanding shapes there would be demanding a thing that cannot
        # exist - the check belongs to .ppt.
        if nsh < 1 and path.endswith(".ppt"):
            fail("%s: no Escher shapes found" % base)
        rr = subprocess.run([PBIN, "text", path], capture_output=True, timeout=600)
        ours = norm_lines(rr.stdout.decode("cp1252", errors="replace"))
        if not have_lo:
            continue
        flat = soffice_flat(path, os.path.join(GEN, "lo_ppt"))
        if flat is None:
            fail("%s: LibreOffice could not convert it" % base)
            continue
        # Impress has no text filter, so the comparison goes through flat ODF
        # with the markup stripped.  LibreOffice emits placeholder furniture
        # we do not, so this asserts our text is a SUBSET in order, not an
        # exact match - every line we produce must be a line it produced.
        theirs = norm_lines(TAGS.sub("\n", flat))
        missing = [l for l in ours if l not in theirs]
        if missing:
            fail("%s: %d slide lines are not in LibreOffice's extraction; "
                 "first: %r" % (base, len(missing), missing[0]))
        elif not ours:
            fail("%s: no slide text extracted at all" % base)
        else:
            print("  %-12s %d slide lines all present in LibreOffice's "
                  "extraction" % (base, len(ours)))

def ppt_fuzz(files, iters=2000):
    for path in files:
        if not (path.endswith(".ppt") or path.endswith(".pptx")):
            continue
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([PBIN, "fuzz", path, "77", str(iters)], timeout=1800)
        except subprocess.TimeoutExpired:
            fail("%s: presentation fuzz did not terminate" % base)
            continue
        if r.returncode:
            fail("%s: presentation fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

def doc_fuzz(files, iters=3000):
    for path in files:
        if not (path.endswith(".doc") or path.endswith(".docx")):
            continue
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([DBIN, "fuzz", path, "4242", str(iters)], timeout=1800)
        except subprocess.TimeoutExpired:
            fail("%s: document fuzz did not terminate" % base)
            continue
        if r.returncode:
            fail("%s: document fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

def xls_fuzz(files, iters=3000):
    for path in files:
        if not (path.endswith(".xls") or path.endswith(".xlsx")):
            continue
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([XBIN, "fuzz", path, "999", str(iters)], timeout=1800)
        except subprocess.TimeoutExpired:
            fail("%s: workbook fuzz did not terminate" % base)
            continue
        if r.returncode:
            fail("%s: workbook fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

# ---- 5. fuzz ----------------------------------------------------------------
def fuzz(files, iters=4000):
    for path in files:
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([BIN, "fuzz", path, "12345", str(iters)], timeout=900)
        except subprocess.TimeoutExpired:
            fail("%s: fuzz did not terminate (a chain walk is unbounded)" % base)
            continue
        if r.returncode:
            fail("%s: fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

# ---- main -------------------------------------------------------------------
def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    force = "--force-corpus" in sys.argv
    filt = args[0] if args else ""

    def stage(name, fn, *a):
        if filt and filt not in name:
            return
        print("\n== %s ==" % name)
        fn(*a)

    build()
    stage("selftest", selftest)

    have_lo = shutil.which("soffice") is not None
    if not have_lo and not os.path.isdir(CORPUS):
        print("\n!! soffice not found and no corpus present: the corpus, "
              "rebuild and fuzz stages need one or the other.")
        print("   WSL: sudo apt install libreoffice-writer libreoffice-calc "
              "libreoffice-impress")
        raise SystemExit(1 if fails else 0)

    if have_lo:
        print("\n== corpus ==")
        ensure_corpus(force)
    files = corpus_files()
    if not files:
        fail("corpus is empty")
    else:
        stage("corpus read", read_corpus, files)
        stage("rebuild", rebuild_corpus, files, have_lo)
        stage("workbook", workbooks, files)
        stage("written", written, have_lo)
        stage("written doc", written_doc, have_lo)
        stage("written ppt", written_ppt, have_lo)
        stage("document", documents, files, have_lo)
        stage("presentation", presentations, files, have_lo)
        stage("fuzz", fuzz, files)
        stage("workbook fuzz", xls_fuzz, files)
        stage("document fuzz", doc_fuzz, files)
        stage("presentation fuzz", ppt_fuzz, files)

    print("\n" + ("unodoc gate: %d FAILURE(S)" % len(fails) if fails
                  else "unodoc gate: GREEN"))
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
