#!/usr/bin/env python3
"""unodoc host gate (phase 1: the CFB container).

Runs without booting the OS, over the same sources the .UNO module compiles
freestanding.  Five stages:

  1. build      cfbtest with build.sh's sanitizer set PLUS AddressSanitizer.
                (docs/OFFICE97-PLAN.md §9, the UnoAmp EQ lesson: a harness
                without the OS's flags tests different code.  Every failure
                is fatal - -fno-sanitize-recover=all.)
  2. selftest   in-memory round-trip, directory ordering, the DIFAT overflow
                path, random access, and a battery of corrupt containers.
  3. corpus     open every file in corpus/ (generated by mkcorpus.py from
                LibreOffice headless) and assert the streams each format is
                required to carry are present.
  4. rebuild    read each corpus file, rebuild the container through OUR
                writer, and assert (a) the tree and every stream byte survive
                and (b) LibreOffice still opens the rebuilt file and converts
                it to the same content as the original.  That second half is
                the oracle: it is a third party agreeing our container is
                well formed.
  5. fuzz       thousands of mutations of each corpus file through the
                reader.  Requirement: never crash, never hang.

Usage: python3 run_tests.py [filter-substring] [--force-corpus]
Exit code 0 = green.
"""
import os, re, shutil, subprocess, sys, time

HERE   = os.path.dirname(os.path.abspath(__file__))
UD     = os.path.dirname(HERE)
GEN    = os.path.join(HERE, "gen")
CORPUS = os.path.join(HERE, "corpus")
BIN    = os.path.join(GEN, "cfbtest")
XBIN   = os.path.join(GEN, "xlstest")
DBIN   = os.path.join(GEN, "doctest")
PROFILE = os.path.join(GEN, "loprofile")

# build.sh's first-party sanitizer set, verbatim, plus ASan for the host.
SAN = ["-fsanitize=address,undefined",
       "-fsanitize=signed-integer-overflow,bounds,shift,"
       "integer-divide-by-zero,null",
       "-fno-sanitize-recover=all"]

SRCS  = ["unodoc.c", "ud_cfb.c"]
XSRCS = ["unodoc.c", "ud_cfb.c", "ud_xls.c", "ud_ptg.c", "ud_ptgc.c", "ud_xlsw.c"]
DSRCS = ["unodoc.c", "ud_cfb.c", "ud_doc.c"]

# what each format is required to carry, as unodoc paths
REQUIRED = {
    ".doc": [["WordDocument"], ["\x05SummaryInformation"], ["0Table", "1Table"]],
    ".xls": [["Workbook", "Book"], ["\x05SummaryInformation"]],
    ".ppt": [["PowerPoint Document"], ["Current User"]],
}

fails = []
def fail(msg):
    fails.append(msg)
    print("  FAIL %s" % msg)

def run(args, timeout=300):
    return subprocess.run(args, capture_output=True, text=True,
                          timeout=timeout, errors="replace")

# ---- 1. build ---------------------------------------------------------------
def build():
    os.makedirs(GEN, exist_ok=True)
    cmd = (["gcc", "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Werror",
            "-I", UD] + SAN + ["-o", BIN] +
           [os.path.join(UD, s) for s in SRCS] +
           [os.path.join(HERE, "cfbtest.c")])
    def gcc(out, srcs, main):
        c = (["gcc", "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Werror",
              "-I", UD] + SAN + ["-o", out] +
             [os.path.join(UD, x) for x in srcs] + [os.path.join(HERE, main)])
        rr = run(c)
        if rr.returncode:
            print(rr.stdout + rr.stderr)
            raise SystemExit("build failed: " + out)
    r = run(cmd)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("build failed")
    gcc(XBIN, XSRCS, "xlstest.c")
    gcc(DBIN, DSRCS, "doctest.c")
    print("build: ok")

# ---- 2. selftest ------------------------------------------------------------
SELFTESTS = [
    (lambda: [BIN, "selftest"],  "cfbtest selftest"),
    (lambda: [XBIN, "selftest"], "xlstest selftest"),   # the SST encoding switch
    (lambda: [XBIN, "wtest"],    "xlstest wtest"),      # the writer round-trip
    (lambda: [DBIN, "selftest"], "doctest selftest"),   # the multi-piece walk
]

def selftest():
    for argv, what in SELFTESTS:
        r = run(argv(), timeout=900)
        out = r.stdout.strip()
        print("  " + (out.replace("\n", "\n  ") if out else "(no output)"))
        if r.returncode:
            fail("%s returned %d" % (what, r.returncode))
            if r.stderr.strip():
                print(r.stderr[:4000])

# ---- corpus helpers ---------------------------------------------------------
def corpus_files():
    if not os.path.isdir(CORPUS):
        return []
    return sorted(os.path.join(CORPUS, f) for f in os.listdir(CORPUS)
                  if os.path.splitext(f)[1] in REQUIRED)

def ensure_corpus(force=False):
    args = [sys.executable, os.path.join(HERE, "mkcorpus.py")]
    if force:
        args.append("--force")
    r = run(args, timeout=1800)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("corpus generation failed")
    print(r.stdout.strip().splitlines()[-1])

# ---- 3. corpus read ---------------------------------------------------------
def read_corpus(files):
    for path in files:
        ext = os.path.splitext(path)[1]
        r = run([BIN, "ls", path])
        if r.returncode or "OPEN-FAILED" in r.stdout:
            fail("%s: %s" % (os.path.basename(path),
                             r.stdout.strip()[:200] or "ls returned %d" % r.returncode))
            continue
        names = set()
        for line in r.stdout.splitlines():
            m = re.match(r"\s*[SD] (.*?)(?: \d+ [0-9a-f]{16})?$", line)
            if m:
                names.add(m.group(1))
        missing = [alts for alts in REQUIRED[ext]
                   if not any(a in names for a in alts)]
        entries = len([l for l in r.stdout.splitlines() if l.strip()]) - 1
        if missing:
            fail("%s: missing %s (saw %s)"
                 % (os.path.basename(path),
                    " / ".join("|".join(a) for a in missing),
                    ", ".join(sorted(repr(n) for n in names))))
        else:
            print("  %-12s %7d bytes, %2d entries"
                  % (os.path.basename(path), os.path.getsize(path), entries))

# ---- 4. rebuild + the LibreOffice oracle ------------------------------------
FLAT = {".doc": "fodt", ".xls": "fods", ".ppt": "fodp"}

# Volatile output, nothing to do with the container:
#   office:meta   carries the conversion timestamp
#   Rsid/RsidRoot are Word revision-save ids, which LibreOffice generates
#                 afresh on every load - two conversions of the SAME file
#                 disagree.  Verified 2026-08-01, hence the determinism
#                 self-check below: we never strip a field on faith.
VOLATILE = [
    re.compile(r"<office:meta>.*?</office:meta>", re.S),
    re.compile(r'<config:config-item config:name="Rsid[A-Za-z]*"'
               r'[^>]*>[^<]*</config:config-item>'),
]

def normalize(text):
    for rx in VOLATILE:
        text = rx.sub("", text)
    return text

def first_diff(a, b, ctx=70):
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    lo = max(0, i - ctx)
    return "at %d:\n    A: %r\n    B: %r" % (i, a[lo:i + ctx], b[lo:i + ctx])

def soffice_flat(path, outdir):
    """Convert `path` to flat XML and return its content, normalized."""
    env = dict(os.environ)
    env["HOME"] = PROFILE
    env["SAL_USE_VCLPLUGIN"] = "svp"
    os.makedirs(PROFILE, exist_ok=True)
    os.makedirs(outdir, exist_ok=True)
    fmt = FLAT[os.path.splitext(path)[1]]
    subprocess.run(["soffice", "--headless", "--norestore", "--convert-to",
                    fmt, "--outdir", outdir, path],
                   capture_output=True, text=True, env=env, timeout=600)
    out = os.path.join(outdir, os.path.splitext(os.path.basename(path))[0]
                       + "." + fmt)
    if not os.path.exists(out):
        return None
    with open(out, encoding="utf-8", errors="replace") as f:
        return normalize(f.read())

def rebuild_corpus(files, oracle=True):
    outdir = os.path.join(GEN, "rebuilt")
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)
    for path in files:
        base = os.path.basename(path)
        # (a) our own gate: the tree and every stream byte survive a rebuild
        r = run([BIN, "rt", path])
        if r.returncode:
            fail("%s: %s" % (base, r.stdout.strip()[:400]))
            continue
        out = os.path.join(outdir, base)
        r = run([BIN, "rebuild", path, out])
        if r.returncode:
            fail("%s: rebuild: %s" % (base, r.stdout.strip()[:200]))
            continue
        print("  %-12s rebuild %s" % (base, r.stdout.strip()))
        if not oracle:
            continue
        # (b) the oracle: LibreOffice reads the rebuilt container and gets
        #     the same document back.  The original is converted TWICE first,
        #     so the comparison has to earn the right to be meaningful: if
        #     two conversions of the same bytes already disagree, the
        #     normalizer is missing a volatile field and we say so instead of
        #     reporting a pass we did not establish.
        a1 = soffice_flat(path, os.path.join(GEN, "lo_orig1"))
        a2 = soffice_flat(path, os.path.join(GEN, "lo_orig2"))
        b = soffice_flat(out, os.path.join(GEN, "lo_new"))
        if a1 is None or a2 is None:
            fail("%s: LibreOffice could not convert the ORIGINAL" % base)
        elif a1 != a2:
            fail("%s: oracle is not deterministic - normalize() misses a "
                 "volatile field, so this file proves nothing. Diff %s"
                 % (base, first_diff(a1, a2)))
        elif b is None:
            fail("%s: LibreOffice REFUSED the rebuilt container" % base)
        elif a1 != b:
            fail("%s: LibreOffice read the rebuilt file differently "
                 "(%d vs %d bytes of flat XML). Diff %s"
                 % (base, len(a1), len(b), first_diff(a1, b)))
        else:
            print("  %-12s oracle  LibreOffice agrees (%d bytes flat XML)"
                  % (base, len(a1)))

# ---- 4b. workbook: values against the fixture -------------------------------
def parse_cells(text):
    out = {}
    for line in text.splitlines():
        f = line.split("	")
        if len(f) >= 6 and f[0] == "cell":
            out[(int(f[1]), int(f[2]), int(f[3]))] = (f[4], f[5])
    return out

def parse_formulas(text):
    out = {}
    for line in text.splitlines():
        f = line.split("\t")
        if len(f) >= 5 and f[0] == "formula":
            out[(int(f[1]), int(f[2]), int(f[3]))] = f[4]
    return out

def same(kind, want, got):
    if want == got:
        return True
    if kind == "NUM":
        try:
            return float(want) == float(got)
        except ValueError:
            return False
    return False

def dump_cp1252(path):
    """xlstest emits CP-1252 bytes (unodoc's internal text encoding), so the
    runner decodes them as CP-1252 rather than letting the default UTF-8 turn
    every accented character into a replacement char and a false failure."""
    r = subprocess.run([XBIN, "dump", path], capture_output=True, timeout=600)
    return (r.returncode,
            r.stdout.decode("cp1252", errors="strict"),
            r.stderr.decode("utf-8", errors="replace"))

def workbooks(files):
    for path in files:
        if not path.endswith(".xls"):
            continue
        base = os.path.basename(path)
        fixpath = path + ".expect.tsv"
        try:
            rc, out, err = dump_cp1252(path)
        except UnicodeDecodeError as e:
            fail("%s: dump is not valid CP-1252 (%s)" % (base, e))
            continue
        if rc or out.startswith("ERR:"):
            fail("%s: %s" % (base, (out + err).strip()[:300]))
            continue
        if "!! lookup disagrees" in out:
            fail("%s: random access disagrees with iteration" % base)
        got = parse_cells(out)
        if not os.path.exists(fixpath):
            fail("%s: no fixture" % base)
            continue
        with open(fixpath, encoding="utf-8") as f:
            fixtext = f.read()
        want = parse_cells(fixtext)
        wantf = parse_formulas(fixtext)
        bad, missing = [], []
        for key, (kind, val) in want.items():
            if key not in got:
                missing.append(key)
            elif got[key][0] != kind or not same(kind, val, got[key][1]):
                bad.append((key, (kind, val), got[key]))
        # Extra cells are fine only when they carry no value (blank records
        # that exist just to hold a format, e.g. the covered half of a merge)
        # or when they are formula cells, whose value is whatever the engine
        # computed on save and so is asserted by the `formula` line instead.
        extra = [k for k, v in got.items()
                 if k not in want and k not in wantf and v[0] != "EMPTY"]
        if missing or bad or extra:
            fail("%s: %d missing, %d wrong, %d unexpected; first wrong: %s"
                 % (base, len(missing), len(bad), len(extra),
                    bad[0] if bad else (missing[0] if missing else extra[0])))
        else:
            print("  %-12s %5d cells match the fixture" % (base, len(want)))
        # formulas: the fixture states them in Excel A1 syntax while the
        # source document states them in ODF syntax, so a match means the
        # decompiler rebuilt the expression rather than echoing anything
        if wantf:
            gotf = parse_formulas(out)
            wrong = [(k, wantf[k], gotf.get(k, "<absent>"))
                     for k in wantf if gotf.get(k) != wantf[k]]
            if wrong:
                fail("%s: %d of %d formulas differ; first: %s"
                     % (base, len(wrong), len(wantf), wrong[0]))
            else:
                print("  %-12s %5d formulas decompile exactly"
                      % (base, len(wantf)))
        if base == "cells.xls":
            # the FORMAT/XF path: the two date cells must resolve to a real
            # number-format code, not General
            fmts = [l.split("	")[-1] for l in out.splitlines()
                    if l.startswith("cell	0	6	")]
            if not fmts or any(f == "fmt=General" for f in fmts):
                fail("cells.xls: date cells lost their number format (%s)" % fmts)
            else:
                print("  %-12s date format resolved: %s"
                      % (base, fmts[0].replace("fmt=", "")))

# ---- 4c. the workbook WE write, judged by LibreOffice -----------------------
# xlstest wtest already proves our writer and our reader agree, but a file we
# both write and read could be consistently wrong. This is the independent
# half: LibreOffice opens it and has to find the same content.
WRITTEN_MUST_HAVE = [
    ('table:name="Alpha"',                  "the first sheet"),
    ('table:name="Beta"',                   "the second sheet"),
    ('office:value="1.5"',                  "a plain number"),
    ('office:value="12345678901234"',       "a number past 32 bits"),
    ('office:value="42"',                   "a rewritten cell"),
    ("café naïve Über",      "CP-1252 accents"),
    ("euro € sign",                    "a string that had to go out WIDE"),
    ("#DIV/0!",                             "an error value"),
    ("#N/A",                                "another error value"),
    ('table:number-columns-spanned="3"',    "the merged range"),
    ("number:date-style",                   "a built-in number format"),
    ("kg",                                  "a custom number format"),
    # Formulas WE compiled, as LibreOffice re-renders them in ODF syntax.
    # This is what actually validates the operand classes: a reference in the
    # wrong class still writes, but comes back meaning something else.
    ("of:=1+2*3",                           "operator precedence"),
    ("of:=(1+2)*3",                         "the author's own parentheses"),
    ("of:=2^3^2",                           "left-associative ^"),
    ("of:=-[.B1]",                          "unary minus on a reference"),
    ("of:=50%",                             "postfix percent"),
    ("of:=[.$A$1]",                         "an absolute reference"),
    ("of:=SUM([.A1:.C3])",                  "an area as a function argument"),
    ("of:=IF([.A1]&gt;0;&quot;y&quot;;&quot;n&quot;)",
                                            "mixed argument types"),
    ("of:=SUM(MAX(1;2);MIN(3;4))",          "nested calls"),
    ("of:=[$Alpha.A1]",                     "a 3-D reference"),
    ("of:=SUM([$Alpha.A1:.B2])",            "a 3-D area"),
    ("of:=&quot;a&quot;&quot;b&quot;",       "a doubled quote in a literal"),
]

def written(have_lo):
    out = os.path.join(GEN, "written.xls")
    r = run([XBIN, "wfile", out], timeout=600)
    if r.returncode or not os.path.exists(out):
        fail("could not write a workbook: %s" % (r.stdout + r.stderr).strip()[:300])
        return
    print("  wrote %d bytes" % os.path.getsize(out))
    if not have_lo:
        print("  (no soffice: the independent half of this stage is SKIPPED)")
        return
    flat = soffice_flat(out, os.path.join(GEN, "lo_written"))
    if flat is None:
        fail("LibreOffice REFUSED the workbook we wrote")
        return
    missing = [why for s, why in WRITTEN_MUST_HAVE if s not in flat]
    if missing:
        fail("LibreOffice opened our workbook but did not find: %s"
             % ", ".join(missing))
    else:
        print("  LibreOffice reads back all %d checked features"
              % len(WRITTEN_MUST_HAVE))

# ---- 4d. documents: our text against LibreOffice's -------------------------
def lo_txt(path, outdir):
    env = dict(os.environ)
    env["HOME"] = PROFILE
    env["SAL_USE_VCLPLUGIN"] = "svp"
    os.makedirs(PROFILE, exist_ok=True)
    os.makedirs(outdir, exist_ok=True)
    subprocess.run(["soffice", "--headless", "--norestore", "--convert-to",
                    "txt:Text (encoded):UTF8", "--outdir", outdir, path],
                   capture_output=True, text=True, env=env, timeout=600)
    out = os.path.join(outdir, os.path.splitext(os.path.basename(path))[0] + ".txt")
    if not os.path.exists(out):
        return None
    with open(out, encoding="utf-8", errors="replace") as f:
        return f.read()

def norm_lines(text):
    """Compare on content, not layout: the two extractors disagree about
    trailing blank lines and about whether a space run is one space, and
    neither difference means the piece table was walked wrong."""
    out = []
    text = text.lstrip("﻿")        # LibreOffice's UTF-8 output is BOM'd
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = " ".join(line.split())
        if line:
            out.append(line)
    return out

def documents(files, have_lo):
    for path in files:
        if not path.endswith(".doc"):
            continue
        base = os.path.basename(path)
        r = run([DBIN, "info", path])
        if r.returncode or r.stdout.startswith("ERR:"):
            fail("%s: %s" % (base, (r.stdout + r.stderr).strip()[:300]))
            continue
        print("  %-12s %s" % (base, r.stdout.strip()))
        rr = subprocess.run([DBIN, "text", path], capture_output=True, timeout=600)
        if rr.returncode:
            fail("%s: text extraction failed" % base)
            continue
        ours = rr.stdout.decode("cp1252", errors="replace")
        if not have_lo:
            continue
        theirs = lo_txt(path, os.path.join(GEN, "lo_txt"))
        if theirs is None:
            fail("%s: LibreOffice could not convert it to text" % base)
            continue
        a, b = norm_lines(ours), norm_lines(theirs)
        if a != b:
            i = 0
            while i < len(a) and i < len(b) and a[i] == b[i]:
                i += 1
            fail("%s: text differs from LibreOffice's at line %d of %d/%d\n"
                 "      ours:  %r\n      theirs: %r"
                 % (base, i, len(a), len(b),
                    a[i] if i < len(a) else "<end>",
                    b[i] if i < len(b) else "<end>"))
        else:
            print("  %-12s %d lines identical to LibreOffice's extraction"
                  % (base, len(a)))

def doc_fuzz(files, iters=3000):
    for path in files:
        if not path.endswith(".doc"):
            continue
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([DBIN, "fuzz", path, "4242", str(iters)], timeout=1800)
        except subprocess.TimeoutExpired:
            fail("%s: document fuzz did not terminate" % base)
            continue
        if r.returncode:
            fail("%s: document fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

def xls_fuzz(files, iters=3000):
    for path in files:
        if not path.endswith(".xls"):
            continue
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([XBIN, "fuzz", path, "999", str(iters)], timeout=1800)
        except subprocess.TimeoutExpired:
            fail("%s: workbook fuzz did not terminate" % base)
            continue
        if r.returncode:
            fail("%s: workbook fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

# ---- 5. fuzz ----------------------------------------------------------------
def fuzz(files, iters=4000):
    for path in files:
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([BIN, "fuzz", path, "12345", str(iters)], timeout=900)
        except subprocess.TimeoutExpired:
            fail("%s: fuzz did not terminate (a chain walk is unbounded)" % base)
            continue
        if r.returncode:
            fail("%s: fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

# ---- main -------------------------------------------------------------------
def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    force = "--force-corpus" in sys.argv
    filt = args[0] if args else ""

    def stage(name, fn, *a):
        if filt and filt not in name:
            return
        print("\n== %s ==" % name)
        fn(*a)

    build()
    stage("selftest", selftest)

    have_lo = shutil.which("soffice") is not None
    if not have_lo and not os.path.isdir(CORPUS):
        print("\n!! soffice not found and no corpus present: the corpus, "
              "rebuild and fuzz stages need one or the other.")
        print("   WSL: sudo apt install libreoffice-writer libreoffice-calc "
              "libreoffice-impress")
        raise SystemExit(1 if fails else 0)

    if have_lo:
        print("\n== corpus ==")
        ensure_corpus(force)
    files = corpus_files()
    if not files:
        fail("corpus is empty")
    else:
        stage("corpus read", read_corpus, files)
        stage("rebuild", rebuild_corpus, files, have_lo)
        stage("workbook", workbooks, files)
        stage("written", written, have_lo)
        stage("document", documents, files, have_lo)
        stage("fuzz", fuzz, files)
        stage("workbook fuzz", xls_fuzz, files)
        stage("document fuzz", doc_fuzz, files)

    print("\n" + ("unodoc gate: %d FAILURE(S)" % len(fails) if fails
                  else "unodoc gate: GREEN"))
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
