#!/usr/bin/env python3
"""unodoc host gate (phase 1: the CFB container).

Runs without booting the OS, over the same sources the .UNO module compiles
freestanding.  Five stages:

  1. build      cfbtest with build.sh's sanitizer set PLUS AddressSanitizer.
                (docs/OFFICE97-PLAN.md §9, the UnoAmp EQ lesson: a harness
                without the OS's flags tests different code.  Every failure
                is fatal - -fno-sanitize-recover=all.)
  2. selftest   in-memory round-trip, directory ordering, the DIFAT overflow
                path, random access, and a battery of corrupt containers.
  3. corpus     open every file in corpus/ (generated by mkcorpus.py from
                LibreOffice headless) and assert the streams each format is
                required to carry are present.
  4. rebuild    read each corpus file, rebuild the container through OUR
                writer, and assert (a) the tree and every stream byte survive
                and (b) LibreOffice still opens the rebuilt file and converts
                it to the same content as the original.  That second half is
                the oracle: it is a third party agreeing our container is
                well formed.
  5. fuzz       thousands of mutations of each corpus file through the
                reader.  Requirement: never crash, never hang.

Usage: python3 run_tests.py [filter-substring] [--force-corpus]
Exit code 0 = green.
"""
import os, re, shutil, subprocess, sys, time

HERE   = os.path.dirname(os.path.abspath(__file__))
UD     = os.path.dirname(HERE)
GEN    = os.path.join(HERE, "gen")
CORPUS = os.path.join(HERE, "corpus")
BIN    = os.path.join(GEN, "cfbtest")
PROFILE = os.path.join(GEN, "loprofile")

# build.sh's first-party sanitizer set, verbatim, plus ASan for the host.
SAN = ["-fsanitize=address,undefined",
       "-fsanitize=signed-integer-overflow,bounds,shift,"
       "integer-divide-by-zero,null",
       "-fno-sanitize-recover=all"]

SRCS = ["unodoc.c", "ud_cfb.c"]

# what each format is required to carry, as unodoc paths
REQUIRED = {
    ".doc": [["WordDocument"], ["\x05SummaryInformation"], ["0Table", "1Table"]],
    ".xls": [["Workbook", "Book"], ["\x05SummaryInformation"]],
    ".ppt": [["PowerPoint Document"], ["Current User"]],
}

fails = []
def fail(msg):
    fails.append(msg)
    print("  FAIL %s" % msg)

def run(args, timeout=300):
    return subprocess.run(args, capture_output=True, text=True,
                          timeout=timeout, errors="replace")

# ---- 1. build ---------------------------------------------------------------
def build():
    os.makedirs(GEN, exist_ok=True)
    cmd = (["gcc", "-O1", "-g", "-std=c99", "-Wall", "-Wextra", "-Werror",
            "-I", UD] + SAN + ["-o", BIN] +
           [os.path.join(UD, s) for s in SRCS] +
           [os.path.join(HERE, "cfbtest.c")])
    r = run(cmd)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("build failed")
    print("build: ok")

# ---- 2. selftest ------------------------------------------------------------
def selftest():
    r = run([BIN, "selftest"], timeout=900)
    print("  " + r.stdout.strip().replace("\n", "\n  "))
    if r.returncode:
        fail("selftest returned %d" % r.returncode)
        if r.stderr.strip():
            print(r.stderr[:4000])

# ---- corpus helpers ---------------------------------------------------------
def corpus_files():
    if not os.path.isdir(CORPUS):
        return []
    return sorted(os.path.join(CORPUS, f) for f in os.listdir(CORPUS)
                  if os.path.splitext(f)[1] in REQUIRED)

def ensure_corpus(force=False):
    args = [sys.executable, os.path.join(HERE, "mkcorpus.py")]
    if force:
        args.append("--force")
    r = run(args, timeout=1800)
    if r.returncode:
        print(r.stdout + r.stderr)
        raise SystemExit("corpus generation failed")
    print(r.stdout.strip().splitlines()[-1])

# ---- 3. corpus read ---------------------------------------------------------
def read_corpus(files):
    for path in files:
        ext = os.path.splitext(path)[1]
        r = run([BIN, "ls", path])
        if r.returncode or "OPEN-FAILED" in r.stdout:
            fail("%s: %s" % (os.path.basename(path),
                             r.stdout.strip()[:200] or "ls returned %d" % r.returncode))
            continue
        names = set()
        for line in r.stdout.splitlines():
            m = re.match(r"\s*[SD] (.*?)(?: \d+ [0-9a-f]{16})?$", line)
            if m:
                names.add(m.group(1))
        missing = [alts for alts in REQUIRED[ext]
                   if not any(a in names for a in alts)]
        entries = len([l for l in r.stdout.splitlines() if l.strip()]) - 1
        if missing:
            fail("%s: missing %s (saw %s)"
                 % (os.path.basename(path),
                    " / ".join("|".join(a) for a in missing),
                    ", ".join(sorted(repr(n) for n in names))))
        else:
            print("  %-12s %7d bytes, %2d entries"
                  % (os.path.basename(path), os.path.getsize(path), entries))

# ---- 4. rebuild + the LibreOffice oracle ------------------------------------
FLAT = {".doc": "fodt", ".xls": "fods", ".ppt": "fodp"}

# Volatile output, nothing to do with the container:
#   office:meta   carries the conversion timestamp
#   Rsid/RsidRoot are Word revision-save ids, which LibreOffice generates
#                 afresh on every load - two conversions of the SAME file
#                 disagree.  Verified 2026-08-01, hence the determinism
#                 self-check below: we never strip a field on faith.
VOLATILE = [
    re.compile(r"<office:meta>.*?</office:meta>", re.S),
    re.compile(r'<config:config-item config:name="Rsid[A-Za-z]*"'
               r'[^>]*>[^<]*</config:config-item>'),
]

def normalize(text):
    for rx in VOLATILE:
        text = rx.sub("", text)
    return text

def first_diff(a, b, ctx=70):
    i = 0
    while i < len(a) and i < len(b) and a[i] == b[i]:
        i += 1
    lo = max(0, i - ctx)
    return "at %d:\n    A: %r\n    B: %r" % (i, a[lo:i + ctx], b[lo:i + ctx])

def soffice_flat(path, outdir):
    """Convert `path` to flat XML and return its content, normalized."""
    env = dict(os.environ)
    env["HOME"] = PROFILE
    env["SAL_USE_VCLPLUGIN"] = "svp"
    os.makedirs(PROFILE, exist_ok=True)
    os.makedirs(outdir, exist_ok=True)
    fmt = FLAT[os.path.splitext(path)[1]]
    subprocess.run(["soffice", "--headless", "--norestore", "--convert-to",
                    fmt, "--outdir", outdir, path],
                   capture_output=True, text=True, env=env, timeout=600)
    out = os.path.join(outdir, os.path.splitext(os.path.basename(path))[0]
                       + "." + fmt)
    if not os.path.exists(out):
        return None
    with open(out, encoding="utf-8", errors="replace") as f:
        return normalize(f.read())

def rebuild_corpus(files, oracle=True):
    outdir = os.path.join(GEN, "rebuilt")
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir)
    for path in files:
        base = os.path.basename(path)
        # (a) our own gate: the tree and every stream byte survive a rebuild
        r = run([BIN, "rt", path])
        if r.returncode:
            fail("%s: %s" % (base, r.stdout.strip()[:400]))
            continue
        out = os.path.join(outdir, base)
        r = run([BIN, "rebuild", path, out])
        if r.returncode:
            fail("%s: rebuild: %s" % (base, r.stdout.strip()[:200]))
            continue
        print("  %-12s rebuild %s" % (base, r.stdout.strip()))
        if not oracle:
            continue
        # (b) the oracle: LibreOffice reads the rebuilt container and gets
        #     the same document back.  The original is converted TWICE first,
        #     so the comparison has to earn the right to be meaningful: if
        #     two conversions of the same bytes already disagree, the
        #     normalizer is missing a volatile field and we say so instead of
        #     reporting a pass we did not establish.
        a1 = soffice_flat(path, os.path.join(GEN, "lo_orig1"))
        a2 = soffice_flat(path, os.path.join(GEN, "lo_orig2"))
        b = soffice_flat(out, os.path.join(GEN, "lo_new"))
        if a1 is None or a2 is None:
            fail("%s: LibreOffice could not convert the ORIGINAL" % base)
        elif a1 != a2:
            fail("%s: oracle is not deterministic - normalize() misses a "
                 "volatile field, so this file proves nothing. Diff %s"
                 % (base, first_diff(a1, a2)))
        elif b is None:
            fail("%s: LibreOffice REFUSED the rebuilt container" % base)
        elif a1 != b:
            fail("%s: LibreOffice read the rebuilt file differently "
                 "(%d vs %d bytes of flat XML). Diff %s"
                 % (base, len(a1), len(b), first_diff(a1, b)))
        else:
            print("  %-12s oracle  LibreOffice agrees (%d bytes flat XML)"
                  % (base, len(a1)))

# ---- 5. fuzz ----------------------------------------------------------------
def fuzz(files, iters=4000):
    for path in files:
        base = os.path.basename(path)
        t = time.time()
        try:
            r = run([BIN, "fuzz", path, "12345", str(iters)], timeout=900)
        except subprocess.TimeoutExpired:
            fail("%s: fuzz did not terminate (a chain walk is unbounded)" % base)
            continue
        if r.returncode:
            fail("%s: fuzz: %s" % (base, (r.stdout + r.stderr).strip()[:600]))
        else:
            print("  %-12s %s in %.1fs" % (base, r.stdout.strip(), time.time() - t))

# ---- main -------------------------------------------------------------------
def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    force = "--force-corpus" in sys.argv
    filt = args[0] if args else ""

    def stage(name, fn, *a):
        if filt and filt not in name:
            return
        print("\n== %s ==" % name)
        fn(*a)

    build()
    stage("selftest", selftest)

    have_lo = shutil.which("soffice") is not None
    if not have_lo and not os.path.isdir(CORPUS):
        print("\n!! soffice not found and no corpus present: the corpus, "
              "rebuild and fuzz stages need one or the other.")
        print("   WSL: sudo apt install libreoffice-writer libreoffice-calc "
              "libreoffice-impress")
        raise SystemExit(1 if fails else 0)

    if have_lo:
        print("\n== corpus ==")
        ensure_corpus(force)
    files = corpus_files()
    if not files:
        fail("corpus is empty")
    else:
        stage("corpus read", read_corpus, files)
        stage("rebuild", rebuild_corpus, files, have_lo)
        stage("fuzz", fuzz, files)

    print("\n" + ("unodoc gate: %d FAILURE(S)" % len(fails) if fails
                  else "unodoc gate: GREEN"))
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main())
