#!/usr/bin/env python3
"""Generate genesis/gen_font.i: the shared UnoDOS 8x8 font as Genesis
4bpp tiles (95 glyphs, ASCII 32-126; pixel on = palette index 1).
Usage: python genesis/mkfont.py   (from the repo root)
"""
import re

font = []
for line in open("kernel/font8x8.asm", encoding="latin-1"):
    m = re.match(r"\s*db\s+0b([01]{8})", line)
    if m:
        font.append(int(m.group(1), 2))
assert len(font) == 95 * 8, f"font rows: {len(font)}"

out = open("genesis/gen_font.i", "w", newline="\n")
out.write("; AUTO-GENERATED by genesis/mkfont.py - the shared UnoDOS 8x8\n")
out.write("; font as 4bpp Mega Drive tiles (ASCII 32-126, color index 1)\n")
out.write("font_tiles:\n")
for g in range(95):
    rows = font[g * 8:(g + 1) * 8]
    longs = []
    for r in rows:
        v = 0
        for bit in range(8):
            v <<= 4
            if r & (0x80 >> bit):
                v |= 1
        longs.append(v)
    out.write("        dc.l    " + ",".join(f"${v:08X}" for v in longs) +
              f"   ; '{chr(32+g)}'\n" if 32+g != 39 else
              "        dc.l    " + ",".join(f"${v:08X}" for v in longs) + "\n")
out.write("font_tiles_end:\n")
out.close()
print("wrote genesis/gen_font.i (95 tiles, 4bpp)")
