#!/usr/bin/env python3
"""Convert the shared UnoDOS font (amiga/gen_data.i font8x8, 68K MSB-left
rows) into the Apple II hi-res convention: 7 pixels per byte, BIT 0 =
LEFTMOST pixel, bit 7 clear (the palette bit stays 0 = green/violet group;
irrelevant on monochrome). The shared glyphs keep their rightmost column
blank for spacing, so dropping source bit 0 loses nothing.

Reads ../amiga/gen_data.i (run amiga/mkdata.py first - build.sh does),
writes font7.s as dasm dc.b rows: 95 glyphs (ASCII 32-126), 8 bytes each.
"""
import re, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(HERE, "..", "amiga", "gen_data.i")
out = os.path.join(HERE, "build", "font7.s")

text = open(src).read()
m = re.search(r"font8x8:\n((?:\s+dc\.b[^\n]+\n)+)", text)
if not m:
    sys.exit("font8x8 block not found in gen_data.i")
rows = []
for tok in re.findall(r"\$([0-9A-Fa-f]{2})", m.group(1)):
    rows.append(int(tok, 16))


def conv(b):
    # source: bit7 = leftmost .. bit1 = 7th column (bit0 = spacing, dropped)
    # dest:   bit0 = leftmost .. bit6 = 7th column, bit7 = 0
    o = 0
    for i in range(7):
        if b & (0x80 >> i):
            o |= 1 << i
    return o


os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("; generated by mkfont.py from the shared UnoDOS font - do not edit\n")
    f.write("font7:\n")
    for g in range(0, min(len(rows), 95 * 8), 8):
        vals = ",".join("$%02X" % conv(b) for b in rows[g:g + 8])
        f.write("\tdc.b %s\n" % vals)
print(f"wrote {out}: {min(len(rows)//8,95)} glyphs")
