#!/usr/bin/env python3
"""Bake a compact symbol table into the pc64 DEBUG build.

Reads a linked BOOTX64.EFI, extracts every .text function symbol via `nm`,
computes each one's RVA (symbol VA - PE ImageBase), and emits:

  build/dbg_syms.c   uno_dbgsym_n / _rva[] / _off[] / _str[]  (self-symbolizing
                     crash reports: the OS resolves its own backtraces)
  build/esp/DOCS/SYMBOLS.TXT   "<rva hex>\t<name>" per line, for the host tool
                     tools/crashsym.py to resolve reports copied off the stick

Two-pass safe: the table is const data (PE .rdata, laid out AFTER .text), so
adding it does not move any .text RVA - the addresses captured from pass 1
stay valid in the relinked pass-2 image.  build.sh verifies this.

Usage: mksyms.py <BOOTX64.EFI> <out dbg_syms.c> <out SYMBOLS.TXT> [nm]
"""
import subprocess, sys, struct

def image_base(path):
    with open(path, "rb") as f:
        b = f.read()
    peoff = struct.unpack_from("<I", b, 0x3C)[0]
    assert b[peoff:peoff+4] == b"PE\0\0", "not a PE image"
    # COFF header 20 bytes -> optional header; magic 0x20b = PE32+
    opt = peoff + 24
    magic = struct.unpack_from("<H", b, opt)[0]
    assert magic == 0x20b, "expected PE32+"
    return struct.unpack_from("<Q", b, opt + 0x18)[0]   # ImageBase

def main():
    efi, out_c, out_txt = sys.argv[1], sys.argv[2], sys.argv[3]
    nm = sys.argv[4] if len(sys.argv) > 4 else "x86_64-w64-mingw32-nm"
    base = image_base(efi)
    syms = {}
    out = subprocess.check_output([nm, "-n", efi], text=True, errors="replace")
    for line in out.splitlines():
        p = line.split()
        if len(p) < 3:
            continue
        addr, typ, name = p[0], p[1], " ".join(p[2:])
        if typ not in ("t", "T"):          # text (functions) only
            continue
        try:
            va = int(addr, 16)
        except ValueError:
            continue
        rva = va - base
        if rva < 0 or rva > 0xFFFFFFFF:
            continue
        # keep the first name at each rva (nm -n is address-sorted)
        if rva not in syms:
            syms[rva] = name

    items = sorted(syms.items())
    # de-clutter: drop the compiler's local labels
    items = [(r, n) for (r, n) in items if not n.startswith(".")]

    with open(out_txt, "w") as f:
        f.write("# rva\tname  (UnoDOS pc64 debug build symbol table)\n")
        for r, n in items:
            f.write("%08x\t%s\n" % (r, n))

    # build the C string blob + offset table
    blob = bytearray()
    offs = []
    for _, n in items:
        offs.append(len(blob))
        blob += n.encode("ascii", "replace") + b"\0"

    with open(out_c, "w") as f:
        f.write("/* generated by tools/mksyms.py - do not edit */\n")
        f.write("const unsigned int uno_dbgsym_n = %d;\n" % len(items))
        f.write("const unsigned int uno_dbgsym_rva[] = {\n")
        for i in range(0, len(items), 8):
            f.write("  " + ",".join("0x%xu" % r for r, _ in items[i:i+8]) + ",\n")
        f.write("};\n")
        f.write("const unsigned int uno_dbgsym_off[] = {\n")
        for i in range(0, len(offs), 12):
            f.write("  " + ",".join("%du" % o for o in offs[i:i+12]) + ",\n")
        f.write("};\n")
        f.write("const char uno_dbgsym_str[] = {\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(x) for x in blob[i:i+20]) + ",\n")
        f.write("};\n")
    sys.stderr.write("mksyms: %d symbols, base=0x%x, str=%d bytes\n"
                     % (len(items), base, len(blob)))

if __name__ == "__main__":
    main()
