#!/usr/bin/env python3
# ===========================================================================
# mkuno.py - build .UNO loadable app modules for UnoDOS/pc64.
#
# The pc64 kernel loads apps from storage at runtime (APPS\*.UNO), like the
# C64 port loads .PRG apps through its JMP table.  A .UNO is a flattened
# PE32+ DLL: the sections laid out at their RVAs, plus the two tables the
# tiny in-kernel loader needs - base relocations (u32 RVAs of u64 cells to
# rebase) and named import slots (resolved against the kernel's export
# table).  Imports are FUNCTIONS ONLY: each undefined symbol in the app
# object becomes a one-instruction thunk `jmp *slot(%rip)`; the slot lives
# in the .unoimp section as a 32-byte {char name[24]; u64 addr;} record the
# loader fills in.  No PE parsing, no import libs, no pseudo-relocs at
# runtime.
#
#   mkuno.py thunks  <syms.txt> <out.s>       generate the thunk assembly
#   mkuno.py convert <in.dll>   <out.uno>     flatten the linked DLL
#   mkuno.py pyapp   <in.py>    <out.uno>     wrap Python source (MODF_PYAPP)
#
# .UNO layout (all little-endian):
#   u32 magic 'UNO1'   u16 abi   u16 flags
#   u32 entry_rva      u32 mem_size (SizeOfImage)   u32 file_size
#   u32 nreloc         u32 imp_rva   u32 imp_count
#   u64 pref_base      u32 crc32 (of everything after the header)  u32 rsv
#   image[file_size]   reloc_rva[nreloc] (u32 each)
# ===========================================================================
import struct, sys, zlib

MAGIC = 0x314F4E55          # 'UNO1'
ABI   = 1                   # UNO_ABI_VERSION
NAME_MAX = 23               # 24-byte name field, NUL-terminated
HDR_FMT = "<IHHIIIIIIQII"   # 48 bytes
IMAGE_REL_BASED_ABSOLUTE = 0
IMAGE_REL_BASED_DIR64    = 10
UNO_MODF_PYAPP = 0x0004     # source-container tier (no code/relocs/imports)


def pyapp(py_path, uno_path):
    """Wrap a .py file's source bytes into a UNO_MODF_PYAPP container: the
    48-byte header (flags=PYAPP, file_size=len(src), crc32(src)) followed by
    the raw source.  No image, no relocs, no imports - PYRT.UNO compiles the
    payload at load time.  Source is normalised to LF so an on-disk CRLF
    checkout can't shift the crc away from what the on-device writer produces."""
    src = open(py_path, "rb").read().replace(b"\r\n", b"\n")
    hdr = struct.pack(HDR_FMT, MAGIC, ABI, UNO_MODF_PYAPP,
                      0, len(src), len(src),   # entry=0, mem_size, file_size
                      0, 0, 0,                 # nreloc, imp_rva, imp_count
                      0,                       # pref_base
                      zlib.crc32(src) & 0xFFFFFFFF, 0)
    open(uno_path, "wb").write(hdr + src)
    print("mkuno: %s  PYAPP src=%d bytes" % (uno_path, len(src)))


def gen_thunks(syms_path, out_path):
    syms = [s.strip() for s in open(syms_path) if s.strip()]
    for s in syms:
        if len(s) > NAME_MAX:
            sys.exit("mkuno: import name too long (>%d): %s" % (NAME_MAX, s))
    lines = ["/* generated by mkuno.py - do not edit */"]
    for s in sorted(syms):
        lines += [
            '\t.text',
            '\t.globl %s' % s,
            '%s:' % s,
            '\tjmp *.Luslot_%s(%%rip)' % s,
            '\t.section .unoimp,"w"',
            '\t.asciz "%s"' % s,
            '\t.space %d' % (NAME_MAX - len(s)),
            '.Luslot_%s:' % s,
            '\t.quad 0',
        ]
    open(out_path, "w").write("\n".join(lines) + "\n")
    print("mkuno: %d import thunks -> %s" % (len(syms), out_path))


def convert(dll_path, uno_path, flags=0):
    d = open(dll_path, "rb").read()
    if d[:2] != b"MZ":
        sys.exit("mkuno: not a PE file")
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    if d[pe:pe + 4] != b"PE\0\0":
        sys.exit("mkuno: bad PE signature")
    machine, nsect, _, _, _, opt_sz, _ = struct.unpack_from("<HHIIIHH", d, pe + 4)
    if machine != 0x8664:
        sys.exit("mkuno: not x86-64")
    opt = pe + 24
    if struct.unpack_from("<H", d, opt)[0] != 0x20B:
        sys.exit("mkuno: not PE32+")
    entry      = struct.unpack_from("<I", d, opt + 16)[0]
    image_base = struct.unpack_from("<Q", d, opt + 24)[0]
    size_image = struct.unpack_from("<I", d, opt + 56)[0]
    nddir      = struct.unpack_from("<I", d, opt + 108)[0]

    def ddir(i):
        if i >= nddir:
            return (0, 0)
        return struct.unpack_from("<II", d, opt + 112 + 8 * i)

    # a decoupled module must carry NO firmware-loader baggage
    for i, what in ((9, "TLS directory"), (13, "delay imports")):
        rva, sz = ddir(i)
        if rva or sz:
            sys.exit("mkuno: DLL has a %s - imports must go through thunks" % what)

    # ---- flatten sections at their RVAs ----------------------------------
    img = bytearray(size_image)
    imp_rva = imp_size = 0
    shoff = opt + opt_sz
    for i in range(nsect):
        name, vsz, va, rsz, roff = struct.unpack_from("<8sIIII", d, shoff + 40 * i)
        name = name.rstrip(b"\0").decode()
        n = min(vsz, rsz)
        if n:
            img[va:va + n] = d[roff:roff + n]
        if name == ".unoimp":
            imp_rva, imp_size = va, vsz
    if imp_size % 32:
        sys.exit("mkuno: .unoimp size %d not a multiple of 32" % imp_size)
    imp_count = imp_size // 32

    # mingw ld always emits an .idata with one null descriptor for DLLs;
    # tolerate that, but any REAL import descriptor means a symbol bypassed
    # the thunks - refuse the module.
    irva, isz = ddir(1)
    p = irva
    while p and p + 20 <= irva + isz:
        if any(struct.unpack_from("<5I", img, p)):
            sys.exit("mkuno: DLL has real PE imports - must go through thunks")
        p += 20

    # ---- base relocations -------------------------------------------------
    relocs = []
    rrva, rsz = ddir(5)
    p, end = rrva, rrva + rsz
    while p < end:
        page, bsz = struct.unpack_from("<II", img, p)
        if bsz < 8:
            break
        for off in struct.unpack_from("<%dH" % ((bsz - 8) // 2), img, p + 8):
            t, o = off >> 12, off & 0xFFF
            if t == IMAGE_REL_BASED_ABSOLUTE:
                continue
            if t != IMAGE_REL_BASED_DIR64:
                sys.exit("mkuno: unsupported reloc type %d" % t)
            relocs.append(page + o)
        p += bsz
    relocs.sort()

    # the loaded image never needs its own PE headers or .reloc bytes; the
    # reloc section usually sits last so the zero-trim below drops it.
    if rsz:
        img[rrva:rrva + rsz] = b"\0" * rsz

    # ---- trim trailing zeros (bss + zeroed .reloc stay virtual) ----------
    file_size = len(img)
    while file_size > 0 and img[file_size - 1] == 0:
        file_size -= 1
    file_size = (file_size + 7) & ~7

    payload = bytes(img[:file_size]) + struct.pack("<%dI" % len(relocs), *relocs)
    hdr = struct.pack(HDR_FMT, MAGIC, ABI, flags, entry, size_image, file_size,
                      len(relocs), imp_rva, imp_count, image_base,
                      zlib.crc32(payload) & 0xFFFFFFFF, 0)
    open(uno_path, "wb").write(hdr + payload)
    names = []
    for i in range(imp_count):
        nm = bytes(img[imp_rva + 32 * i: imp_rva + 32 * i + NAME_MAX + 1])
        names.append(nm.split(b"\0")[0].decode())
    print("mkuno: %s  entry=0x%x mem=%dK file=%dK relocs=%d imports=%d (%s)"
          % (uno_path, entry, size_image // 1024, (48 + len(payload)) // 1024,
             len(relocs), imp_count, " ".join(names) if imp_count else "-"))


if __name__ == "__main__":
    if len(sys.argv) == 4 and sys.argv[1] == "thunks":
        gen_thunks(sys.argv[2], sys.argv[3])
    elif len(sys.argv) == 4 and sys.argv[1] == "pyapp":
        pyapp(sys.argv[2], sys.argv[3])
    elif len(sys.argv) in (4, 5) and sys.argv[1] == "convert":
        # optional 4th arg: header flags (1 = unoui-class module)
        convert(sys.argv[2], sys.argv[3],
                int(sys.argv[4], 0) if len(sys.argv) == 5 else 0)
    else:
        sys.exit(__doc__ or "usage: mkuno.py thunks|convert <in> <out> [flags]")
