#!/usr/bin/env python3
"""Rasterise a coarse world land-mask into a C bitmap for the Clock app.

Source: Natural Earth 110m "land" polygons. Natural Earth is explicitly in the
PUBLIC DOMAIN - its terms state no permission is needed and crediting the
authors is unnecessary - so the derived bitmap can ship with UnoDOS under no
obligations at all. The GeoJSON is fetched once and cached next to this script;
the generated header is committed, so a normal build never touches the network.

  python3 tools/mkworldmap.py            regenerate build/world_map.h

Projection is plate carree (equirectangular): x = lon, y = -lat, linearly
mapped. That is the projection the day/night terminator is cheapest to draw in,
which is the whole reason the Clock wants a map.
"""
import json, os, sys, urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(HERE)

SRC_URL = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
           "master/geojson/ne_110m_land.geojson")
CACHE = "tools/ne_110m_land.geojson"
OUT = "build/world_map.h"
W, H = 192, 96                      # 1 px = 1.875 deg lon x 1.875 deg lat


def load():
    if not os.path.exists(CACHE):
        print("fetching Natural Earth 110m land (public domain)...")
        urllib.request.urlretrieve(SRC_URL, CACHE)
    with open(CACHE) as f:
        return json.load(f)


def rings(gj):
    """every outer ring as a list of (lon, lat); holes are ignored - at this
    resolution an inland sea is a pixel or two and not worth the complexity"""
    out = []
    for feat in gj["features"]:
        g = feat["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        for poly in polys:
            if poly:
                out.append([(p[0], p[1]) for p in poly[0]])
    return out


def rasterise(polys):
    """even-odd scanline fill, sampling each pixel at its centre"""
    grid = [[0] * W for _ in range(H)]
    for py in range(H):
        lat = 90.0 - (py + 0.5) * 180.0 / H
        xs = []
        for ring in polys:
            n = len(ring)
            for i in range(n):
                x1, y1 = ring[i]
                x2, y2 = ring[(i + 1) % n]
                if (y1 > lat) == (y2 > lat):
                    continue                       # edge doesn't cross this row
                t = (lat - y1) / (y2 - y1)
                xs.append(x1 + t * (x2 - x1))
        xs.sort()
        for i in range(0, len(xs) - 1, 2):
            a = int((xs[i] + 180.0) * W / 360.0 + 0.5)
            b = int((xs[i + 1] + 180.0) * W / 360.0 + 0.5)
            for px in range(max(0, a), min(W, b)):
                grid[py][px] = 1
    return grid


def emit(grid):
    os.makedirs("build", exist_ok=True)
    rowbytes = (W + 7) // 8
    with open(OUT, "w") as f:
        f.write("/* Generated by tools/mkworldmap.py - do not edit.\n"
                " *\n"
                " * A %dx%d equirectangular land mask, 1 bit per pixel, MSB first.\n"
                " * Derived from Natural Earth 110m land polygons, which are in the\n"
                " * PUBLIC DOMAIN (no permission needed, no attribution required), so\n"
                " * this table carries no licensing obligations.\n"
                " */\n" % (W, H))
        f.write("#ifndef PC64_WORLD_MAP_H\n#define PC64_WORLD_MAP_H\n\n")
        f.write("#define WORLD_W %d\n#define WORLD_H %d\n\n" % (W, H))
        f.write("static const unsigned char kWorldMap[%d] = {\n" % (rowbytes * H))
        for py in range(H):
            row = []
            for bx in range(rowbytes):
                v = 0
                for bit in range(8):
                    px = bx * 8 + bit
                    if px < W and grid[py][px]:
                        v |= 0x80 >> bit
                row.append("0x%02X" % v)
            f.write("    " + ",".join(row) + ",\n")
        f.write("};\n\n#endif\n")
    land = sum(sum(r) for r in grid)
    print("wrote %s: %dx%d, %d land px (%.1f%%), %d bytes"
          % (OUT, W, H, land, 100.0 * land / (W * H), rowbytes * H))


if __name__ == "__main__":
    emit(rasterise(rings(load())))
