#!/usr/bin/env python3
"""Generate snes/gen_data.inc from the shared UnoDOS assets (the SNES
twin of genesis/mkdata.py).

M0 scope: just what the splash needs.
  - tiles_all: one contiguous 4bpp planar tile blob, loaded at the BG1
    character base (VRAM word $1000):
        tile 0     blank (transparent index 0)
        1..95      font (ASCII 32-126): fg = index 1, bg = index 2 (opaque)
        96         solid desktop cell (index 2 = the blue background)
  - pal0: 16-entry BGR555 palette for BG palette line 0. Entries 0..4 are
    the four UnoDOS UI colors (PORT-SPEC SS1): backdrop/bg = DOS blue,
    fg = white, accent cyan, accent magenta.

SNES 4bpp planar tile format (32 bytes / 8x8 tile): bytes 0..15 are eight
(plane0, plane1) row pairs, bytes 16..31 are eight (plane2, plane3) row
pairs. Pixel colour = bit(plane0) | bit(plane1)<<1 | bit(plane2)<<2 |
bit(plane3)<<3, MSB = leftmost pixel.

Usage: python snes/mkdata.py   (from the repo root)
"""
import re

OUT = "snes/gen_data.inc"

# ---------------- font (shared x86 8x8) ----------------
font = []
for line in open("kernel/font8x8.asm", encoding="latin-1"):
    m = re.match(r"\s*db\s+0b([01]{8})", line)
    if m:
        font.append(int(m.group(1), 2))
assert len(font) == 95 * 8, f"font rows: {len(font)}"


def tile4bpp(rows):
    """rows: 8 lists of 8 palette indices (0..15) -> 32 planar bytes."""
    out = bytearray()
    for plane_pair in (0, 2):           # planes (0,1) then (2,3)
        for r in rows:
            lo = hi = 0
            for x in range(8):
                bit = 7 - x
                lo |= ((r[x] >> plane_pair) & 1) << bit
                hi |= ((r[x] >> (plane_pair + 1)) & 1) << bit
            out.append(lo)
            out.append(hi)
    return out


tiles = []   # list of (comment, 32 bytes)

# tile 0: blank / transparent
tiles.append(("blank", tile4bpp([[0] * 8 for _ in range(8)])))

# font tiles 1..95: fg = index 1, bg = index 2 (opaque text cell)
for g in range(95):
    rows = []
    for r in font[g * 8:(g + 1) * 8]:
        rows.append([1 if r & (0x80 >> b) else 2 for b in range(8)])
    ch = chr(32 + g)
    tiles.append(("'%s'" % (ch if ch not in "'" else "quote"), tile4bpp(rows)))

# tile 96: solid desktop cell (index 2 = blue background)
tiles.append(("solid bg(2)", tile4bpp([[2] * 8 for _ in range(8)])))

T_BLANK = 0
T_FONT = 1
T_SOLBG = 96
assert len(tiles) == 97, len(tiles)

# ---------------- palette (BGR555) ----------------
def bgr555(r, g, b):
    return ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)

# entries 0..4 = the UnoDOS UI colours (PORT-SPEC SS1)
PAL = [
    (0x00, 0x00, 0xA8),   # 0 backdrop  (DOS blue - matches bg so transparent reads blue)
    (0xFF, 0xFF, 0xFF),   # 1 fg        (white)
    (0x00, 0x00, 0xA8),   # 2 bg        (DOS blue)
    (0x00, 0xA8, 0xA8),   # 3 accent    (cyan)
    (0xA8, 0x00, 0xA8),   # 4 accent    (magenta)
]
pal0 = [bgr555(*c) for c in PAL] + [0] * (16 - len(PAL))

# ---------------- emit ----------------
def byte_rows(data):
    return "\n".join(
        "    .byte " + ",".join(f"${b:02X}" for b in data[i:i + 16])
        for i in range(0, len(data), 16))

with open(OUT, "w", newline="\n") as f:
    f.write("; AUTO-GENERATED by snes/mkdata.py - do not edit\n\n")
    f.write(f"NTILES      = {len(tiles)}\n")
    f.write(f"TILES_BYTES = {len(tiles) * 32}\n")
    f.write(f"T_BLANK     = {T_BLANK}\n")
    f.write(f"T_FONT      = {T_FONT}\n")
    f.write(f"T_SOLBG     = {T_SOLBG}\n\n")
    f.write("; 4bpp planar tile blob, DMA'd to BG1 char base (VRAM word $1000)\n")
    f.write("tiles_all:\n")
    for comment, data in tiles:
        f.write(f"  ; {comment}\n")
        f.write(byte_rows(data) + "\n")
    f.write("\n; BG palette line 0 (BGR555)\n")
    f.write("pal0:\n")
    f.write("    .word " + ",".join(f"${w:04X}" for w in pal0) + "\n")

print(f"wrote {OUT}: {len(tiles)} tiles, {len(pal0)} palette entries")
