/* ===========================================================================
 * ucc front end - preprocessor, lexer, parser, types, constant folding.
 *
 * UnoC is the C subset documented in docs_esp/LANG.MD: the integer types,
 * pointers/arrays/structs/unions/enums/typedefs/function pointers, the full
 * C expression and statement set, constant initializers (including brace
 * and address-constant forms), and a minimal preprocessor (#include one
 * file deep, object-like #define, #ifdef/#ifndef/#else/#endif).  Left out
 * by design: floats, varargs, bitfields, function-like macros, goto, VLAs.
 *
 * Written from scratch for UnoDOS (CC BY-NC, like the rest of the repo).
 * The structure follows the classic single-pass recursive-descent shape;
 * everything allocates from the caller's work arena and bails out through
 * one setjmp on hard errors, so the compiler needs no OS services at all -
 * the same source builds freestanding inside STUDIO.UNO and hosted for the
 * tools/ucc_test.c battery.
 * ======================================================================== */
#include "ucc_int.h"

/* the legal import list, generated by build.sh from pc64_modload.c (KX names)
 * into build/apps/ucc_kexports.h:  static const char *const kKexports[] and
 * KEXPORTS_N.  Host builds generate the same file (see tools/ucc_test.sh). */
#include UCC_KEXPORTS_H

int ucc_import_ok(const char *name, int len)
{
    int i;
    for (i = 0; i < KEXPORTS_N; i++)
        if ((int)strlen(kKexports[i]) == len &&
            !strncmp(kKexports[i], name, (unsigned long)len)) return 1;
    return 0;
}

/* ---- arena / diagnostics -------------------------------------------------- */
void *ucc_alloc(Cc *cc, long n)
{
    void *p;
    n = (n + 15) & ~15L;
    if (cc->wkuse + n > cc->wkcap) ucc_fatal(cc, "out of compiler memory", 0);
    p = cc->wk + cc->wkuse; cc->wkuse += n;
    return p;
}

static void dcpy(char *dst, int cap, int *pos, const char *s)
{
    while (s && *s && *pos < cap - 1) dst[(*pos)++] = *s++;
    dst[*pos] = 0;
}

static void ucc_diag_at(Cc *cc, const char *file, int line, int col,
                        const char *m1, const char *m2)
{
    if (cc->ndiag < cc->maxdiag) {
        UccDiag *d = &cc->diag[cc->ndiag];
        int pos = 0;
        d->line = line; d->col = col;
        d->file[0] = 0;
        if (file) { int fp = 0; dcpy(d->file, (int)sizeof d->file, &fp, file); }
        dcpy(d->msg, (int)sizeof d->msg, &pos, m1);
        if (m2) { dcpy(d->msg, (int)sizeof d->msg, &pos, " '");
                  dcpy(d->msg, (int)sizeof d->msg, &pos, m2);
                  dcpy(d->msg, (int)sizeof d->msg, &pos, "'"); }
    }
    cc->ndiag++;
}

void ucc_fatal(Cc *cc, const char *m1, const char *m2)
{
    ucc_diag_at(cc, 0, 0, 0, m1, m2);
    __builtin_longjmp(cc->jb, 1);
}

/* copy a token's spelling into a small stack buffer for messages */
static const char *tok_spell(Cc *cc, Tok *t, char *buf, int cap)
{
    static const char *kPunct[P_NPUNCT] = {
        "(", ")", "{", "}", "[", "]", ";", ",", ".", "->", "?", ":", "...",
        "+", "-", "*", "/", "%", "&", "|", "^", "~", "!", "<", ">", "<=",
        ">=", "==", "!=", "<<", ">>", "&&", "||", "++", "--", "=",
        "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "<<=", ">>=",
    };
    static const char *kKw[KW_NKW] = {
        "void", "char", "short", "int", "long", "unsigned", "signed",
        "const", "static", "extern", "struct", "union", "enum", "typedef",
        "if", "else", "while", "do", "for", "switch", "case", "default",
        "break", "continue", "return", "sizeof",
    };
    int pos = 0;
    (void)cc;
    if (!t) return "end of file";
    switch (t->kind) {
    case TK_EOF:   return "end of file";
    case TK_PUNCT: return kPunct[t->id];
    case TK_KW:    return kKw[t->id];
    case TK_NUM:   return "number";
    case TK_STR:   return "string literal";
    default:
        if (t->len >= cap) return "identifier";
        while (pos < t->len) { buf[pos] = t->p[pos]; pos++; }
        buf[pos] = 0;
        return buf;
    }
}

void ucc_err_tok(Cc *cc, Tok *t, const char *m1, const char *m2)
{
    const char *fn = (t && t->file < (u16)cc->nfiles) ? cc->files[t->file] : 0;
    ucc_diag_at(cc, fn, t ? t->line : 0, t ? t->col : 0, m1, m2);
    __builtin_longjmp(cc->jb, 1);
}

/* ============================================================================
 * LEXER (+ the directive layer: the two live in one loop because directives
 * are line-oriented while tokens are not)
 * ========================================================================== */
/* a macro is visible to tokens lexed in [defseq, undefseq); redefinition
 * simply prepends a fresh entry with a later window */
typedef struct Macro Macro;
struct Macro {
    const char *name; int len;
    Tok *body;
    int  defseq, undefseq;
    u8   busy;
    Macro *next;
};

typedef struct Lx {
    Cc *cc;
    const char *p, *end;
    int line, col;
    u16 file;
    int bol;                    /* at beginning of line (only ws so far) */
} Lx;

static int lx_peek(Lx *L)      { return L->p < L->end ? (u8)*L->p : -1; }
static int lx_at(Lx *L, int i) { return L->p + i < L->end ? (u8)L->p[i] : -1; }
static int lx_adv(Lx *L)
{
    int c = lx_peek(L);
    if (c < 0) return c;
    L->p++;
    if (c == '\n') { L->line++; L->col = 1; L->bol = 1; }
    else           { L->col++; if (c != ' ' && c != '\t' && c != '\r') L->bol = 0; }
    return c;
}

/* skip spaces + comments; if stop_nl, stop before a newline (directive mode) */
static void lx_space(Lx *L, int stop_nl)
{
    for (;;) {
        int c = lx_peek(L);
        if (c == ' ' || c == '\t' || c == '\r') { lx_adv(L); continue; }
        if (c == '\n') { if (stop_nl) return; lx_adv(L); continue; }
        if (c == '/' && lx_at(L, 1) == '/') {
            while (lx_peek(L) >= 0 && lx_peek(L) != '\n') lx_adv(L);
            continue;
        }
        if (c == '/' && lx_at(L, 1) == '*') {
            lx_adv(L); lx_adv(L);
            for (;;) {
                if (lx_peek(L) < 0) ucc_fatal(L->cc, "unterminated comment", 0);
                if (lx_peek(L) == '*' && lx_at(L, 1) == '/') { lx_adv(L); lx_adv(L); break; }
                lx_adv(L);
            }
            continue;
        }
        return;
    }
}

static int is_ident0(int c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'; }
static int is_digit(int c)  { return c >= '0' && c <= '9'; }
static int is_ident(int c)  { return is_ident0(c) || is_digit(c); }

static int kw_lookup(const char *p, int len)
{
    static const struct { const char *s; int id; } kw[] = {
        {"void",KW_VOID},{"char",KW_CHAR},{"short",KW_SHORT},{"int",KW_INT},
        {"long",KW_LONG},{"unsigned",KW_UNSIGNED},{"signed",KW_SIGNED},
        {"const",KW_CONST},{"static",KW_STATIC},{"extern",KW_EXTERN},
        {"struct",KW_STRUCT},{"union",KW_UNION},{"enum",KW_ENUM},
        {"typedef",KW_TYPEDEF},{"if",KW_IF},{"else",KW_ELSE},
        {"while",KW_WHILE},{"do",KW_DO},{"for",KW_FOR},{"switch",KW_SWITCH},
        {"case",KW_CASE},{"default",KW_DEFAULT},{"break",KW_BREAK},
        {"continue",KW_CONTINUE},{"return",KW_RETURN},{"sizeof",KW_SIZEOF},
    };
    int i;
    for (i = 0; i < (int)(sizeof kw / sizeof kw[0]); i++)
        if ((int)strlen(kw[i].s) == len && !strncmp(kw[i].s, p, (unsigned long)len))
            return kw[i].id;
    return -1;
}

static int esc_char(Lx *L)
{
    int c = lx_adv(L);
    switch (c) {
    case 'n': return '\n';  case 't': return '\t';  case 'r': return '\r';
    case '0': return 0;     case '\\': return '\\'; case '\'': return '\'';
    case '"': return '"';   case 'b': return '\b';  case 'f': return '\f';
    case 'v': return '\v';  case 'a': return 7;
    case 'x': {
        int v = 0, n = 0;
        for (;;) {
            int d = lx_peek(L);
            if (d >= '0' && d <= '9') d -= '0';
            else if (d >= 'a' && d <= 'f') d -= 'a' - 10;
            else if (d >= 'A' && d <= 'F') d -= 'A' - 10;
            else break;
            v = v * 16 + d; lx_adv(L); n++;
        }
        if (!n) ucc_fatal(L->cc, "bad \\x escape", 0);
        return v & 0xFF;
    }
    default:
        if (c >= '1' && c <= '7') {           /* octal */
            int v = c - '0';
            while (lx_peek(L) >= '0' && lx_peek(L) <= '7')
                v = v * 8 + (lx_adv(L) - '0');
            return v & 0xFF;
        }
        ucc_fatal(L->cc, "bad escape sequence", 0);
        return 0;
    }
}

static Tok *tok_new(Cc *cc, int kind, Lx *L, int line, int col)
{
    Tok *t = ucc_alloc(cc, sizeof *t);
    memset(t, 0, sizeof *t);
    t->kind = (u8)kind; t->file = L ? L->file : 0;
    t->line = line; t->col = col;
    t->seq = ++cc->lexseq;
    return t;
}

/* lex exactly one token (directives already handled by the caller);
 * returns 0 at end of input */
static Tok *lx_one(Lx *L, int stop_nl)
{
    Cc *cc = L->cc;
    int line, col, c;
    Tok *t;

    lx_space(L, stop_nl);
    if (stop_nl && (lx_peek(L) == '\n' || lx_peek(L) < 0)) return 0;
    if (lx_peek(L) < 0) return 0;
    line = L->line; col = L->col;
    c = lx_peek(L);

    if (is_ident0(c)) {
        const char *s = L->p;
        int n = 0, kw;
        while (is_ident(lx_peek(L))) { lx_adv(L); n++; }
        kw = kw_lookup(s, n);
        if (kw >= 0) { t = tok_new(cc, TK_KW, L, line, col); t->id = (u8)kw; }
        else {
            char *cp = ucc_alloc(cc, n + 1);
            memcpy(cp, s, (unsigned long)n); cp[n] = 0;
            t = tok_new(cc, TK_IDENT, L, line, col);
            t->p = cp; t->len = n;
        }
        return t;
    }

    if (is_digit(c)) {
        u64 v = 0;
        t = tok_new(cc, TK_NUM, L, line, col);
        if (c == '0' && (lx_at(L, 1) == 'x' || lx_at(L, 1) == 'X')) {
            lx_adv(L); lx_adv(L);
            for (;;) {
                int d = lx_peek(L);
                if (d >= '0' && d <= '9') d -= '0';
                else if (d >= 'a' && d <= 'f') d -= 'a' - 10;
                else if (d >= 'A' && d <= 'F') d -= 'A' - 10;
                else break;
                v = v * 16 + (u64)d; lx_adv(L);
            }
        } else if (c == '0') {
            while (lx_peek(L) >= '0' && lx_peek(L) <= '7')
                v = v * 8 + (u64)(lx_adv(L) - '0');
        } else {
            while (is_digit(lx_peek(L)))
                v = v * 10 + (u64)(lx_adv(L) - '0');
        }
        for (;;) {                              /* suffixes, any order */
            int d = lx_peek(L);
            if (d == 'u' || d == 'U') { t->num_uns = 1; lx_adv(L); }
            else if (d == 'l' || d == 'L') { t->num_long++; lx_adv(L); }
            else break;
        }
        t->val = (i64)v;
        return t;
    }

    if (c == '\'') {
        int v;
        lx_adv(L);
        c = lx_adv(L);
        if (c == '\\') v = esc_char(L); else v = c;
        if (lx_adv(L) != '\'') ucc_fatal(cc, "unterminated char literal", 0);
        t = tok_new(cc, TK_NUM, L, line, col);
        t->val = (signed char)v;
        return t;
    }

    if (c == '"') {
        /* decode into the arena; worst case = source length */
        char *buf = ucc_alloc(cc, (long)(L->end - L->p) + 1);
        int n = 0;
        lx_adv(L);
        for (;;) {
            c = lx_peek(L);
            if (c < 0 || c == '\n') ucc_fatal(cc, "unterminated string", 0);
            lx_adv(L);
            if (c == '"') break;
            if (c == '\\') c = esc_char(L);
            buf[n++] = (char)c;
        }
        buf[n] = 0;
        t = tok_new(cc, TK_STR, L, line, col);
        t->str = buf; t->slen = n;
        return t;
    }

    /* punctuators - longest match first */
    {
        static const struct { const char *s; int id; } px[] = {
            {"...",P_ELLIPSIS},{"<<=",P_SHLA},{">>=",P_SHRA},
            {"->",P_ARROW},{"++",P_INC},{"--",P_DEC},{"<<",P_SHL},{">>",P_SHR},
            {"<=",P_LE},{">=",P_GE},{"==",P_EQ},{"!=",P_NE},{"&&",P_ANDAND},
            {"||",P_OROR},{"+=",P_ADDA},{"-=",P_SUBA},{"*=",P_MULA},
            {"/=",P_DIVA},{"%=",P_MODA},{"&=",P_ANDA},{"|=",P_ORA},{"^=",P_XORA},
            {"(",P_LPAR},{")",P_RPAR},{"{",P_LBRACE},{"}",P_RBRACE},
            {"[",P_LBRACK},{"]",P_RBRACK},{";",P_SEMI},{",",P_COMMA},
            {".",P_DOT},{"?",P_QUEST},{":",P_COLON},{"+",P_PLUS},{"-",P_MINUS},
            {"*",P_STAR},{"/",P_SLASH},{"%",P_PCT},{"&",P_AMP},{"|",P_PIPE},
            {"^",P_CARET},{"~",P_TILDE},{"!",P_BANG},{"<",P_LT},{">",P_GT},
            {"=",P_ASSIGN},
        };
        int i;
        for (i = 0; i < (int)(sizeof px / sizeof px[0]); i++) {
            int n = (int)strlen(px[i].s), j, hit = 1;
            for (j = 0; j < n; j++)
                if (lx_at(L, j) != px[i].s[j]) { hit = 0; break; }
            if (hit) {
                for (j = 0; j < n; j++) lx_adv(L);
                t = tok_new(cc, TK_PUNCT, L, line, col);
                t->id = (u8)px[i].id;
                return t;
            }
        }
    }
    ucc_fatal(cc, "unexpected character in source", 0);
    return 0;
}

/* ---- directives + include splicing ---------------------------------------- */
/* the macro visible to a token lexed at sequence position seq (entries are
 * prepended, so the first window hit is the latest matching definition) */
static Macro *macro_find(Cc *cc, const char *p, int len, int seq)
{
    Macro *m;
    for (m = cc->macros; m; m = m->next)
        if (m->len == len && !strncmp(m->name, p, (unsigned long)len) &&
            seq >= m->defseq && seq < m->undefseq)
            return m;
    return 0;
}

#define UCC_INC_DEPTH 4
#define UCC_INC_MAX   (192 * 1024L)

static Tok *lex_unit(Cc *cc, const char *src, long len, const char *name,
                     UccIncRead inc, void *incctx, int depth, Tok ***tailp);

/* handle one # directive; L is positioned after the '#' */
static Tok *directive(Cc *cc, Lx *L, UccIncRead inc, void *incctx, int depth,
                      Tok ***tailp, int *skip, int *skdepth, int *sksat)
{
    Tok *d = lx_one(L, 1);
    char nm[24];
    const char *dn;

    if (!d) return 0;                      /* '#' alone on a line */
    dn = tok_spell(cc, d, nm, (int)sizeof nm);

    /* while skipping a dead #if region, only the structure matters */
    if (*skip) {
        if (!strcmp(dn, "ifdef") || !strcmp(dn, "ifndef")) (*skdepth)++;
        else if (!strcmp(dn, "endif")) {
            if (*skdepth) (*skdepth)--; else *skip = 0;
        } else if (!strcmp(dn, "else")) {
            if (!*skdepth && !*sksat) *skip = 0;
        }
        while (lx_one(L, 1)) {}
        return 0;
    }

    if (!strcmp(dn, "include")) {
        Tok *f = lx_one(L, 1);
        char *ibuf; long n;
        Tok *head, **tail2;
        if (!f || f->kind != TK_STR)
            ucc_err_tok(cc, f ? f : d, "#include expects \"FILE\"", 0);
        if (depth >= UCC_INC_DEPTH)
            ucc_err_tok(cc, f, "#include nested too deep", 0);
        if (!inc)
            ucc_err_tok(cc, f, "no include files available here", 0);
        ibuf = ucc_alloc(cc, UCC_INC_MAX);
        n = inc(incctx, f->str, ibuf, UCC_INC_MAX);
        if (n < 0)
            ucc_err_tok(cc, f, "include file not found", f->str);
        while (lx_one(L, 1)) {}
        head = lex_unit(cc, ibuf, n, f->str, inc, incctx, depth + 1, &tail2);
        if (head) { **tailp = head; *tailp = tail2; }
        return 0;
    }
    if (!strcmp(dn, "define")) {
        Tok *id = lx_one(L, 1), *b, **bt;
        Macro *m;
        if (!id || id->kind != TK_IDENT)
            ucc_err_tok(cc, id ? id : d, "#define expects a name", 0);
        if (lx_peek(L) == '(')
            ucc_err_tok(cc, id, "function-like macros are not in UnoC", 0);
        m = ucc_alloc(cc, sizeof *m);
        m->name = id->p; m->len = id->len; m->busy = 0; m->body = 0;
        m->undefseq = 0x7FFFFFFF;
        bt = &m->body;
        while ((b = lx_one(L, 1)) != 0) { *bt = b; bt = &b->next; }
        m->defseq = cc->lexseq + 1;        /* visible from the next token on */
        m->next = cc->macros; cc->macros = m;
        return 0;
    }
    if (!strcmp(dn, "undef")) {
        Tok *id = lx_one(L, 1);
        Macro *m;
        if (id && id->kind == TK_IDENT) {
            m = macro_find(cc, id->p, id->len, cc->lexseq + 1);
            if (m) m->undefseq = cc->lexseq + 1;
        }
        while (lx_one(L, 1)) {}
        return 0;
    }
    if (!strcmp(dn, "ifdef") || !strcmp(dn, "ifndef")) {
        Tok *id = lx_one(L, 1);
        int def;
        if (!id || id->kind != TK_IDENT)
            ucc_err_tok(cc, id ? id : d, "#ifdef expects a name", 0);
        def = macro_find(cc, id->p, id->len, cc->lexseq + 1) != 0;
        if (!strcmp(dn, "ifndef")) def = !def;
        while (lx_one(L, 1)) {}
        if (def) { *skip = 0; *sksat = 1; }     /* branch taken */
        else     { *skip = 1; *skdepth = 0; *sksat = 0; }
        return 0;
    }
    if (!strcmp(dn, "else"))  {                 /* taken branch done */
        while (lx_one(L, 1)) {}
        *skip = 1; *skdepth = 0; *sksat = 1;
        return 0;
    }
    if (!strcmp(dn, "endif")) { while (lx_one(L, 1)) {} *sksat = 0; return 0; }
    if (!strcmp(dn, "pragma")) { while (lx_one(L, 1)) {} return 0; }
    if (!strcmp(dn, "error"))
        ucc_err_tok(cc, d, "#error directive reached", 0);
    if (!strcmp(dn, "if") || !strcmp(dn, "elif"))
        ucc_err_tok(cc, d, "#if expressions are not in UnoC (use #ifdef)", 0);
    ucc_err_tok(cc, d, "unknown preprocessor directive", dn);
    return 0;
}

/* lex a whole file (recursing into includes); appends to a fresh list.
 * Conditional-skip state is per-file, which UnoC can afford because its
 * conditionals are include-guard-grade, not cross-file. */
static Tok *lex_unit(Cc *cc, const char *src, long len, const char *name,
                     UccIncRead inc, void *incctx, int depth, Tok ***tailp)
{
    Lx L;
    Tok *head = 0, **tail = &head, *t;
    int skip = 0, skdepth = 0, sksat = 0;

    if (cc->nfiles >= UCC_MAXFILES) ucc_fatal(cc, "too many include files", 0);
    { char *nm = ucc_alloc(cc, (long)strlen(name) + 1);
      strcpy(nm, name); cc->files[cc->nfiles] = nm; }

    L.cc = cc; L.p = src; L.end = src + len;
    L.line = 1; L.col = 1; L.file = (u16)cc->nfiles++; L.bol = 1;

    for (;;) {
        lx_space(&L, 0);
        if (lx_peek(&L) < 0) break;
        if (lx_peek(&L) == '#' && L.bol) {
            lx_adv(&L);
            directive(cc, &L, inc, incctx, depth, &tail, &skip, &skdepth, &sksat);
            continue;
        }
        if (skip) { lx_adv(&L); continue; }
        t = lx_one(&L, 0);
        if (!t) break;
        *tail = t; tail = &t->next;
    }
    if (skip) ucc_fatal(cc, "missing #endif", name);
    *tailp = tail;
    return head;
}

/* ---- macro expansion (object-like, recursive with busy flags) ------------- */
static Tok *tok_dup(Cc *cc, Tok *t, Tok *site)
{
    Tok *n = ucc_alloc(cc, sizeof *n);
    *n = *t;
    n->next = 0;
    /* report diagnostics (and any later rescans) at the use site */
    n->file = site->file; n->line = site->line; n->col = site->col;
    n->seq = site->seq;
    return n;
}

/* splice a macro body at a use site; nested names rescan against the table
 * as visible AT THE USE SITE (site->seq), per cpp rescanning semantics */
static Tok *expand_list(Cc *cc, Tok *in, Tok *site, int depth)
{
    Tok *head = 0, **tail = &head, *t;
    if (depth > 32) ucc_fatal(cc, "macro expansion too deep", 0);
    for (t = in; t; t = t->next) {
        Macro *m = (t->kind == TK_IDENT)
                 ? macro_find(cc, t->p, t->len, site->seq) : 0;
        if (m && !m->busy) {
            Tok *ex;
            m->busy = 1;
            ex = expand_list(cc, m->body, site, depth + 1);
            m->busy = 0;
            while (ex) { Tok *nx = ex->next; ex->next = 0; *tail = ex; tail = &ex->next; ex = nx; }
        } else {
            Tok *cp = tok_dup(cc, t, site);
            *tail = cp; tail = &cp->next;
        }
    }
    return head;
}

/* expansion over the top-level stream: tokens are already fresh, so only
 * macro hits allocate copies */
static Tok *expand_stream(Cc *cc, Tok *in)
{
    Tok *head = 0, **tail = &head, *t, *nx;
    for (t = in; t; t = nx) {
        Macro *m = (t->kind == TK_IDENT)
                 ? macro_find(cc, t->p, t->len, t->seq) : 0;
        nx = t->next;
        if (m && !m->busy) {
            Tok *ex;
            m->busy = 1;
            ex = expand_list(cc, m->body, t, 1);
            m->busy = 0;
            while (ex) { Tok *x = ex->next; ex->next = 0; *tail = ex; tail = &ex->next; ex = x; }
        } else {
            t->next = 0;
            *tail = t; tail = &t->next;
        }
    }
    {
        Tok *eof = ucc_alloc(cc, sizeof *eof);
        memset(eof, 0, sizeof *eof);
        eof->kind = TK_EOF;
        *tail = eof;
    }
    return head;
}

/* ============================================================================
 * TYPES
 * ========================================================================== */
static Type *ty_new(Cc *cc, int kind, int size, int align)
{
    Type *t = ucc_alloc(cc, sizeof *t);
    memset(t, 0, sizeof *t);
    t->kind = (u8)kind; t->size = size; t->align = align;
    return t;
}
static Type *ty_int(Cc *cc)   { return ty_new(cc, TY_INT, 4, 4); }
static Type *ty_long(Cc *cc)  { return ty_new(cc, TY_LONG, 8, 8); }
static Type *ty_char(Cc *cc)  { return ty_new(cc, TY_CHAR, 1, 1); }
static Type *ty_ptr(Cc *cc, Type *base)
{
    Type *t = ty_new(cc, TY_PTR, 8, 8);
    t->base = base;
    return t;
}
static Type *ty_arr(Cc *cc, Type *base, int n)
{
    Type *t = ty_new(cc, TY_ARR, n >= 0 ? base->size * n : 0, base->align);
    t->base = base; t->arr_len = n;
    return t;
}

int ucc_type_is_int(const Type *t)
{
    return t->kind == TY_CHAR || t->kind == TY_SHORT ||
           t->kind == TY_INT  || t->kind == TY_LONG;
}

/* ============================================================================
 * SCOPES / SYMBOLS
 * ========================================================================== */
static void scope_push(Cc *cc)
{
    Scope *s = ucc_alloc(cc, sizeof *s);
    s->syms = 0; s->tags = 0; s->up = cc->scope;
    cc->scope = s;
}
static void scope_pop(Cc *cc) { cc->scope = cc->scope->up; }

static Sym *sym_find(Cc *cc, const char *p, int len)
{
    Scope *sc; Sym *s;
    for (sc = cc->scope; sc; sc = sc->up)
        for (s = sc->syms; s; s = s->next)
            if ((int)strlen(s->name) == len && !strncmp(s->name, p, (unsigned long)len))
                return s;
    return 0;
}
static Sym *tag_find(Cc *cc, const char *p, int len)
{
    Scope *sc; Sym *s;
    for (sc = cc->scope; sc; sc = sc->up)
        for (s = sc->tags; s; s = s->next)
            if ((int)strlen(s->name) == len && !strncmp(s->name, p, (unsigned long)len))
                return s;
    return 0;
}

static Sym *sym_new(Cc *cc, Tok *id, Type *ty, int cls)
{
    Sym *s = ucc_alloc(cc, sizeof *s);
    char *nm = ucc_alloc(cc, id->len + 1);
    memset(s, 0, sizeof *s);
    memcpy(nm, id->p, (unsigned long)id->len); nm[id->len] = 0;
    s->name = nm; s->ty = ty; s->cls = (u8)cls; s->impno = -1;
    s->next = cc->scope->syms; cc->scope->syms = s;
    return s;
}

/* ============================================================================
 * PARSER
 * ========================================================================== */
static Tok *peek(Cc *cc) { return cc->tok; }
static int  at_punct(Cc *cc, int id) { return cc->tok->kind == TK_PUNCT && cc->tok->id == id; }
static int  at_kw(Cc *cc, int id)    { return cc->tok->kind == TK_KW && cc->tok->id == id; }
static Tok *advance(Cc *cc) { Tok *t = cc->tok; if (t->kind != TK_EOF) cc->tok = t->next; return t; }
static int  eat_punct(Cc *cc, int id) { if (at_punct(cc, id)) { advance(cc); return 1; } return 0; }
static int  eat_kw(Cc *cc, int id)    { if (at_kw(cc, id)) { advance(cc); return 1; } return 0; }
static void expect(Cc *cc, int id, const char *what)
{
    char b[64];
    if (!eat_punct(cc, id))
        ucc_err_tok(cc, cc->tok, what, tok_spell(cc, cc->tok, b, (int)sizeof b));
}

static Node *nd(Cc *cc, int kind, Tok *tok)
{
    Node *n = ucc_alloc(cc, sizeof *n);
    memset(n, 0, sizeof *n);
    n->kind = (u8)kind; n->tok = tok;
    return n;
}
static Node *nd_num(Cc *cc, i64 v, Tok *tok, Type *ty)
{
    Node *n = nd(cc, ND_NUM, tok);
    n->val = v; n->ty = ty ? ty : ty_int(cc);
    return n;
}

/* forward decls */
static Node *expr(Cc *cc);
static Node *assign(Cc *cc);
static Node *cond_expr(Cc *cc);
static Node *unary(Cc *cc);
static Node *stmt(Cc *cc);
static Node *block(Cc *cc);
static Type *declspec(Cc *cc, int *storage);
static Type *declarator(Cc *cc, Type *base, Tok **name);
static int   is_typename(Cc *cc, Tok *t);

/* Recursion-depth guard for the recursive-descent parser: deeply nested source
 * must not overrun the ring0 stack and triple-fault. Each recursive entry point
 * bumps depth on the way in and drops it on the normal return. On the error
 * path ucc_fatal longjmps straight to the top-level handler (which returns and
 * ends the compile), so rec_leave is skipped and depth is left stale - that is
 * harmless because ucc_compile memsets the whole Cc (depth = 0) at entry, so the
 * count never carries across compiles. */
#define UCC_MAX_DEPTH 200
static void rec_enter(Cc *cc){ if (++cc->depth > UCC_MAX_DEPTH) ucc_fatal(cc, "nesting too deep", 0); }
static void rec_leave(Cc *cc){ cc->depth--; }

/* storage flags */
enum { ST_TYPEDEF = 1, ST_STATIC = 2, ST_EXTERN = 4 };

/* ---- type helpers on nodes ------------------------------------------------ */
static Type *decay(Cc *cc, Node **pn)
{
    Node *n = *pn;
    if (n->ty->kind == TY_ARR) {
        Node *a = nd(cc, ND_ADDR, n->tok);
        a->lhs = n; a->ty = ty_ptr(cc, n->ty->base);
        *pn = a;
        return a->ty;
    }
    if (n->ty->kind == TY_FUNC) {
        Node *a = nd(cc, ND_ADDR, n->tok);
        a->lhs = n; a->ty = ty_ptr(cc, n->ty);
        *pn = a;
        return a->ty;
    }
    return n->ty;
}

static Type *usual_arith(Cc *cc, Type *a, Type *b)
{
    int uns;
    if (a->kind == TY_LONG || b->kind == TY_LONG) {
        uns = (a->kind == TY_LONG && a->is_uns) || (b->kind == TY_LONG && b->is_uns);
        { Type *t = ty_long(cc); t->is_uns = (u8)uns; return t; }
    }
    uns = (a->kind == TY_INT && a->is_uns) || (b->kind == TY_INT && b->is_uns);
    { Type *t = ty_int(cc); t->is_uns = (u8)uns; return t; }
}

static Node *mkcast(Cc *cc, Node *n, Type *to)
{
    Node *c;
    if (n->ty == to) return n;
    c = nd(cc, ND_CAST, n->tok);
    c->lhs = n; c->ty = to;
    return c;
}

static Node *mkbin(Cc *cc, int kind, Node *l, Node *r, Tok *t)
{
    Node *n;
    Type *lt, *rt;
    lt = decay(cc, &l); rt = decay(cc, &r);

    if (kind == ND_ADD || kind == ND_SUB) {
        if (lt->kind == TY_PTR && ucc_type_is_int(rt)) {
            n = nd(cc, kind, t);
            r = mkbin(cc, ND_MUL, r,
                      nd_num(cc, lt->base->size ? lt->base->size : 1, t, ty_long(cc)), t);
            n->lhs = l; n->rhs = mkcast(cc, r, ty_long(cc)); n->ty = lt;
            return n;
        }
        if (kind == ND_ADD && rt->kind == TY_PTR && ucc_type_is_int(lt))
            return mkbin(cc, ND_ADD, r, l, t);
        if (kind == ND_SUB && lt->kind == TY_PTR && rt->kind == TY_PTR) {
            Node *d = nd(cc, ND_SUB, t);
            d->lhs = l; d->rhs = r; d->ty = ty_long(cc);
            n = nd(cc, ND_DIV, t);
            n->lhs = d;
            n->rhs = nd_num(cc, lt->base->size ? lt->base->size : 1, t, ty_long(cc));
            n->ty = ty_long(cc);
            return n;
        }
    }
    n = nd(cc, kind, t);
    n->lhs = l; n->rhs = r;
    switch (kind) {
    case ND_EQ: case ND_NE: case ND_LT: case ND_LE:
        /* compare in the common type so mixed widths behave */
        if (ucc_type_is_int(lt) && ucc_type_is_int(rt)) {
            Type *ct = usual_arith(cc, lt, rt);
            n->lhs = mkcast(cc, l, ct);
            n->rhs = mkcast(cc, r, ct);
        }
        n->ty = ty_int(cc);
        break;
    case ND_LOGAND: case ND_LOGOR:
        n->ty = ty_int(cc);
        break;
    case ND_SHL: case ND_SHR:
        /* integer-promote the shifted value; count is an int */
        if (lt->size < 4) {
            Type *pt = ty_int(cc);
            n->lhs = mkcast(cc, l, pt);
            lt = pt;
        }
        n->rhs = mkcast(cc, r, ty_int(cc));
        n->ty = lt;
        break;
    default:
        if (lt->kind == TY_PTR || rt->kind == TY_PTR)
            n->ty = lt->kind == TY_PTR ? lt : rt;   /* ptr +- handled above */
        else {
            n->ty = usual_arith(cc, lt, rt);
            n->lhs = mkcast(cc, l, n->ty);
            n->rhs = mkcast(cc, r, n->ty);
        }
        break;
    }
    return n;
}

/* ---- constant folding ------------------------------------------------------ */
i64 ucc_const_expr(Cc *cc, Node *n, int *ok)
{
    i64 a, b;
    *ok = 1;
    switch (n->kind) {
    case ND_NUM: return n->val;
    case ND_CAST: {
        a = ucc_const_expr(cc, n->lhs, ok);
        if (!*ok) return 0;
        switch (n->ty->kind) {
        case TY_CHAR:  return n->ty->is_uns ? (i64)(u8)a  : (i64)(signed char)a;
        case TY_SHORT: return n->ty->is_uns ? (i64)(u16)a : (i64)(short)a;
        case TY_INT:   return n->ty->is_uns ? (i64)(u32)a : (i64)(int)a;
        default:       return a;
        }
    }
    case ND_NEG:    a = ucc_const_expr(cc, n->lhs, ok); return -a;
    case ND_BITNOT: a = ucc_const_expr(cc, n->lhs, ok); return ~a;
    case ND_NOT:    a = ucc_const_expr(cc, n->lhs, ok); return !a;
    case ND_COND:
        a = ucc_const_expr(cc, n->cond, ok);
        if (!*ok) return 0;
        return ucc_const_expr(cc, a ? n->then : n->els, ok);
    case ND_ADD: case ND_SUB: case ND_MUL: case ND_DIV: case ND_MOD:
    case ND_AND: case ND_OR: case ND_XOR: case ND_SHL: case ND_SHR:
    case ND_EQ: case ND_NE: case ND_LT: case ND_LE:
    case ND_LOGAND: case ND_LOGOR:
        a = ucc_const_expr(cc, n->lhs, ok);
        if (!*ok) return 0;
        b = ucc_const_expr(cc, n->rhs, ok);
        if (!*ok) return 0;
        switch (n->kind) {
        case ND_ADD: return a + b;   case ND_SUB: return a - b;
        case ND_MUL: return a * b;
        case ND_DIV:
            if (!b) { *ok = 0; return 0; }
            if (n->ty->is_uns) return (i64)((u64)a / (u64)b);
            /* INT64_MIN / -1 overflows and would raise #DE on idiv; wrap to
               INT64_MIN, matching two's-complement runtime behaviour */
            if (b == -1 && a == (-9223372036854775807LL - 1)) return a;
            return a / b;
        case ND_MOD:
            if (!b) { *ok = 0; return 0; }
            if (n->ty->is_uns) return (i64)((u64)a % (u64)b);
            /* INT64_MIN % -1 raises #DE the same way; the remainder is 0 */
            if (b == -1 && a == (-9223372036854775807LL - 1)) return 0;
            return a % b;
        case ND_AND: return a & b;   case ND_OR:  return a | b;
        case ND_XOR: return a ^ b;
        case ND_SHL: return a << (b & 63);
        case ND_SHR:
            if (n->ty->is_uns || n->lhs->ty->is_uns) {
                if (n->lhs->ty->size == 4) return (i64)((u32)a >> (b & 31));
                return (i64)((u64)a >> (b & 63));
            }
            return a >> (b & 63);
        case ND_EQ: return a == b;   case ND_NE: return a != b;
        case ND_LT:
            if (n->lhs->ty->is_uns || n->rhs->ty->is_uns) return (u64)a < (u64)b;
            return a < b;
        case ND_LE:
            if (n->lhs->ty->is_uns || n->rhs->ty->is_uns) return (u64)a <= (u64)b;
            return a <= b;
        case ND_LOGAND: return a && b;
        case ND_LOGOR:  return a || b;
        }
        *ok = 0; return 0;
    case ND_COMMA:
        (void)ucc_const_expr(cc, n->lhs, ok);
        if (!*ok) return 0;
        return ucc_const_expr(cc, n->rhs, ok);
    default:
        *ok = 0; return 0;
    }
}

static i64 const_expr_req(Cc *cc, Node *n)
{
    int ok;
    i64 v = ucc_const_expr(cc, n, &ok);
    if (!ok) ucc_err_tok(cc, n->tok, "constant expression required", 0);
    return v;
}

/* ---- struct/union/enum ----------------------------------------------------- */
static void struct_members(Cc *cc, Type *st)
{
    Member *head = 0, **tail = &head;
    int off = 0, align = 1;

    expect(cc, P_LBRACE, "expected { in struct");
    while (!eat_punct(cc, P_RBRACE)) {
        int storage = 0;
        Type *base = declspec(cc, &storage);
        int first = 1;
        if (storage)
            ucc_err_tok(cc, cc->tok, "storage class inside struct", 0);
        if (eat_punct(cc, P_SEMI)) continue;          /* lone tag decl */
        for (;;) {
            Tok *name = 0;
            Type *ty;
            Member *m;
            if (!first) expect(cc, P_COMMA, "expected , or ; in struct");
            first = 0;
            ty = declarator(cc, base, &name);
            if (!name) ucc_err_tok(cc, cc->tok, "member name expected", 0);
            if (ty->kind == TY_VOID || ty->kind == TY_FUNC ||
                (ty->kind == TY_ARR && ty->arr_len < 0) ||
                !ty->size)
                ucc_err_tok(cc, name, "bad member type", 0);
            if (at_punct(cc, P_COLON))
                ucc_err_tok(cc, cc->tok, "bitfields are not in UnoC", 0);
            m = ucc_alloc(cc, sizeof *m);
            m->name = 0; m->ty = ty; m->next = 0;
            { char *nm = ucc_alloc(cc, name->len + 1);
              memcpy(nm, name->p, (unsigned long)name->len); nm[name->len] = 0;
              m->name = nm; }
            if (st->kind == TY_STRUCT) {
                off = (off + ty->align - 1) & ~(ty->align - 1);
                m->off = off;
                off += ty->size;
            } else {
                m->off = 0;
                if (ty->size > off) off = ty->size;
            }
            if (ty->align > align) align = ty->align;
            *tail = m; tail = &m->next;
            if (at_punct(cc, P_SEMI)) break;
        }
        expect(cc, P_SEMI, "expected ; after member");
    }
    st->members = head;
    st->align = align;
    st->size = (off + align - 1) & ~(align - 1);
    if (!st->members) ucc_err_tok(cc, cc->tok, "empty struct", 0);
}

static Type *struct_union_spec(Cc *cc, int kind)
{
    Tok *tag = 0;
    Type *ty;
    Sym *ts;

    if (peek(cc)->kind == TK_IDENT) tag = advance(cc);

    if (tag && !at_punct(cc, P_LBRACE)) {
        ts = tag_find(cc, tag->p, tag->len);
        if (ts) return ts->ty;
        ty = ty_new(cc, kind, 0, 1);        /* incomplete forward tag */
        ts = sym_new(cc, tag, ty, SYM_TYPEDEF);
        /* move onto the tag chain instead of the ordinary chain */
        cc->scope->syms = ts->next;
        ts->next = cc->scope->tags; cc->scope->tags = ts;
        return ty;
    }

    if (tag) {
        ts = tag_find(cc, tag->p, tag->len);
        if (ts && ts->ty->kind == (u8)kind && !ts->ty->members)
            ty = ts->ty;                    /* completing a forward tag */
        else {
            ty = ty_new(cc, kind, 0, 1);
            ts = sym_new(cc, tag, ty, SYM_TYPEDEF);
            cc->scope->syms = ts->next;
            ts->next = cc->scope->tags; cc->scope->tags = ts;
        }
    } else
        ty = ty_new(cc, kind, 0, 1);

    struct_members(cc, ty);
    return ty;
}

static Type *enum_spec(Cc *cc)
{
    Tok *tag = 0;
    i64 v = 0;

    if (peek(cc)->kind == TK_IDENT) tag = advance(cc);
    if (tag && !at_punct(cc, P_LBRACE)) {
        Sym *ts = tag_find(cc, tag->p, tag->len);
        if (ts) return ts->ty;
        ucc_err_tok(cc, tag, "unknown enum tag", 0);
    }
    expect(cc, P_LBRACE, "expected { in enum");
    for (;;) {
        Tok *id;
        Sym *s;
        if (peek(cc)->kind != TK_IDENT)
            ucc_err_tok(cc, cc->tok, "enumerator name expected", 0);
        id = advance(cc);
        if (eat_punct(cc, P_ASSIGN))
            v = const_expr_req(cc, cond_expr(cc));
        s = sym_new(cc, id, ty_int(cc), SYM_ENUMC);
        s->enum_val = v++;
        if (eat_punct(cc, P_COMMA)) {
            if (eat_punct(cc, P_RBRACE)) break;
            continue;
        }
        expect(cc, P_RBRACE, "expected } in enum");
        break;
    }
    if (tag) {
        Sym *ts = sym_new(cc, tag, ty_int(cc), SYM_TYPEDEF);
        cc->scope->syms = ts->next;
        ts->next = cc->scope->tags; cc->scope->tags = ts;
    }
    return ty_int(cc);
}

/* ---- declaration specifiers ------------------------------------------------ */
static int is_typename(Cc *cc, Tok *t)
{
    if (t->kind == TK_KW) {
        switch (t->id) {
        case KW_VOID: case KW_CHAR: case KW_SHORT: case KW_INT: case KW_LONG:
        case KW_UNSIGNED: case KW_SIGNED: case KW_CONST:
        case KW_STRUCT: case KW_UNION: case KW_ENUM:
            return 1;
        }
        return 0;
    }
    if (t->kind == TK_IDENT) {
        Sym *s = sym_find(cc, t->p, t->len);
        return s && s->cls == SYM_TYPEDEF;
    }
    return 0;
}

static Type *declspec(Cc *cc, int *storage)
{
    int uns = -1, base = -1, longs = 0, seen = 0;
    Type *ty = 0;

    for (;;) {
        Tok *t = peek(cc);
        if (t->kind == TK_KW) {
            switch (t->id) {
            case KW_TYPEDEF: if (storage) *storage |= ST_TYPEDEF; advance(cc); continue;
            case KW_STATIC:  if (storage) *storage |= ST_STATIC;  advance(cc); continue;
            case KW_EXTERN:  if (storage) *storage |= ST_EXTERN;  advance(cc); continue;
            case KW_CONST:   advance(cc); continue;               /* parsed, ignored */
            case KW_UNSIGNED: uns = 1; seen = 1; advance(cc); continue;
            case KW_SIGNED:   uns = 0; seen = 1; advance(cc); continue;
            case KW_VOID:  base = TY_VOID;  seen = 1; advance(cc); continue;
            case KW_CHAR:  base = TY_CHAR;  seen = 1; advance(cc); continue;
            case KW_SHORT: base = TY_SHORT; seen = 1; advance(cc); continue;
            case KW_INT:   if (base < 0) base = TY_INT; seen = 1; advance(cc); continue;
            case KW_LONG:  longs++; seen = 1; advance(cc); continue;
            case KW_STRUCT: advance(cc); ty = struct_union_spec(cc, TY_STRUCT); seen = 1; continue;
            case KW_UNION:  advance(cc); ty = struct_union_spec(cc, TY_UNION);  seen = 1; continue;
            case KW_ENUM:   advance(cc); ty = enum_spec(cc); seen = 1; continue;
            }
        }
        if (t->kind == TK_IDENT && !ty && base < 0 && !longs && uns < 0) {
            Sym *s = sym_find(cc, t->p, t->len);
            if (s && s->cls == SYM_TYPEDEF) { ty = s->ty; seen = 1; advance(cc); continue; }
        }
        break;
    }
    if (!seen) ucc_err_tok(cc, cc->tok, "type name expected", 0);
    if (ty) return ty;
    /* LLP64, matching the mingw-built kernel ABI exactly: long is 4 bytes
     * (an int), long long is the 8-byte type */
    if (longs >= 2)      base = TY_LONG;
    else if (longs == 1) base = TY_INT;
    if (base < 0) base = TY_INT;                 /* unsigned / signed alone */
    switch (base) {
    case TY_VOID:  return ty_new(cc, TY_VOID, 0, 1);
    case TY_CHAR:  ty = ty_char(cc); break;
    case TY_SHORT: ty = ty_new(cc, TY_SHORT, 2, 2); break;
    case TY_INT:   ty = ty_int(cc); break;
    default:       ty = ty_long(cc); break;
    }
    ty->is_uns = (u8)(uns == 1);
    return ty;
}

/* ---- declarators ------------------------------------------------------------ */
static Type *func_params(Cc *cc, Type *ret)
{
    Type *fn = ty_new(cc, TY_FUNC, 0, 1);
    Param *head = 0, **tail = &head;
    int n = 0;

    fn->base = ret;
    if (eat_punct(cc, P_RPAR)) { fn->params = 0; fn->nparams = -1; return fn; }
    if (at_kw(cc, KW_VOID) && cc->tok->next->kind == TK_PUNCT &&
        cc->tok->next->id == P_RPAR) {
        advance(cc); advance(cc);
        fn->params = 0; fn->nparams = 0;
        return fn;
    }
    for (;;) {
        Type *bt, *ty;
        Tok *name = 0;
        Param *p;
        if (at_punct(cc, P_ELLIPSIS))
            ucc_err_tok(cc, cc->tok, "varargs are not in UnoC", 0);
        bt = declspec(cc, 0);
        ty = declarator(cc, bt, &name);
        if (ty->kind == TY_ARR) ty = ty_ptr(cc, ty->base);     /* decay */
        if (ty->kind == TY_FUNC) ty = ty_ptr(cc, ty);
        if ((ty->kind == TY_STRUCT || ty->kind == TY_UNION) &&
            ty->size != 1 && ty->size != 2 && ty->size != 4 && ty->size != 8)
            ucc_err_tok(cc, name ? name : cc->tok,
                        "pass structs by pointer in UnoC", 0);
            /* 1/2/4/8-byte structs ride in a register per the MS x64 ABI
             * (Point is the one that matters - GetMouse/click take it) */
        p = ucc_alloc(cc, sizeof *p);
        p->ty = ty; p->name = 0; p->next = 0;
        if (name) {
            char *nm = ucc_alloc(cc, name->len + 1);
            memcpy(nm, name->p, (unsigned long)name->len); nm[name->len] = 0;
            p->name = nm;
        }
        *tail = p; tail = &p->next;
        n++;
        if (n > 8) ucc_err_tok(cc, cc->tok, "more than 8 parameters", 0);
        if (eat_punct(cc, P_RPAR)) break;
        expect(cc, P_COMMA, "expected , in parameter list");
    }
    fn->params = head; fn->nparams = n;
    return fn;
}

/* declarator suffixes: [N]... ( params ) */
static Type *ty_suffix(Cc *cc, Type *ty)
{
    if (eat_punct(cc, P_LPAR)) return func_params(cc, ty);
    if (eat_punct(cc, P_LBRACK)) {
        int n = -1;
        if (!at_punct(cc, P_RBRACK))
            n = (int)const_expr_req(cc, cond_expr(cc));
        expect(cc, P_RBRACK, "expected ]");
        ty = ty_suffix(cc, ty);
        if (ty->kind == TY_FUNC) ucc_err_tok(cc, cc->tok, "array of functions", 0);
        if (n < -1 || (n >= 0 && ty->size && n > (1 << 26) / (ty->size ? ty->size : 1)))
            ucc_err_tok(cc, cc->tok, "bad array size", 0);
        return ty_arr(cc, ty, n);
    }
    return ty;
}

static Type *declarator_r(Cc *cc, Type *base, Tok **name);
static Type *declarator(Cc *cc, Type *base, Tok **name)
{ Type *r; rec_enter(cc); r = declarator_r(cc, base, name); rec_leave(cc); return r; }
static Type *declarator_r(Cc *cc, Type *base, Tok **name)
{
    Type *ty = base;

    while (eat_punct(cc, P_STAR)) {
        ty = ty_ptr(cc, ty);
        while (eat_kw(cc, KW_CONST)) {}
    }

    if (eat_punct(cc, P_LPAR)) {
        /* parenthesized declarator: parse the inner part against a dummy,
         * then re-thread with the real suffixed type (K&R two-pass trick) */
        Tok *save = cc->tok;
        Type dummy;
        Type *inner, *outer;
        memset(&dummy, 0, sizeof dummy);
        dummy.kind = TY_INT; dummy.size = 4; dummy.align = 4;
        (void)declarator(cc, &dummy, name);        /* skip to matching ) */
        expect(cc, P_RPAR, "expected )");
        outer = ty_suffix(cc, ty);
        cc->tok = save;
        inner = declarator(cc, outer, name);
        /* skip the tail we already consumed on the first pass */
        expect(cc, P_RPAR, "expected )");
        ty_suffix(cc, &dummy);                     /* discard re-parse */
        return inner;
    }

    if (name) *name = 0;
    if (peek(cc)->kind == TK_IDENT && !is_typename(cc, peek(cc))) {
        if (!name) ucc_err_tok(cc, cc->tok, "unexpected name in type", 0);
        *name = advance(cc);
    }
    return ty_suffix(cc, ty);
}

/* abstract type name for casts / sizeof */
static Type *typename_parse(Cc *cc)
{
    Type *base = declspec(cc, 0);
    return declarator(cc, base, 0);
}

/* ============================================================================
 * EXPRESSIONS
 * ========================================================================== */
static Member *member_find(Cc *cc, Type *st, Tok *id)
{
    Member *m;
    for (m = st->members; m; m = m->next)
        if ((int)strlen(m->name) == id->len &&
            !strncmp(m->name, id->p, (unsigned long)id->len)) return m;
    ucc_err_tok(cc, id, "no such member", 0);
    return 0;
}

static Node *intern_str(Cc *cc, Tok *t);

static Node *funcall(Cc *cc, Node *fn, Tok *t)
{
    Node *n = nd(cc, ND_CALL, t);
    Node *ah = 0, **at = &ah;
    Type *fty;
    int nargs = 0;

    /* direct call to a plain function symbol keeps the symbol for E8 rel32
     * (and lets undefined externs become imports) */
    if (fn->kind == ND_VAR && fn->ty->kind == TY_FUNC)
        n->sym = fn->sym;
    else {
        decay(cc, &fn);
        if (fn->ty->kind != TY_PTR || fn->ty->base->kind != TY_FUNC)
            ucc_err_tok(cc, t, "called object is not a function", 0);
        n->lhs = fn;
    }
    fty = n->sym ? n->sym->ty : fn->ty->base;

    if (!eat_punct(cc, P_RPAR)) {
        for (;;) {
            Node *a = assign(cc);
            decay(cc, &a);
            if ((a->ty->kind == TY_STRUCT || a->ty->kind == TY_UNION) &&
                a->ty->size != 1 && a->ty->size != 2 &&
                a->ty->size != 4 && a->ty->size != 8)
                ucc_err_tok(cc, a->tok, "pass structs by pointer in UnoC", 0);
            *at = a; at = &a->next;
            nargs++;
            if (nargs > 8) ucc_err_tok(cc, cc->tok, "more than 8 arguments", 0);
            if (eat_punct(cc, P_RPAR)) break;
            expect(cc, P_COMMA, "expected , in argument list");
        }
    }
    if (fty->nparams >= 0 && fty->nparams != nargs)
        ucc_err_tok(cc, t, "wrong number of arguments", n->sym ? n->sym->name : 0);
    n->args = ah;
    n->val = nargs;
    n->ty = fty->base;
    return n;
}

static Node *postfix_tail(Cc *cc, Node *n)
{
    for (;;) {
        Tok *t = peek(cc);
        if (eat_punct(cc, P_LPAR)) { n = funcall(cc, n, t); continue; }
        if (eat_punct(cc, P_LBRACK)) {
            Node *ix = expr(cc);
            Node *d;
            expect(cc, P_RBRACK, "expected ]");
            d = nd(cc, ND_DEREF, t);
            d->lhs = mkbin(cc, ND_ADD, n, ix, t);
            if (d->lhs->ty->kind != TY_PTR)
                ucc_err_tok(cc, t, "subscript on a non-pointer", 0);
            d->ty = d->lhs->ty->base;
            n = d;
            continue;
        }
        if (eat_punct(cc, P_DOT)) {
            Tok *id = advance(cc);
            Member *m;
            Node *mb;
            if (id->kind != TK_IDENT) ucc_err_tok(cc, id, "member name expected", 0);
            if (n->ty->kind != TY_STRUCT && n->ty->kind != TY_UNION)
                ucc_err_tok(cc, t, ". on a non-struct", 0);
            m = member_find(cc, n->ty, id);
            mb = nd(cc, ND_MEMBER, t);
            mb->lhs = n; mb->val = m->off; mb->ty = m->ty;
            n = mb;
            continue;
        }
        if (eat_punct(cc, P_ARROW)) {
            Tok *id = advance(cc);
            Member *m;
            Node *de, *mb;
            if (id->kind != TK_IDENT) ucc_err_tok(cc, id, "member name expected", 0);
            decay(cc, &n);
            if (n->ty->kind != TY_PTR ||
                (n->ty->base->kind != TY_STRUCT && n->ty->base->kind != TY_UNION))
                ucc_err_tok(cc, t, "-> on a non-struct-pointer", 0);
            m = member_find(cc, n->ty->base, id);
            de = nd(cc, ND_DEREF, t);
            de->lhs = n; de->ty = n->ty->base;
            mb = nd(cc, ND_MEMBER, t);
            mb->lhs = de; mb->val = m->off; mb->ty = m->ty;
            n = mb;
            continue;
        }
        if (at_punct(cc, P_INC) || at_punct(cc, P_DEC)) {
            Node *p = nd(cc, peek(cc)->id == P_INC ? ND_POSTINC : ND_POSTDEC, t);
            advance(cc);
            decay(cc, &n);
            p->lhs = n; p->ty = n->ty;
            n = p;
            continue;
        }
        return n;
    }
}

static Node *primary_r(Cc *cc);
static Node *primary(Cc *cc)
{ Node *r; rec_enter(cc); r = primary_r(cc); rec_leave(cc); return r; }
static Node *primary_r(Cc *cc)
{
    Tok *t = peek(cc);

    if (eat_punct(cc, P_LPAR)) {
        Node *n = expr(cc);
        expect(cc, P_RPAR, "expected )");
        return n;
    }
    if (t->kind == TK_NUM) {
        Type *ty;
        advance(cc);
        /* LLP64: only LL (or a value that needs 64 bits) makes a long long */
        if (t->num_long >= 2 || (u64)t->val > 0xFFFFFFFFull)
            ty = ty_long(cc);
        else
            ty = ty_int(cc);
        ty->is_uns = t->num_uns;
        return nd_num(cc, t->val, t, ty);
    }
    if (t->kind == TK_STR) {
        return intern_str(cc, t);
    }
    if (eat_kw(cc, KW_SIZEOF)) {
        Type *ty;
        if (at_punct(cc, P_LPAR) && is_typename(cc, cc->tok->next)) {
            advance(cc);
            ty = typename_parse(cc);
            expect(cc, P_RPAR, "expected )");
        } else {
            Node *n = unary(cc);                       /* sizeof unary-expr */
            ty = n->ty;
        }
        if (!ty->size && ty->kind != TY_ARR)
            ucc_err_tok(cc, t, "sizeof incomplete type", 0);
        { Type *lt = ty_long(cc); lt->is_uns = 1;
          return nd_num(cc, ty->size, t, lt); }
    }
    if (t->kind == TK_IDENT) {
        Sym *s = sym_find(cc, t->p, t->len);
        Node *n;
        advance(cc);
        if (s && s->cls == SYM_ENUMC)
            return nd_num(cc, s->enum_val, t, ty_int(cc));
        if (!s) {
            /* calling an undeclared name is the one classic C leniency we
             * keep: it becomes an extern int() decl - but only if a call
             * follows; anything else is an error */
            if (at_punct(cc, P_LPAR))
                ucc_err_tok(cc, t, "call to undeclared function", 0);
            ucc_err_tok(cc, t, "undeclared identifier", 0);
        }
        n = nd(cc, ND_VAR, t);
        n->sym = s; n->ty = s->ty;
        return n;
    }
    {
        char b[64];
        ucc_err_tok(cc, t, "expression expected, got",
                    tok_spell(cc, t, b, (int)sizeof b));
    }
    return 0;
}

static Node *unary_r(Cc *cc);
static Node *unary(Cc *cc)
{ Node *r; rec_enter(cc); r = unary_r(cc); rec_leave(cc); return r; }
static Node *unary_r(Cc *cc)
{
    Tok *t = peek(cc);

    if (eat_punct(cc, P_PLUS))  return unary(cc);
    if (eat_punct(cc, P_MINUS)) {
        Node *n = nd(cc, ND_NEG, t);
        n->lhs = unary(cc);
        decay(cc, &n->lhs);
        n->ty = n->lhs->ty->kind == TY_LONG ? n->lhs->ty : usual_arith(cc, n->lhs->ty, ty_int(cc));
        return n;
    }
    if (eat_punct(cc, P_TILDE)) {
        Node *n = nd(cc, ND_BITNOT, t);
        n->lhs = unary(cc);
        decay(cc, &n->lhs);
        n->ty = n->lhs->ty;
        return n;
    }
    if (eat_punct(cc, P_BANG)) {
        Node *n = nd(cc, ND_NOT, t);
        n->lhs = unary(cc);
        decay(cc, &n->lhs);
        n->ty = ty_int(cc);
        return n;
    }
    if (eat_punct(cc, P_AMP)) {
        Node *n = nd(cc, ND_ADDR, t);
        n->lhs = unary(cc);
        if (n->lhs->ty->kind == TY_ARR)
            n->ty = ty_ptr(cc, n->lhs->ty->base);
        else if (n->lhs->ty->kind == TY_FUNC)
            n->ty = ty_ptr(cc, n->lhs->ty);
        else
            n->ty = ty_ptr(cc, n->lhs->ty);
        return n;
    }
    if (eat_punct(cc, P_STAR)) {
        Node *n = nd(cc, ND_DEREF, t);
        n->lhs = unary(cc);
        decay(cc, &n->lhs);
        if (n->lhs->ty->kind != TY_PTR)
            ucc_err_tok(cc, t, "* on a non-pointer", 0);
        n->ty = n->lhs->ty->base;
        if (n->ty->kind == TY_FUNC) return n->lhs;     /* *fnptr == fnptr */
        return n;
    }
    if (at_punct(cc, P_INC) || at_punct(cc, P_DEC)) {
        /* ++x -> (x = x + 1); parsed as compound assign for one-eval */
        int dec = peek(cc)->id == P_DEC;
        Node *n;
        advance(cc);
        n = nd(cc, ND_ASSIGN, t);
        n->lhs = unary(cc);
        n->rhs = nd_num(cc, 1, t, ty_int(cc));
        n->val = dec ? ND_SUB : ND_ADD;
        n->ty = n->lhs->ty;
        return n;
    }
    if (at_punct(cc, P_LPAR) && is_typename(cc, t->next)) {
        Type *ty;
        Node *n;
        advance(cc);
        ty = typename_parse(cc);
        expect(cc, P_RPAR, "expected ) after cast");
        n = unary(cc);
        if (ty->kind == TY_VOID) {
            Node *c = nd(cc, ND_CAST, t);
            c->lhs = n; c->ty = ty;
            return c;
        }
        decay(cc, &n);
        return mkcast(cc, n, ty);
    }
    return postfix_tail(cc, primary(cc));
}

/* precedence climbing over the binary operators */
static int bin_prec(int pid)
{
    switch (pid) {
    case P_STAR: case P_SLASH: case P_PCT:  return 10;
    case P_PLUS: case P_MINUS:              return 9;
    case P_SHL: case P_SHR:                 return 8;
    case P_LT: case P_GT: case P_LE: case P_GE: return 7;
    case P_EQ: case P_NE:                   return 6;
    case P_AMP:                             return 5;
    case P_CARET:                           return 4;
    case P_PIPE:                            return 3;
    case P_ANDAND:                          return 2;
    case P_OROR:                            return 1;
    }
    return 0;
}
static int bin_node(int pid)
{
    switch (pid) {
    case P_STAR: return ND_MUL;   case P_SLASH: return ND_DIV;
    case P_PCT: return ND_MOD;    case P_PLUS: return ND_ADD;
    case P_MINUS: return ND_SUB;  case P_SHL: return ND_SHL;
    case P_SHR: return ND_SHR;    case P_LT: return ND_LT;
    case P_LE: return ND_LE;      case P_EQ: return ND_EQ;
    case P_NE: return ND_NE;      case P_AMP: return ND_AND;
    case P_CARET: return ND_XOR;  case P_PIPE: return ND_OR;
    case P_ANDAND: return ND_LOGAND; case P_OROR: return ND_LOGOR;
    default: return -1;
    }
}

static Node *binexpr(Cc *cc, Node *lhs, int minprec)
{
    for (;;) {
        Tok *t = peek(cc);
        int prec, kind, swap = 0;
        if (t->kind != TK_PUNCT) return lhs;
        prec = bin_prec(t->id);
        if (!prec || prec < minprec) return lhs;
        /* a>b and a>=b lower onto LT/LE with swapped operands */
        if (t->id == P_GT || t->id == P_GE) swap = 1;
        kind = bin_node(t->id == P_GT ? P_LT : t->id == P_GE ? P_LE : t->id);
        advance(cc);
        {
            Node *rhs = unary(cc);
            for (;;) {
                Tok *t2 = peek(cc);
                int p2 = (t2->kind == TK_PUNCT) ? bin_prec(t2->id) : 0;
                if (!p2 || p2 <= prec) break;
                rhs = binexpr(cc, rhs, prec + 1);
            }
            lhs = swap ? mkbin(cc, kind, rhs, lhs, t)
                       : mkbin(cc, kind, lhs, rhs, t);
        }
    }
}

static Node *cond_expr_r(Cc *cc);
static Node *cond_expr(Cc *cc)
{ Node *r; rec_enter(cc); r = cond_expr_r(cc); rec_leave(cc); return r; }
static Node *cond_expr_r(Cc *cc)
{
    Node *c = binexpr(cc, unary(cc), 1);
    Tok *t = peek(cc);
    if (eat_punct(cc, P_QUEST)) {
        Node *n = nd(cc, ND_COND, t);
        n->cond = c;
        decay(cc, &n->cond);
        n->then = expr(cc);
        expect(cc, P_COLON, "expected : in ?:");
        n->els = cond_expr(cc);
        decay(cc, &n->then); decay(cc, &n->els);
        if (n->then->ty->kind == TY_PTR)      n->ty = n->then->ty;
        else if (n->els->ty->kind == TY_PTR)  n->ty = n->els->ty;
        else if (n->then->ty->kind == TY_VOID) n->ty = n->then->ty;
        else n->ty = usual_arith(cc, n->then->ty, n->els->ty);
        return n;
    }
    return c;
}

static Node *assign_r(Cc *cc);
static Node *assign(Cc *cc)
{ Node *r; rec_enter(cc); r = assign_r(cc); rec_leave(cc); return r; }
static Node *assign_r(Cc *cc)
{
    Node *l = cond_expr(cc);
    Tok *t = peek(cc);
    static const struct { int pid, op; } ca[] = {
        {P_ASSIGN, 0}, {P_ADDA, ND_ADD}, {P_SUBA, ND_SUB}, {P_MULA, ND_MUL},
        {P_DIVA, ND_DIV}, {P_MODA, ND_MOD}, {P_ANDA, ND_AND}, {P_ORA, ND_OR},
        {P_XORA, ND_XOR}, {P_SHLA, ND_SHL}, {P_SHRA, ND_SHR},
    };
    int i;
    if (t->kind != TK_PUNCT) return l;
    for (i = 0; i < (int)(sizeof ca / sizeof ca[0]); i++) {
        if (t->id == ca[i].pid) {
            Node *n;
            advance(cc);
            n = nd(cc, ND_ASSIGN, t);
            n->lhs = l;
            n->rhs = assign(cc);
            decay(cc, &n->rhs);
            n->val = ca[i].op;
            n->ty = l->ty;
            if (l->ty->kind == TY_ARR || l->ty->kind == TY_FUNC)
                ucc_err_tok(cc, t, "assignment to a non-lvalue", 0);
            if ((l->ty->kind == TY_STRUCT || l->ty->kind == TY_UNION) && ca[i].op)
                ucc_err_tok(cc, t, "compound assign on a struct", 0);
            return n;
        }
    }
    return l;
}

static Node *expr(Cc *cc)
{
    Node *n = assign(cc);
    while (at_punct(cc, P_COMMA)) {
        Tok *t = advance(cc);
        Node *c = nd(cc, ND_COMMA, t);
        c->lhs = n;
        c->rhs = assign(cc);
        c->ty = c->rhs->ty;
        n = c;
    }
    return n;
}

/* ============================================================================
 * DATA SECTION / GLOBAL INITIALIZERS
 * ========================================================================== */
static int data_reserve(Cc *cc, int n, int align)
{
    int off = (cc->datalen + align - 1) & ~(align - 1);
    if (off + n > cc->datacap) ucc_fatal(cc, "data section overflow", 0);
    if (off + n > cc->datalen) memset(cc->data + cc->datalen, 0, (unsigned long)(off + n - cc->datalen));
    cc->datalen = off + n;
    return off;
}

static Node *intern_str(Cc *cc, Tok *t)
{
    Node *n;
    /* adjacent string literal concatenation */
    int total = t->slen;
    Tok *t2 = t->next;
    advance(cc);
    while (t2 && t2->kind == TK_STR) { total += t2->slen; t2 = t2->next; advance(cc); }
    n = nd(cc, ND_STR, t);
    n->ty = ty_arr(cc, ty_char(cc), total + 1);
    if (cc->dry) { n->stroff = 0; return n; }      /* sizing pass: no bytes */
    {
        int off = data_reserve(cc, total + 1, 1);
        int pos = 0;
        Tok *w = t;
        while (w && w->kind == TK_STR && pos < total) {
            memcpy(cc->data + off + pos, w->str, (unsigned long)w->slen);
            pos += w->slen;
            w = w->next;
        }
        cc->data[off + total] = 0;
        n->stroff = off;
    }
    return n;
}

static void dreloc_add(Cc *cc, int off, Sym *sym, int dataoff, int addend)
{
    DReloc *r = ucc_alloc(cc, sizeof *r);
    r->off = off; r->sym = sym; r->dataoff = dataoff; r->addend = addend;
    r->next = cc->drelocs; cc->drelocs = r;
    cc->ndreloc++;
}

/* address-constant analysis for static initializers: string literals,
 * function names, &global, &global.member, &global[K] (constant K), and
 * integer-cast wrappers of those.  Everything else is rejected. */
static int addr_const(Cc *cc, Node *n, Sym **sym, int *dataoff, int *addend)
{
    *sym = 0; *dataoff = 0; *addend = 0;
    for (;;) {
        switch (n->kind) {
        case ND_CAST: case ND_ADDR:
            n = n->lhs;
            continue;
        case ND_MEMBER:
            *addend += (int)n->val;
            n = n->lhs;
            continue;
        case ND_DEREF: {
            /* fold &*(base + CONST): pointer adds carry pre-scaled offsets */
            Node *a = n->lhs;
            int ok;
            while (a->kind == ND_CAST) a = a->lhs;
            if (a->kind == ND_ADD) {
                i64 k = ucc_const_expr(cc, a->rhs, &ok);
                if (!ok) return 0;
                *addend += (int)k;
                n = a->lhs;
                continue;
            }
            n = a;
            continue;
        }
        case ND_STR:
            *dataoff = n->stroff;
            return 1;
        case ND_VAR: {
            Sym *s = n->sym;
            if (s->cls == SYM_FUNC) {
                if (!s->defined && ucc_import_ok(s->name, (int)strlen(s->name)))
                    ucc_err_tok(cc, n->tok,
                        "static initializer cannot hold a kernel import's address",
                        s->name);
                *sym = s;
                return 1;
            }
            if (s->cls == SYM_GLOBAL) { *sym = s; return 1; }
            return 0;
        }
        default:
            return 0;
        }
    }
}

static void gvar_init(Cc *cc, Type *ty, int off);

static void gvar_init_scalar(Cc *cc, Type *ty, int off)
{
    Node *v = assign(cc);
    Sym *sym; int doff, add, ok;

    decay(cc, &v);
    if (cc->dry) return;                    /* sizing pass: parse only */
    if (ty->kind == TY_PTR && addr_const(cc, v, &sym, &doff, &add)) {
        dreloc_add(cc, off, sym, doff, add);
        return;
    }
    {
        i64 c = ucc_const_expr(cc, v, &ok);
        if (!ok) ucc_err_tok(cc, v->tok, "initializer is not constant", 0);
        switch (ty->size) {
        case 1: cc->data[off] = (u8)c; break;
        case 2: *(u16 *)(cc->data + off) = (u16)c; break;
        case 4: *(u32 *)(cc->data + off) = (u32)c; break;
        default: *(u64 *)(cc->data + off) = (u64)c; break;
        }
    }
}

static void gvar_init(Cc *cc, Type *ty, int off)
{
    if (ty->kind == TY_ARR) {
        /* char arr[] = "s" */
        if (peek(cc)->kind == TK_STR && ty->base->size == 1) {
            Tok *t = peek(cc);
            Node *s = intern_str(cc, t);
            int n = s->ty->arr_len;                 /* concatenated length */
            if (ty->arr_len < 0) { ty->arr_len = n; ty->size = n; }
            if (n > ty->arr_len + 1) ucc_err_tok(cc, t, "string too long", 0);
            if (!cc->dry)
                memcpy(cc->data + off, cc->data + s->stroff,
                       (unsigned long)(n > ty->arr_len ? ty->arr_len : n));
            return;
        }
        expect(cc, P_LBRACE, "expected { in array initializer");
        {
            int i = 0;
            if (!at_punct(cc, P_RBRACE)) for (;;) {
                if (ty->arr_len >= 0 && i >= ty->arr_len)
                    ucc_err_tok(cc, cc->tok, "too many array initializers", 0);
                gvar_init(cc, ty->base, off + i * ty->base->size);
                i++;
                if (!eat_punct(cc, P_COMMA)) break;
                if (at_punct(cc, P_RBRACE)) break;
            }
            expect(cc, P_RBRACE, "expected } in array initializer");
            if (ty->arr_len < 0) { ty->arr_len = i; ty->size = i * ty->base->size; }
        }
        return;
    }
    if (ty->kind == TY_STRUCT || ty->kind == TY_UNION) {
        if (!at_punct(cc, P_LBRACE)) {
            /* struct-from-struct constant init isn't expressible */
            ucc_err_tok(cc, cc->tok, "expected { in struct initializer", 0);
        }
        advance(cc);
        {
            Member *m = ty->members;
            if (!at_punct(cc, P_RBRACE)) for (;;) {
                if (!m) ucc_err_tok(cc, cc->tok, "too many struct initializers", 0);
                gvar_init(cc, m->ty, off + m->off);
                m = (ty->kind == TY_UNION) ? 0 : m->next;
                if (!eat_punct(cc, P_COMMA)) break;
                if (at_punct(cc, P_RBRACE)) break;
            }
            expect(cc, P_RBRACE, "expected } in struct initializer");
        }
        return;
    }
    /* scalar; allow one level of braces */
    if (eat_punct(cc, P_LBRACE)) {
        gvar_init_scalar(cc, ty, off);
        expect(cc, P_RBRACE, "expected }");
        return;
    }
    gvar_init_scalar(cc, ty, off);
}

/* array dimensions may be completed by the initializer, so sizing/placement
 * happens in two steps for `T x[] = {...}` */
static void global_var(Cc *cc, Sym *s, int has_init)
{
    Type *ty = s->ty;

    if (!has_init) {
        int off;
        if (ty->kind == TY_ARR && ty->arr_len < 0)
            ucc_err_tok(cc, cc->tok, "array size required", s->name);
        if (!ty->size) ucc_err_tok(cc, cc->tok, "incomplete type", s->name);
        /* uninitialized -> bss */
        off = (cc->bsslen + ty->align - 1) & ~(ty->align - 1);
        cc->bsslen = off + ty->size;
        s->sec = SEC_BSS; s->secoff = off;
        s->defined = 1;
        return;
    }
    if (ty->kind == TY_ARR && ty->arr_len < 0) {
        /* two passes: a dry parse sizes the array (writing nothing), then
         * the tokens rewind and the real parse fills the reserved slot */
        Tok *save = cc->tok;
        cc->dry++;
        gvar_init(cc, ty, 0);
        cc->dry--;
        cc->tok = save;
        s->sec = SEC_DATA;
        s->secoff = data_reserve(cc, ty->size, ty->align);
        s->defined = 1;
        gvar_init(cc, ty, s->secoff);
        return;
    }
    if (!ty->size) ucc_err_tok(cc, cc->tok, "incomplete type", s->name);
    s->sec = SEC_DATA;
    s->secoff = data_reserve(cc, ty->size, ty->align);
    s->defined = 1;
    gvar_init(cc, ty, s->secoff);
}

/* ============================================================================
 * STATEMENTS / FUNCTION BODIES
 * ========================================================================== */
static Sym *local_var(Cc *cc, Tok *name, Type *ty)
{
    Sym *s = sym_new(cc, name, ty, SYM_LOCAL);
    int sz = (ty->size + 7) & ~7;
    cc->lvsize += sz;
    if (cc->lvsize > UCC_LOCALS_MAX)
        ucc_err_tok(cc, name, "stack frame too large", 0);
    s->lvoff = -cc->lvsize;
    return s;
}

static char *uniq_name(Cc *cc, const char *base)
{
    /* "base.N" for function statics */
    long bl = (long)strlen(base);
    char *nm = ucc_alloc(cc, bl + 12);
    int n = cc->statno++;
    char rev[12]; int rl = 0, i;
    memcpy(nm, base, (unsigned long)bl);
    nm[bl] = '.';
    if (!n) rev[rl++] = '0';
    while (n) { rev[rl++] = (char)('0' + n % 10); n /= 10; }
    for (i = 0; i < rl; i++) nm[bl + 1 + i] = rev[rl - 1 - i];
    nm[bl + 1 + rl] = 0;
    return nm;
}

/* local declaration -> statement list of initializer assignments */
static Node *local_decl(Cc *cc)
{
    int storage = 0;
    Type *base = declspec(cc, &storage);
    Node *head = 0, **tail = &head;
    int first = 1;

    if (storage & ST_TYPEDEF) {
        for (;;) {
            Tok *name = 0;
            Type *ty = declarator(cc, base, &name);
            if (!name) ucc_err_tok(cc, cc->tok, "typedef name expected", 0);
            { Sym *s = sym_new(cc, name, ty, SYM_TYPEDEF); (void)s; }
            if (!eat_punct(cc, P_COMMA)) break;
        }
        expect(cc, P_SEMI, "expected ;");
        return nd(cc, ND_NULL, cc->tok);
    }

    if (eat_punct(cc, P_SEMI))                     /* lone struct/enum decl */
        return nd(cc, ND_NULL, cc->tok);

    for (;;) {
        Tok *name = 0;
        Type *ty;
        if (!first) expect(cc, P_COMMA, "expected , or ;");
        first = 0;
        ty = declarator(cc, base, &name);
        if (!name) ucc_err_tok(cc, cc->tok, "variable name expected", 0);
        if (ty->kind == TY_VOID) ucc_err_tok(cc, name, "void variable", 0);
        if (ty->kind == TY_FUNC) {
            Sym *s = sym_new(cc, name, ty, SYM_FUNC);
            (void)s;                               /* local extern fn decl */
            if (at_punct(cc, P_SEMI)) break;
            continue;
        }
        if (storage & ST_STATIC) {
            /* a function-scope static is a global that only this scope sees
             * (globals are placed by Sym identity, never looked up by name,
             * so no renaming is needed) */
            Sym *s = sym_new(cc, name, ty, SYM_GLOBAL);
            s->is_static = 1;
            if (eat_punct(cc, P_ASSIGN)) global_var(cc, s, 1);
            else                          global_var(cc, s, 0);
            if (at_punct(cc, P_SEMI)) break;
            continue;
        }
        if (eat_punct(cc, P_ASSIGN)) {
            if (at_punct(cc, P_LBRACE) ||
                (peek(cc)->kind == TK_STR && ty->kind == TY_ARR)) {
                /* brace/string init of a local: materialize a hidden const
                 * global image, then memcpy it in (backend struct-assign) */
                Sym *img;
                Tok fake;
                Sym *s;
                fake = *name;
                img = ucc_alloc(cc, sizeof *img);
                memset(img, 0, sizeof *img);
                img->name = uniq_name(cc, "init");
                img->ty = ty; img->cls = SYM_GLOBAL; img->is_static = 1;
                img->impno = -1;
                global_var(cc, img, 1);            /* parses the braces */
                ty = img->ty;                      /* [] arrays now sized */
                s = local_var(cc, &fake, ty);
                {
                    Node *st = nd(cc, ND_EXPRSTMT, name);
                    Node *as = nd(cc, ND_ASSIGN, name);
                    Node *dst = nd(cc, ND_VAR, name);
                    Node *src = nd(cc, ND_VAR, name);
                    dst->sym = s; dst->ty = ty;
                    src->sym = img; src->ty = ty;
                    as->lhs = dst; as->rhs = src; as->ty = ty;
                    st->lhs = as;
                    *tail = st; tail = &st->next;
                }
            } else {
                Sym *s;
                Node *st, *as, *dst;
                if (ty->kind == TY_ARR && ty->arr_len < 0)
                    ucc_err_tok(cc, name, "array size required", 0);
                s = local_var(cc, name, ty);
                st = nd(cc, ND_EXPRSTMT, name);
                as = nd(cc, ND_ASSIGN, name);
                dst = nd(cc, ND_VAR, name);
                dst->sym = s; dst->ty = ty;
                as->lhs = dst;
                as->rhs = assign(cc);
                decay(cc, &as->rhs);
                as->ty = ty;
                st->lhs = as;
                *tail = st; tail = &st->next;
            }
        } else {
            if (ty->kind == TY_ARR && ty->arr_len < 0)
                ucc_err_tok(cc, name, "array size required", 0);
            if (!ty->size) ucc_err_tok(cc, name, "incomplete type", 0);
            local_var(cc, name, ty);
        }
        if (at_punct(cc, P_SEMI)) break;
    }
    expect(cc, P_SEMI, "expected ; after declaration");
    {
        Node *b = nd(cc, ND_BLOCK, cc->tok);       /* no new scope needed */
        b->body = head;
        return b;
    }
}

static Node *stmt_r(Cc *cc);
static Node *stmt(Cc *cc)
{ Node *r; rec_enter(cc); r = stmt_r(cc); rec_leave(cc); return r; }
static Node *stmt_r(Cc *cc)
{
    Tok *t = peek(cc);

    if (at_punct(cc, P_LBRACE)) return block(cc);
    if (eat_punct(cc, P_SEMI))  return nd(cc, ND_NULL, t);

    if (eat_kw(cc, KW_IF)) {
        Node *n = nd(cc, ND_IF, t);
        expect(cc, P_LPAR, "expected ( after if");
        n->cond = expr(cc); decay(cc, &n->cond);
        expect(cc, P_RPAR, "expected )");
        n->then = stmt(cc);
        if (eat_kw(cc, KW_ELSE)) n->els = stmt(cc);
        return n;
    }
    if (eat_kw(cc, KW_WHILE)) {
        Node *n = nd(cc, ND_WHILE, t);
        expect(cc, P_LPAR, "expected ( after while");
        n->cond = expr(cc); decay(cc, &n->cond);
        expect(cc, P_RPAR, "expected )");
        n->body = stmt(cc);
        return n;
    }
    if (eat_kw(cc, KW_DO)) {
        Node *n = nd(cc, ND_DO, t);
        n->body = stmt(cc);
        if (!eat_kw(cc, KW_WHILE))
            ucc_err_tok(cc, cc->tok, "expected while after do", 0);
        expect(cc, P_LPAR, "expected (");
        n->cond = expr(cc); decay(cc, &n->cond);
        expect(cc, P_RPAR, "expected )");
        expect(cc, P_SEMI, "expected ;");
        return n;
    }
    if (eat_kw(cc, KW_FOR)) {
        Node *n = nd(cc, ND_FOR, t);
        expect(cc, P_LPAR, "expected ( after for");
        scope_push(cc);
        if (!eat_punct(cc, P_SEMI)) {
            if (is_typename(cc, peek(cc)))
                n->init = local_decl(cc);
            else {
                n->init = nd(cc, ND_EXPRSTMT, peek(cc));
                n->init->lhs = expr(cc);
                expect(cc, P_SEMI, "expected ; in for");
            }
        }
        if (!at_punct(cc, P_SEMI)) { n->cond = expr(cc); decay(cc, &n->cond); }
        expect(cc, P_SEMI, "expected ; in for");
        if (!at_punct(cc, P_RPAR)) n->inc = expr(cc);
        expect(cc, P_RPAR, "expected )");
        n->body = stmt(cc);
        scope_pop(cc);
        return n;
    }
    if (eat_kw(cc, KW_SWITCH)) {
        Node *n = nd(cc, ND_SWITCH, t);
        Node *save = cc->cur_sw;
        expect(cc, P_LPAR, "expected ( after switch");
        n->cond = expr(cc); decay(cc, &n->cond);
        if (!ucc_type_is_int(n->cond->ty))
            ucc_err_tok(cc, t, "switch on a non-integer", 0);
        expect(cc, P_RPAR, "expected )");
        cc->cur_sw = n;
        n->body = stmt(cc);
        cc->cur_sw = save;
        return n;
    }
    if (eat_kw(cc, KW_CASE)) {
        Node *n = nd(cc, ND_CASE, t);
        if (!cc->cur_sw) ucc_err_tok(cc, t, "case outside switch", 0);
        n->val = const_expr_req(cc, cond_expr(cc));
        expect(cc, P_COLON, "expected : after case");
        n->body = stmt(cc);
        n->cases = cc->cur_sw->cases; cc->cur_sw->cases = n;
        return n;
    }
    if (eat_kw(cc, KW_DEFAULT)) {
        Node *n = nd(cc, ND_CASE, t);
        if (!cc->cur_sw) ucc_err_tok(cc, t, "default outside switch", 0);
        if (cc->cur_sw->defcase) ucc_err_tok(cc, t, "duplicate default", 0);
        expect(cc, P_COLON, "expected : after default");
        n->body = stmt(cc);
        n->val = 0;
        cc->cur_sw->defcase = n;
        return n;
    }
    if (eat_kw(cc, KW_BREAK))    { Node *n = nd(cc, ND_BREAK, t); expect(cc, P_SEMI, "expected ;"); return n; }
    if (eat_kw(cc, KW_CONTINUE)) { Node *n = nd(cc, ND_CONT, t);  expect(cc, P_SEMI, "expected ;"); return n; }
    if (eat_kw(cc, KW_RETURN)) {
        Node *n = nd(cc, ND_RETURN, t);
        if (!at_punct(cc, P_SEMI)) {
            n->lhs = expr(cc);
            decay(cc, &n->lhs);
            if (cc->cur_ret->kind == TY_VOID)
                ucc_err_tok(cc, t, "return with a value in a void function", 0);
        } else if (cc->cur_ret->kind != TY_VOID)
            ucc_err_tok(cc, t, "return without a value", 0);
        expect(cc, P_SEMI, "expected ;");
        return n;
    }
    if (is_typename(cc, t) || at_kw(cc, KW_STATIC) || at_kw(cc, KW_TYPEDEF) ||
        at_kw(cc, KW_EXTERN))
        return local_decl(cc);
    {
        Node *n = nd(cc, ND_EXPRSTMT, t);
        n->lhs = expr(cc);
        expect(cc, P_SEMI, "expected ; after expression");
        return n;
    }
}

static Node *block_r(Cc *cc);
static Node *block(Cc *cc)
{ Node *r; rec_enter(cc); r = block_r(cc); rec_leave(cc); return r; }
static Node *block_r(Cc *cc)
{
    Tok *t = peek(cc);
    Node *n = nd(cc, ND_BLOCK, t);
    Node **tail = &n->body;

    expect(cc, P_LBRACE, "expected {");
    scope_push(cc);
    while (!at_punct(cc, P_RBRACE)) {
        Node *s;
        if (peek(cc)->kind == TK_EOF)
            ucc_err_tok(cc, cc->tok, "unexpected end of file in block", 0);
        s = stmt(cc);
        *tail = s; tail = &s->next;
    }
    advance(cc);
    scope_pop(cc);
    return n;
}

/* ---- function definitions ---------------------------------------------------*/
static void func_def(Cc *cc, Sym *s)
{
    Param *p;
    int i;

    if (s->defined) ucc_err_tok(cc, cc->tok, "function redefined", s->name);
    s->defined = 1;
    cc->cur_ret = s->ty->base;
    cc->lvsize = 0;
    scope_push(cc);
    for (p = s->ty->params, i = 0; p; p = p->next, i++) {
        Sym *ps;
        Tok fake;
        memset(&fake, 0, sizeof fake);
        fake.kind = TK_IDENT;
        fake.p = p->name ? p->name : "arg";
        fake.len = (int)strlen(fake.p);
        if (!p->name)
            ucc_err_tok(cc, cc->tok, "parameter name required", s->name);
        ps = sym_new(cc, &fake, p->ty, SYM_LOCAL);
        ps->lvoff = 16 + 8 * i;                 /* MS x64 home slots */
    }
    {
        Node *body = block(cc);
        scope_pop(cc);
        ucc_gen_func(cc, s, body);
    }
}

/* ---- top level ---------------------------------------------------------------*/
static void top_decl(Cc *cc)
{
    int storage = 0;
    Type *base = declspec(cc, &storage);
    int first = 1;

    if (eat_punct(cc, P_SEMI)) return;              /* struct/enum tag decl */

    for (;;) {
        Tok *name = 0;
        Type *ty;
        if (!first) expect(cc, P_COMMA, "expected , or ;");
        first = 0;
        ty = declarator(cc, base, &name);
        if (!name) ucc_err_tok(cc, cc->tok, "name expected in declaration", 0);

        if (storage & ST_TYPEDEF) {
            sym_new(cc, name, ty, SYM_TYPEDEF);
            if (at_punct(cc, P_SEMI)) break;
            continue;
        }

        if (ty->kind == TY_FUNC) {
            Sym *s = sym_find(cc, name->p, name->len);
            if (s && s->cls == SYM_FUNC) {
                /* re-declaration; adopt the later parameter list if the
                 * first was () */
                if (s->ty->nparams < 0) s->ty = ty;
            } else if (s) {
                ucc_err_tok(cc, name, "redeclared as a function", 0);
            } else {
                s = sym_new(cc, name, ty, SYM_FUNC);
                s->is_static = (u8)((storage & ST_STATIC) != 0);
            }
            if (at_punct(cc, P_LBRACE)) { func_def(cc, s); return; }
            if (at_punct(cc, P_SEMI)) break;
            continue;
        }

        /* global variable */
        {
            Sym *s = sym_find(cc, name->p, name->len);
            if (s && !(s->cls == SYM_GLOBAL && !s->defined))
                ucc_err_tok(cc, name, "redefined", 0);
            if (!s) {
                s = sym_new(cc, name, ty, SYM_GLOBAL);
                s->is_static = (u8)((storage & ST_STATIC) != 0);
            }
            s->ty = ty;
            if (storage & ST_EXTERN) {
                /* extern data: only KernelApi-style declarations end up here;
                 * there is no data import channel, so require a definition
                 * later in this unit */
                if (at_punct(cc, P_SEMI)) break;
                continue;
            }
            if (eat_punct(cc, P_ASSIGN)) global_var(cc, s, 1);
            else                          global_var(cc, s, 0);
        }
        if (at_punct(cc, P_SEMI)) break;
    }
    expect(cc, P_SEMI, "expected ; after declaration");
}

/* ============================================================================
 * DRIVER
 * ========================================================================== */
static Cc *gCc;                    /* for ucc_summary only */

const char *ucc_summary(void) { return gCc ? gCc->summary : ""; }

long ucc_compile(const char *src, long srclen, const char *srcname,
                 UccIncRead inc, void *incctx,
                 void *work, long worklen,
                 unsigned char *out, long outmax,
                 UccDiag *diag, int maxdiag, int *ndiag)
{
    Cc *cc;
    long r = -1;

    if (!work || worklen < (1 << 20) || !diag || maxdiag < 1) return -1;
    cc = (Cc *)work;
    memset(cc, 0, sizeof *cc);
    cc->wk = (u8 *)work; cc->wkcap = worklen;
    cc->wkuse = (long)((sizeof *cc + 15) & ~15UL);
    cc->diag = diag; cc->maxdiag = maxdiag; cc->ndiag = 0;
    cc->memcpy_imp = -1;
    gCc = cc;

    if (__builtin_setjmp(cc->jb)) {
        *ndiag = cc->ndiag;
        return -1;
    }

    /* section images from the arena: code ~ 1/3, data ~ 1/3 of the buffer */
    cc->codecap = (int)(worklen / 3);
    cc->code = ucc_alloc(cc, cc->codecap);
    cc->datacap = (int)(worklen / 3);
    cc->data = ucc_alloc(cc, cc->datacap);

    cc->scope = &cc->gscope;

    {
        Tok **tail;
        Tok *raw = lex_unit(cc, src, srclen, srcname ? srcname : "SRC",
                            inc, incctx, 0, &tail);
        cc->tok = expand_stream(cc, raw);
    }

    while (peek(cc)->kind != TK_EOF)
        top_decl(cc);

    r = ucc_emit_uno(cc, out, outmax);
    *ndiag = cc->ndiag;
    return cc->ndiag ? -1 : r;
}
